// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "Primitive3DGUT.cuh"
#include "FusedProjectionBwdOptim_kernel.cuh"

template void fused_projection_bwd_optimizer_3dgs_kernel_wrapper<
    Vanilla3DGUT,
    ssplat::CameraModelType::PINHOLE,
    HessianDiagonalOutputMode::None,
    false
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT::WorldBuffer splats_world,
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t *__restrict__ camera_id_bounds,   // [N]
    const int32_t *__restrict__ camera_ids,   // [nnz]
    const float4 *__restrict__ aabb,   // [C, N, 4] or [nnz, 4]
    // grad outputs from rasterization
    Vanilla3DGUT::WorldBuffer v_splats_world,
    Vanilla3DGUT::WorldBuffer vr_splats_world,
    Vanilla3DGUT::WorldBuffer h_splats_world,
    Vanilla3DGUT::ScreenBuffer v_splats_screen,
    Vanilla3DGUT::ScreenBuffer vr_splats_screen,
    Vanilla3DGUT::ScreenBuffer h_splats_screen,
    // optimizer states
    Vanilla3DGUT::WorldBuffer g1_splats_world,
    Vanilla3DGUT::WorldBuffer g2_splats_world,
    // float *__restrict__ v_viewmats // [C, 4, 4] optional
    // optimizer params
    const float* __restrict__ radii,
    const float lr_means,
    const float lr_quats,
    const float lr_scales,
    const float lr_opacs,
    const float lr_features_dc,
    const float lr_features_sh,
    const float mcmc_noise_scalar,
    const float min_opacity,
    const float max_gauss_ratio,
    const float scale_regularization_weight,
    const float mcmc_opacity_reg_weight,
    const float mcmc_scale_reg_weight,
    const float erank_reg_weight,
    const float erank_reg_weight_s3,
    const float quat_norm_reg_weight,
    const float mrnf_opacity_decay_factor,
    const float mrnf_scale_decay_factor,
    const int32_t scalar_step,
    const int32_t* __restrict__ steps
);
