// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "Primitive3DGS.cuh"
#include "ProjectionBwd_kernel.cuh"

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGS<0>,
    CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<0>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGS<0>::ScreenBuffer v_splats_screen,
    // grad inputs
    Vanilla3DGS<0>::WorldBuffer v_splats_world,
    float * v_viewmats // [C, 4, 4] optional
);

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGS<0>,
    CameraModelType::FISHEYE
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<0>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGS<0>::ScreenBuffer v_splats_screen,
    // grad inputs
    Vanilla3DGS<0>::WorldBuffer v_splats_world,
    float * v_viewmats // [C, 4, 4] optional
);

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGS<0>,
    CameraModelType::EQUISOLID
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<0>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGS<0>::ScreenBuffer v_splats_screen,
    // grad inputs
    Vanilla3DGS<0>::WorldBuffer v_splats_world,
    float * v_viewmats // [C, 4, 4] optional
);

template void projection_fused_bwd_kernel_wrapper<
    MipSplatting<0>,
    CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    MipSplatting<0>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    MipSplatting<0>::ScreenBuffer v_splats_screen,
    // grad inputs
    MipSplatting<0>::WorldBuffer v_splats_world,
    float * v_viewmats // [C, 4, 4] optional
);

template void projection_fused_bwd_kernel_wrapper<
    MipSplatting<0>,
    CameraModelType::FISHEYE
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    MipSplatting<0>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    MipSplatting<0>::ScreenBuffer v_splats_screen,
    // grad inputs
    MipSplatting<0>::WorldBuffer v_splats_world,
    float * v_viewmats // [C, 4, 4] optional
);

template void projection_fused_bwd_kernel_wrapper<
    MipSplatting<0>,
    CameraModelType::EQUISOLID
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    MipSplatting<0>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    MipSplatting<0>::ScreenBuffer v_splats_screen,
    // grad inputs
    MipSplatting<0>::WorldBuffer v_splats_world,
    float * v_viewmats // [C, 4, 4] optional
);

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGS<1>,
    CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<1>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGS<1>::ScreenBuffer v_splats_screen,
    // grad inputs
    Vanilla3DGS<1>::WorldBuffer v_splats_world,
    float * v_viewmats // [C, 4, 4] optional
);

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGS<1>,
    CameraModelType::FISHEYE
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<1>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGS<1>::ScreenBuffer v_splats_screen,
    // grad inputs
    Vanilla3DGS<1>::WorldBuffer v_splats_world,
    float * v_viewmats // [C, 4, 4] optional
);

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGS<1>,
    CameraModelType::EQUISOLID
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<1>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGS<1>::ScreenBuffer v_splats_screen,
    // grad inputs
    Vanilla3DGS<1>::WorldBuffer v_splats_world,
    float * v_viewmats // [C, 4, 4] optional
);
