// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "Primitive3DGUT.cuh"
#include "ProjectionBwd_kernel.cuh"

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGUT<1>,
    ssplat::CameraModelType::EQUISOLID,
    HessianDiagonalOutputMode::Position
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<1>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGUT<1>::ScreenBuffer v_splats_screen,
    Vanilla3DGUT<1>::ScreenBuffer vr_splats_screen,
    Vanilla3DGUT<1>::ScreenBuffer h_splats_screen,
    // grad inputs
    Vanilla3DGUT<1>::WorldBuffer v_splats_world,
    float3* vr_world_pos_buffer,
    float3* h_world_pos_buffer,
    Vanilla3DGUT<1>::WorldBuffer vr_splats_world,
    Vanilla3DGUT<1>::WorldBuffer h_splats_world,
    float * v_viewmats // [C, 4, 4] optional
);

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGUT<1>,
    ssplat::CameraModelType::EQUISOLID,
    HessianDiagonalOutputMode::AllReasonable
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<1>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGUT<1>::ScreenBuffer v_splats_screen,
    Vanilla3DGUT<1>::ScreenBuffer vr_splats_screen,
    Vanilla3DGUT<1>::ScreenBuffer h_splats_screen,
    // grad inputs
    Vanilla3DGUT<1>::WorldBuffer v_splats_world,
    float3* vr_world_pos_buffer,
    float3* h_world_pos_buffer,
    Vanilla3DGUT<1>::WorldBuffer vr_splats_world,
    Vanilla3DGUT<1>::WorldBuffer h_splats_world,
    float * v_viewmats // [C, 4, 4] optional
);
