// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "Primitive3DGUT.cuh"
#include "ProjectionBwdQuantGrad_kernel.cuh"

template void projection_bwd_quantgrad_kernel_wrapper<
    Vanilla3DGUT<2>,
    CameraModelType::FISHEYE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    Vanilla3DGUT<2>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    Vanilla3DGUT<2>::WorldBuffer v_splats_world,
    Vanilla3DGUT<2>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    Vanilla3DGUT<2>,
    CameraModelType::EQUISOLID
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    Vanilla3DGUT<2>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    Vanilla3DGUT<2>::WorldBuffer v_splats_world,
    Vanilla3DGUT<2>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    Vanilla3DGUT<2>,
    CameraModelType::EQUIRECTANGULAR
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    Vanilla3DGUT<2>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    Vanilla3DGUT<2>::WorldBuffer v_splats_world,
    Vanilla3DGUT<2>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    Vanilla3DGUT<3>,
    CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    Vanilla3DGUT<3>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    Vanilla3DGUT<3>::WorldBuffer v_splats_world,
    Vanilla3DGUT<3>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    Vanilla3DGUT<3>,
    CameraModelType::FISHEYE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    Vanilla3DGUT<3>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    Vanilla3DGUT<3>::WorldBuffer v_splats_world,
    Vanilla3DGUT<3>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    Vanilla3DGUT<3>,
    CameraModelType::EQUISOLID
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    Vanilla3DGUT<3>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    Vanilla3DGUT<3>::WorldBuffer v_splats_world,
    Vanilla3DGUT<3>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    Vanilla3DGUT<3>,
    CameraModelType::EQUIRECTANGULAR
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    Vanilla3DGUT<3>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    Vanilla3DGUT<3>::WorldBuffer v_splats_world,
    Vanilla3DGUT<3>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    Vanilla3DGUT<4>,
    CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    Vanilla3DGUT<4>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    Vanilla3DGUT<4>::WorldBuffer v_splats_world,
    Vanilla3DGUT<4>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    Vanilla3DGUT<4>,
    CameraModelType::FISHEYE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    Vanilla3DGUT<4>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    Vanilla3DGUT<4>::WorldBuffer v_splats_world,
    Vanilla3DGUT<4>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);
