// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "PrimitiveVoxel.cuh"
#include "ProjectionBwd_kernel.cuh"

template void projection_fused_bwd_kernel_wrapper<
    VoxelPrimitive,
    ssplat::CameraModelType::PINHOLE,
    HessianDiagonalOutputMode::None
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t B,
    const uint32_t C,
    const uint32_t N,
    const VoxelPrimitive::WorldBuffer splats_world,
    const float * viewmats, // [B, C, 4, 4]
    const float4 * intrins,  // [B, C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [B, C, N, 4]
    // grad outputs
    VoxelPrimitive::ScreenBuffer v_splats_screen,
    VoxelPrimitive::ScreenBuffer vr_splats_screen,
    VoxelPrimitive::ScreenBuffer h_splats_screen,
    // grad inputs
    VoxelPrimitive::WorldBuffer v_splats_world,
    float3* vr_world_pos_buffer,
    float3* h_world_pos_buffer,
    VoxelPrimitive::WorldBuffer vr_splats_world,
    VoxelPrimitive::WorldBuffer h_splats_world,
    float * v_viewmats // [B, C, 4, 4] optional
);
