// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "Primitive3DGUT.cuh"
#include "ProjectionFwd_kernel.cuh"

template void projection_fused_fwd_kernel_wrapper<
    Vanilla3DGUT<0>,
    CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<0>::WorldBuffer splats_world,
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    float4 *__restrict__ aabbs,         // [C, N, 4]
    float *__restrict__ sorting_depths,  // [C, N, 1]
    float *__restrict__ radii,  // [N, 1]
    Vanilla3DGUT<0>::ScreenBuffer splats_screen,
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits
);

template void projection_fused_fwd_kernel_wrapper<
    Vanilla3DGUT<0>,
    CameraModelType::FISHEYE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<0>::WorldBuffer splats_world,
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    float4 *__restrict__ aabbs,         // [C, N, 4]
    float *__restrict__ sorting_depths,  // [C, N, 1]
    float *__restrict__ radii,  // [N, 1]
    Vanilla3DGUT<0>::ScreenBuffer splats_screen,
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits
);

template void projection_fused_fwd_kernel_wrapper<
    Vanilla3DGUT<0>,
    CameraModelType::EQUISOLID
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<0>::WorldBuffer splats_world,
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    float4 *__restrict__ aabbs,         // [C, N, 4]
    float *__restrict__ sorting_depths,  // [C, N, 1]
    float *__restrict__ radii,  // [N, 1]
    Vanilla3DGUT<0>::ScreenBuffer splats_screen,
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits
);

template void projection_fused_fwd_kernel_wrapper<
    Vanilla3DGUT<1>,
    CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<1>::WorldBuffer splats_world,
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    float4 *__restrict__ aabbs,         // [C, N, 4]
    float *__restrict__ sorting_depths,  // [C, N, 1]
    float *__restrict__ radii,  // [N, 1]
    Vanilla3DGUT<1>::ScreenBuffer splats_screen,
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits
);

template void projection_fused_fwd_kernel_wrapper<
    Vanilla3DGUT<1>,
    CameraModelType::FISHEYE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<1>::WorldBuffer splats_world,
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    float4 *__restrict__ aabbs,         // [C, N, 4]
    float *__restrict__ sorting_depths,  // [C, N, 1]
    float *__restrict__ radii,  // [N, 1]
    Vanilla3DGUT<1>::ScreenBuffer splats_screen,
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits
);

template void projection_fused_fwd_kernel_wrapper<
    Vanilla3DGUT<1>,
    CameraModelType::EQUISOLID
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<1>::WorldBuffer splats_world,
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    float4 *__restrict__ aabbs,         // [C, N, 4]
    float *__restrict__ sorting_depths,  // [C, N, 1]
    float *__restrict__ radii,  // [N, 1]
    Vanilla3DGUT<1>::ScreenBuffer splats_screen,
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits
);

template void projection_fused_fwd_kernel_wrapper<
    Vanilla3DGUT<2>,
    CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<2>::WorldBuffer splats_world,
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    float4 *__restrict__ aabbs,         // [C, N, 4]
    float *__restrict__ sorting_depths,  // [C, N, 1]
    float *__restrict__ radii,  // [N, 1]
    Vanilla3DGUT<2>::ScreenBuffer splats_screen,
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits
);

template void projection_fused_fwd_kernel_wrapper<
    Vanilla3DGUT<2>,
    CameraModelType::FISHEYE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<2>::WorldBuffer splats_world,
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    float4 *__restrict__ aabbs,         // [C, N, 4]
    float *__restrict__ sorting_depths,  // [C, N, 1]
    float *__restrict__ radii,  // [N, 1]
    Vanilla3DGUT<2>::ScreenBuffer splats_screen,
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits
);

template void projection_fused_fwd_kernel_wrapper<
    Vanilla3DGUT<2>,
    CameraModelType::EQUISOLID
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<2>::WorldBuffer splats_world,
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    float4 *__restrict__ aabbs,         // [C, N, 4]
    float *__restrict__ sorting_depths,  // [C, N, 1]
    float *__restrict__ radii,  // [N, 1]
    Vanilla3DGUT<2>::ScreenBuffer splats_screen,
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits
);
