// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "Primitive3DGUT_SV.cuh"
#include "ProjectionFwd_kernel.cuh"

template void projection_fused_fwd_kernel_wrapper<
    SphericalVoronoi3DGUT<5>,
    ssplat::CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    const uint32_t B,
    const uint32_t C,
    const uint32_t N,
    const SphericalVoronoi3DGUT<5>::World::Buffer splats_world,
    const float *__restrict__ viewmats, // [B, C, 4, 4]
    const float4 *__restrict__ intrins,  // [B, C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    float4 *__restrict__ aabbs,         // [B, C, N, 4]
    SphericalVoronoi3DGUT<5>::Screen::Buffer splats_screen
);
