// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "Primitive3DGS.cuh"
#include "ProjectionPackedFwd_kernel.cuh"

template void projection_packed_mask_kernel_wrapper<
    MipSplatting<4>,
    ssplat::CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    MipSplatting<4>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    bool *__restrict__ intersection_mask  // [C, N]
);

template void projection_packed_mask_kernel_wrapper<
    MipSplatting<4>,
    ssplat::CameraModelType::FISHEYE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    MipSplatting<4>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    bool *__restrict__ intersection_mask  // [C, N]
);

template void projection_packed_mask_kernel_wrapper<
    MipSplatting<4>,
    ssplat::CameraModelType::EQUISOLID
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    MipSplatting<4>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    bool *__restrict__ intersection_mask  // [C, N]
);
