// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "Primitive3DGS.cuh"
#include "RasterizationBwd_kernel.cuh"

template void rasterize_to_pixels_bwd_kernel_wrapper<
    Vanilla3DGS,
    true,
    true
>(
    cudaStream_t stream,
    const uint32_t I,
    const uint32_t n_isects,
    // fwd inputs
    Vanilla3DGS::Screen::Buffer splat_buffer,
    const float *__restrict__ backgrounds, // [..., CDIM] or [nnz, CDIM]
    const bool *__restrict__ masks,           // [..., tile_height, tile_width]
    const uint32_t image_width,
    const uint32_t image_height,
    const uint32_t tile_width,
    const uint32_t tile_height,
    const int32_t *__restrict__ tile_offsets, // [..., tile_height, tile_width]
    const int32_t *__restrict__ flatten_ids,  // [n_isects]
    // fwd outputs
    const float
        *__restrict__ render_Ts,      // [..., image_height, image_width, 1]
    const int32_t *__restrict__ last_ids, // [..., image_height, image_width]
    Vanilla3DGS::RenderOutput::Buffer render_output_buffer,
    Vanilla3DGS::RenderOutput::Buffer render2_output_buffer,
    const float *__restrict__ loss_map_buffer,           // [..., image_height, image_width, 1]
    // grad outputs
    Vanilla3DGS::RenderOutput::Buffer v_render_output_buffer,
    const float *__restrict__ v_render_Ts, // [..., image_height, image_width, 1]
    Vanilla3DGS::RenderOutput::Buffer v_distortions_output_buffer,
    // grad inputs
    Vanilla3DGS::Screen::Buffer v_splat_buffer,
    Vanilla3DGS::Screen::Buffer vr_splat_buffer,
    Vanilla3DGS::Screen::Buffer h_splat_buffer
);
