// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "PrimitiveVoxel.cuh"
#include "RasterizationEval3DFwd_kernel.cuh"

template void rasterize_to_pixels_eval3d_fwd_kernel_wrapper<
    VoxelPrimitive,
    ssplat::CameraModelType::FISHEYE,
    true,
    true,
    true
>(
    cudaStream_t stream,
    const uint32_t I,
    const uint32_t N,
    const uint32_t n_isects,
    const uint32_t *__restrict__ gaussian_ids,  // [nnz] optional, for packed mode
    const VoxelPrimitive::Screen::Buffer splat_buffer,
    const float *__restrict__ viewmats, // [B, C, 4, 4]
    const float4 *__restrict__ intrins,  // [B, C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const float3 *__restrict__ backgrounds, // [I, 3]
    const float *__restrict__ accum_weight_map,  // [B, C, image_width, image_height]
    const bool *__restrict__ max_blending_masks,  // [B, C, image_width, image_height]
    const uint32_t image_width,
    const uint32_t image_height,
    const uint32_t tile_width,
    const uint32_t tile_height,
    const int32_t *__restrict__ tile_offsets, // [I, tile_height, tile_width]
    const int32_t *__restrict__ flatten_ids,  // [n_isects]
    VoxelPrimitive::RenderOutput::Buffer render_colors, // [I, image_height, image_width, ...]
    float *__restrict__ render_Ts, // [I, image_height, image_width, 1]
    int32_t *__restrict__ last_ids, // [I, image_height, image_width]
    VoxelPrimitive::RenderOutput::Buffer render_colors2, // [I, image_height, image_width, ...]
    VoxelPrimitive::RenderOutput::Buffer render_distortions, // [I, image_height, image_width, ...]
    float* __restrict__ out_accum_weight,
    float* __restrict__ out_max_blending
);
