#!/usr/bin/env python3
# Generate the near-minimax (Chebyshev) polynomial coefficients used by the
# range-reduced transcendentals in shaders/src/sfm/shaders/common/df.slang and shaders/src/sfm/shaders/common/dmath.slang.
#
#   python3 tools/sfm/genpoly.py            # emit the Slang constant blocks
#   python3 tools/sfm/genpoly.py --survey   # error vs degree + fp32-tail magnitudes
#
# Chebyshev interpolation is within a hair of true minimax (L^inf/Remez) at
# these degrees and needs several fewer terms than Taylor for the same
# interval accuracy (exp: degree 10 vs 14, sin/cos in s=r^2: 6 vs 8).
#
# Reduced ranges (must match the shader argument reduction):
#   exp:     r in [-ln2/2, ln2/2]   after  r = a - round(a/ln2) ln2
#   sincos:  s = r^2 in [0,(pi/4)^2] after r = a - round(a*2/pi) pi/2
#
# df split evaluation: head coefficients are (hi, lo) fp32 pairs evaluated
# with full DF Horner steps; tail terms whose total contribution is below
# ~6e-9 (so fp32 rounding of the tail stays under one df ulp, ~3e-16) are
# evaluated in plain fp32. The split points below were chosen from the
# --survey tail-magnitude table; re-check them if degrees or ranges change.
#
# Coefficient error targets: df needs poly rel err <~ 5e-16 (df arithmetic
# noise is ~1e-14 anyway); double needs <~ 1.2e-16 (about one ulp).
import sys

import mpmath as mp
import numpy as np

mp.mp.prec = 200

LN2 = mp.log(2)
H_EXP = LN2 / 2          # |r| bound after exp range reduction
H_S = (mp.pi / 4) ** 2   # s = r^2 bound after sincos range reduction

FEXP = lambda r: mp.exp(r)
FSIN = lambda s: mp.sin(mp.sqrt(s)) / mp.sqrt(s) if s > 0 else mp.mpf(1)
FCOS = lambda s: mp.cos(mp.sqrt(s))

# (name, f, a, b, df config: degree + first fp32-tail index, double degree)
SPECS = [
    ("exp", FEXP, -H_EXP, H_EXP, 10, 8, 11),
    ("sin", FSIN, mp.mpf(0), H_S, 6, 5, 6),
    ("cos", FCOS, mp.mpf(0), H_S, 6, 6, 7),
]


def cheb(f, a, b, deg):
    """Chebyshev-node interpolation, monomial coefficients (ascending)."""
    n = deg + 1
    nodes = [(a + b) / 2 + (b - a) / 2 * mp.cos(mp.pi * (2 * k + 1) / (2 * n))
             for k in range(n)]
    A = mp.matrix(n, n)
    for i, x in enumerate(nodes):
        p = mp.mpf(1)
        for j in range(n):
            A[i, j] = p
            p *= x
    c = mp.lu_solve(A, mp.matrix([f(x) for x in nodes]))
    return [c[i] for i in range(n)]


def maxerr(f, coef, a, b, n=4000):
    e = mp.mpf(0)
    for k in range(n + 1):
        x = a + (b - a) * mp.mpf(k) / n
        p = mp.mpf(0)
        for c in reversed(coef):
            p = p * x + c
        fx = f(x)
        e = max(e, abs(p - fx) / max(abs(fx), mp.mpf("1e-300")))
    return e


def tailmag(coef, k, a, b, n=2000):
    """max |sum_{i>=k} c_i x^i| over [a,b] (fp32-tail feasibility)."""
    m = mp.mpf(0)
    for t in range(n + 1):
        x = a + (b - a) * mp.mpf(t) / n
        p = mp.mpf(0)
        for c in reversed(coef[k:]):
            p = p * x + c
        m = max(m, abs(p * x ** k))
    return m


def survey():
    for name, f, a, b, dfdeg, _, dbldeg in SPECS:
        print(f"== {name} on [{mp.nstr(a, 6)}, {mp.nstr(b, 6)}]")
        for d in range(dfdeg - 2, max(dfdeg, dbldeg) + 2):
            print(f"  minimax deg {d:2d}: max rel err {mp.nstr(maxerr(f, cheb(f, a, b, d), a, b), 3)}")
        c = cheb(f, a, b, dfdeg)
        print("  tail magnitudes (fp32 tail wants mag*6e-8 < ~3e-16):")
        for k in range(3, dfdeg + 1):
            print(f"    from i={k}: {mp.nstr(tailmag(c, k, a, b), 3)}")


def df_pair(c):
    hi = np.float32(float(c))
    lo = np.float32(float(mp.mpf(c) - mp.mpf(float(hi))))
    return f"dfc({float(hi)!r}f, {float(lo)!r}f)"


def emit():
    print("// generated by tools/sfm/genpoly.py -- paste into shaders/src/sfm/shaders/common/df.slang")
    for name, f, a, b, deg, khead, _ in SPECS:
        c = cheb(f, a, b, deg)
        uname = name.capitalize()
        print(f"// {name}: degree {deg}, max rel err {mp.nstr(maxerr(f, c, a, b), 3)}")
        print(f"static const DF kDf{uname}C[{khead}] = {{")
        for i in range(khead):
            print(f"    {df_pair(c[i])},")
        print("};")
        tail = [float(np.float32(float(x))) for x in c[khead:deg + 1]]
        print(f"static const float kDf{uname}Tail[{len(tail)}] = {{ "
              + ", ".join(f"{t!r}f" for t in tail) + " };")
    print()
    print("// generated by tools/sfm/genpoly.py -- paste into shaders/src/sfm/shaders/common/dmath.slang")
    for name, f, a, b, _, _, deg in SPECS:
        c = cheb(f, a, b, deg)
        print(f"// {name}: degree {deg}, max rel err {mp.nstr(maxerr(f, c, a, b), 3)}")
        print(f"static const double kD{name.capitalize()}Coef[{len(c)}] = {{")
        row = []
        for x in c:
            row.append(mp.nstr(x, 20))
            if len(row) == 3:
                print("    " + ", ".join(row) + ",")
                row = []
        if row:
            print("    " + ", ".join(row) + ",")
        print("};")


if __name__ == "__main__":
    survey() if "--survey" in sys.argv[1:] else emit()
