var createWASMModule = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var n=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=(b,a)=>{throw a;};"undefined"!=typeof __filename?_scriptName=__filename:ba&&(_scriptName=self.location.href);var p="",ea,r;
if(ca){var fs=require("fs");p=__dirname+"/";r=b=>{b=v(b)?new URL(b):b;return fs.readFileSync(b)};ea=async b=>{b=v(b)?new URL(b):b;return fs.readFileSync(b,void 0)};process.argv.slice(2);da=(b,a)=>{process.exitCode=b;throw a;}}else if(aa||ba){try{p=(new URL(".",_scriptName)).href}catch{}ba&&(r=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)});ea=async b=>{if(v(b))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",
b,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var a=await fetch(b,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var fa=console.log.bind(console),w=console.error.bind(console),A,ha=!1,v=b=>b.startsWith("file://"),ia,ja,B,ka,C,la,D,F,G,ma,na,oa,pa,qa=!1;
function ra(){var b=B.buffer;ka=new Int8Array(b);la=new Int16Array(b);C=new Uint8Array(b);D=new Uint16Array(b);F=new Int32Array(b);G=new Uint32Array(b);ma=new Float32Array(b);na=new Float64Array(b);oa=new BigInt64Array(b);pa=new BigUint64Array(b)}var H=0,I=null;function sa(b){n.onAbort?.(b);b="Aborted("+b+")";w(b);ha=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ja?.(b);throw b;}var ta;
async function ua(b){if(!A)try{var a=await ea(b);return new Uint8Array(a)}catch{}if(b==ta&&A)b=new Uint8Array(A);else if(r)b=r(b);else throw"both async and sync fetching of the wasm failed";return b}async function va(b,a){try{var c=await ua(b);return await WebAssembly.instantiate(c,a)}catch(d){w(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(b){var a=ta;if(!A&&"function"==typeof WebAssembly.instantiateStreaming&&!v(a)&&!ca)try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){w(`wasm streaming compile failed: ${d}`),w("falling back to ArrayBuffer instantiation")}return va(a,b)}class xa{name="ExitStatus";constructor(b){this.message=`Program terminated with exit(${b})`;this.status=b}}
var ya=b=>{for(;0<b.length;)b.shift()(n)},za=[],Aa=[],Ba=()=>{var b=n.preRun.shift();Aa.push(b)},Ca=!0,Da="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(b,a=0,c=NaN)=>{var d=a+c;for(c=a;b[c]&&!(c>=d);)++c;if(16<c-a&&b.buffer&&Da)return Da.decode(b.subarray(a,c));for(d="";a<c;){var e=b[a++];if(e&128){var f=b[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=b[a++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|b[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d};class Fa{constructor(b){this.U=b-24}}var Ga=0,Ha=0,Ia={},Ja=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function K(b){return this.fromWireType(G[b>>2])}
var L={},M={},Ka={},La=class extends Error{constructor(b){super(b);this.name="InternalError"}},O=(b,a,c)=>{function d(g){g=c(g);if(g.length!==b.length)throw new La("Mismatched type converter count");for(var m=0;m<b.length;++m)N(b[m],g[m])}b.forEach(g=>Ka[g]=a);var e=Array(a.length),f=[],h=0;a.forEach((g,m)=>{M.hasOwnProperty(g)?e[m]=M[g]:(f.push(g),L.hasOwnProperty(g)||(L[g]=[]),L[g].push(()=>{e[m]=M[g];++h;h===f.length&&d(e)}))});0===f.length&&d(e)},P=b=>{for(var a="";;){var c=C[b++];if(!c)return a;
a+=String.fromCharCode(c)}},Q=class extends Error{constructor(b){super(b);this.name="BindingError"}},Ma=b=>{throw new Q(b);};function Na(b,a,c={}){var d=a.name;if(!b)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(M.hasOwnProperty(b)){if(c.za)return;throw new Q(`Cannot register type '${d}' twice`);}M[b]=a;delete Ka[b];L.hasOwnProperty(b)&&(a=L[b],delete L[b],a.forEach(e=>e()))}function N(b,a,c={}){return Na(b,a,c)}
var Oa=(b,a,c)=>{switch(a){case 1:return c?d=>ka[d]:d=>C[d];case 2:return c?d=>la[d>>1]:d=>D[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];case 8:return c?d=>oa[d>>3]:d=>pa[d>>3];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Pa=b=>{throw new Q(b.S.V.T.name+" instance already deleted");},Qa=!1,Ra=()=>{},R=b=>{if("undefined"===typeof FinalizationRegistry)return R=a=>a,b;Qa=new FinalizationRegistry(a=>{a=a.S;--a.count.value;0===a.count.value&&(a.X?a.$.ba(a.X):a.V.T.ba(a.U))});R=
a=>{var c=a.S;c.X&&Qa.register(a,{S:c},a);return a};Ra=a=>{Qa.unregister(a)};return R(b)},Sa=[];function Ta(){}
var Ua=(b,a)=>Object.defineProperty(a,"name",{value:b}),Va={},Wa=(b,a,c)=>{if(void 0===b[a].W){var d=b[a];b[a]=function(...e){if(!b[a].W.hasOwnProperty(e.length))throw new Q(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].W})!`);return b[a].W[e.length].apply(this,e)};b[a].W=[];b[a].W[d.fa]=d}},Xa=(b,a,c)=>{if(n.hasOwnProperty(b)){if(void 0===c||void 0!==n[b].W&&void 0!==n[b].W[c])throw new Q(`Cannot register public name '${b}' twice`);Wa(n,b,b);if(n[b].W.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
n[b].W[c]=a}else n[b]=a,n[b].fa=c},Ya=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function Za(b,a,c,d,e,f,h,g){this.name=b;this.constructor=a;this.ea=c;this.ba=d;this.Y=e;this.ua=f;this.ia=h;this.sa=g;this.Ca=[]}
var $a=(b,a,c)=>{for(;a!==c;){if(!a.ia)throw new Q(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.ia(b);a=a.Y}return b},ab=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b};
function bb(b,a){if(null===a){if(this.la)throw new Q(`null is not a valid ${this.name}`);return 0}if(!a.S)throw new Q(`Cannot pass "${ab(a)}" as a ${this.name}`);if(!a.S.U)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);return $a(a.S.U,a.S.V.T,this.T)}
function cb(b,a){if(null===a){if(this.la)throw new Q(`null is not a valid ${this.name}`);if(this.ka){var c=this.ma();null!==b&&b.push(this.ba,c);return c}return 0}if(!a||!a.S)throw new Q(`Cannot pass "${ab(a)}" as a ${this.name}`);if(!a.S.U)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ja&&a.S.V.ja)throw new Q(`Cannot convert argument of type ${a.S.$?a.S.$.name:a.S.V.name} to parameter type ${this.name}`);c=$a(a.S.U,a.S.V.T,this.T);if(this.ka){if(void 0===a.S.X)throw new Q("Passing raw pointer to smart pointer is illegal");
switch(this.Ha){case 0:if(a.S.$===this)c=a.S.X;else throw new Q(`Cannot convert argument of type ${a.S.$?a.S.$.name:a.S.V.name} to parameter type ${this.name}`);break;case 1:c=a.S.X;break;case 2:if(a.S.$===this)c=a.S.X;else{var d=a.clone();c=this.Da(c,S(()=>d["delete"]()));null!==b&&b.push(this.ba,c)}break;default:throw new Q("Unsupporting sharing policy");}}return c}
function db(b,a){if(null===a){if(this.la)throw new Q(`null is not a valid ${this.name}`);return 0}if(!a.S)throw new Q(`Cannot pass "${ab(a)}" as a ${this.name}`);if(!a.S.U)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.S.V.ja)throw new Q(`Cannot convert argument of type ${a.S.V.name} to parameter type ${this.name}`);return $a(a.S.U,a.S.V.T,this.T)}
var eb=(b,a,c)=>{if(a===c)return b;if(void 0===c.Y)return null;b=eb(b,a,c.Y);return null===b?null:c.sa(b)},fb={},gb=(b,a)=>{if(void 0===a)throw new Q("ptr should not be undefined");for(;b.Y;)a=b.ia(a),b=b.Y;return fb[a]},hb=(b,a)=>{if(!a.V||!a.U)throw new La("makeClassHandle requires ptr and ptrType");if(!!a.$!==!!a.X)throw new La("Both smartPtrType and smartPtr must be specified");a.count={value:1};return R(Object.create(b,{S:{value:a,writable:!0}}))};
function ib(b,a,c,d,e,f,h,g,m,k,l){this.name=b;this.T=a;this.la=c;this.ja=d;this.ka=e;this.Ba=f;this.Ha=h;this.qa=g;this.ma=m;this.Da=k;this.ba=l;e||void 0!==a.Y?this.toWireType=cb:(this.toWireType=d?bb:db,this.Z=null)}
var jb=(b,a,c)=>{if(!n.hasOwnProperty(b))throw new La("Replacing nonexistent public symbol");void 0!==n[b].W&&void 0!==c?n[b].W[c]=a:(n[b]=a,n[b].fa=c)},kb=[],lb,T=(b,a)=>{b=P(b);var c;(c=kb[a])||(kb[a]=c=lb.get(a));if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${b}: ${a}`);return c};class mb extends Error{}
var ob=b=>{b=nb(b);var a=P(b);W(b);return a},pb=(b,a)=>{function c(f){e[f]||M[f]||(Ka[f]?Ka[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};a.forEach(c);throw new mb(`${b}: `+d.map(ob).join([", "]));},qb=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(G[a+4*d>>2]);return c};function rb(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].Z)return!0;return!1}
function tb(b,a,c,d,e,f){var h=a.length;if(2>h)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==a[1]&&null!==c,m=rb(a);c="void"!==a[0].name;d=[b,Ma,d,e,Ja,a[0],a[1]];for(e=0;e<h-2;++e)d.push(a[e+2]);if(!m)for(e=g?1:2;e<a.length;++e)null!==a[e].Z&&d.push(a[e].Z);m=rb(a);e=a.length-2;var k=[],l=["fn"];g&&l.push("thisWired");for(h=0;h<e;++h)k.push(`arg${h}`),l.push(`arg${h}Wired`);k=k.join(",");l=l.join(",");k=`return function (${k}) {\n`;m&&
(k+="var destructors = [];\n");var q=m?"destructors":"null",t="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");g&&(k+=`var thisWired = classParam['toWireType'](${q}, this);\n`);for(h=0;h<e;++h)k+=`var arg${h}Wired = argType${h}['toWireType'](${q}, arg${h});\n`,t.push(`argType${h}`);k+=(c||f?"var rv = ":"")+`invoker(${l});\n`;if(m)k+="runDestructors(destructors);\n";else for(h=g?1:2;h<a.length;++h)f=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==a[h].Z&&(k+=`${f}_dtor(${f});\n`,
t.push(`${f}_dtor`));c&&(k+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [x,u]=[t,k+"}\n"];a=(new Function(...x,u))(...d);return Ua(b,a)}
var ub=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},vb=[],X=[0,1,,1,null,1,!0,1,!1,1],wb=b=>{9<b&&0===--X[b+1]&&(X[b]=void 0,vb.push(b))},Y=b=>{if(!b)throw new Q(`Cannot use deleted val. handle = ${b}`);return X[b]},S=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=vb.pop()||X.length;X[a]=b;X[a+1]=1;return a}},xb={name:"emscripten::val",fromWireType:b=>{var a=Y(b);wb(b);return a},toWireType:(b,a)=>S(a),aa:8,readValueFromPointer:K,
Z:null},yb=(b,a)=>{switch(a){case 4:return function(c){return this.fromWireType(ma[c>>2])};case 8:return function(c){return this.fromWireType(na[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);}},zb=(b,a,c)=>{var d=C;if(0<c){c=a+c-1;for(var e=0;e<b.length;++e){var f=b.codePointAt(e);if(127>=f){if(a>=c)break;d[a++]=f}else if(2047>=f){if(a+1>=c)break;d[a++]=192|f>>6;d[a++]=128|f&63}else if(65535>=f){if(a+2>=c)break;d[a++]=224|f>>12;d[a++]=128|f>>6&63;d[a++]=128|f&63}else{if(a+
3>=c)break;d[a++]=240|f>>18;d[a++]=128|f>>12&63;d[a++]=128|f>>6&63;d[a++]=128|f&63;e++}}d[a]=0}},Ab=b=>{for(var a=0,c=0;c<b.length;++c){var d=b.charCodeAt(c);127>=d?a++:2047>=d?a+=2:55296<=d&&57343>=d?(a+=4,++c):a+=3}return a},Bb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Cb=(b,a)=>{b>>=1;a=b+a/2;for(var c=b;!(c>=a)&&D[c];)++c;if(16<c-b&&Bb)return Bb.decode(D.subarray(b,c));for(c="";!(b>=a);++b){var d=D[b];if(0==d)break;c+=String.fromCharCode(d)}return c},Db=(b,a,c)=>{c??=
2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)la[a>>1]=b.charCodeAt(e),a+=2;la[a>>1]=0;return a-d},Eb=b=>2*b.length,Fb=(b,a)=>{for(var c="",d=0;!(d>=a/4);d++){var e=F[b+4*d>>2];if(!e)break;c+=String.fromCodePoint(e)}return c},Gb=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var f=b.codePointAt(e);65535<f&&e++;F[a>>2]=f;a+=4;if(a+4>c)break}F[a>>2]=0;return a-d},Hb=b=>{for(var a=0,c=0;c<b.length;++c)65535<b.codePointAt(c)&&
c++,a+=4;return a},Ib=(b,a)=>{var c=M[b];if(void 0===c)throw b=`${a} has unknown type ${ob(b)}`,new Q(b);return c},Jb=(b,a,c)=>{var d=[];b=b.toWireType(d,c);d.length&&(G[a>>2]=S(d));return b},Kb=[],Lb={},Mb=b=>{var a=Lb[b];return void 0===a?P(b):a},Nb=b=>{var a=Kb.length;Kb.push(b);return a},Ob=(b,a)=>{for(var c=Array(b),d=0;d<b;++d)c[d]=Ib(G[a+4*d>>2],`parameter ${d}`);return c},Pb=[null,[],[]],Tb=(b,a,c,d)=>{var e={string:k=>{var l=0;if(null!==k&&void 0!==k&&0!==k){l=Ab(k)+1;var q=Qb(l);zb(k,q,
l);l=q}return l},array:k=>{var l=Qb(k.length);ka.set(k,l);return l}};b=n["_"+b];var f=[],h=0;if(d)for(var g=0;g<d.length;g++){var m=e[c[g]];m?(0===h&&(h=Rb()),f[g]=m(d[g])):f[g]=d[g]}c=b(...f);return c=function(k){0!==h&&Sb(h);return"string"===a?k?J(C,k):"":"boolean"===a?!!k:k}(c)};
(()=>{let b=Ta.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof Ta&&c instanceof Ta))return!1;var d=this.S.V.T,e=this.S.U;c.S=c.S;var f=c.S.V.T;for(c=c.S.U;d.Y;)e=d.ia(e),d=d.Y;for(;f.Y;)c=f.ia(c),f=f.Y;return d===f&&e===c},clone:function(){this.S.U||Pa(this);if(this.S.ha)return this.S.count.value+=1,this;var c=R,d=Object,e=d.create,f=Object.getPrototypeOf(this),h=this.S;c=c(e.call(d,f,{S:{value:{count:h.count,ga:h.ga,ha:h.ha,U:h.U,V:h.V,X:h.X,$:h.$}}}));c.S.count.value+=1;c.S.ga=
!1;return c},["delete"](){this.S.U||Pa(this);if(this.S.ga&&!this.S.ha)throw new Q("Object already scheduled for deletion");Ra(this);var c=this.S;--c.count.value;0===c.count.value&&(c.X?c.$.ba(c.X):c.V.T.ba(c.U));this.S.ha||(this.S.X=void 0,this.S.U=void 0)},isDeleted:function(){return!this.S.U},deleteLater:function(){this.S.U||Pa(this);if(this.S.ga&&!this.S.ha)throw new Q("Object already scheduled for deletion");Sa.push(this);this.S.ga=!0;return this}});const a=Symbol.dispose;a&&(b[a]=b["delete"])})();
Object.assign(ib.prototype,{va(b){this.qa&&(b=this.qa(b));return b},oa(b){this.ba?.(b)},aa:8,readValueFromPointer:K,fromWireType:function(b){function a(){return this.ka?hb(this.T.ea,{V:this.Ba,U:c,$:this,X:b}):hb(this.T.ea,{V:this,U:b})}var c=this.va(b);if(!c)return this.oa(b),null;var d=gb(this.T,c);if(void 0!==d){if(0===d.S.count.value)return d.S.U=c,d.S.X=b,d.clone();d=d.clone();this.oa(b);return d}d=this.T.ua(c);d=Va[d];if(!d)return a.call(this);d=this.ja?d.ra:d.pointerType;var e=eb(c,this.T,
d.T);return null===e?a.call(this):this.ka?hb(d.T.ea,{V:d,U:e,$:this,X:b}):hb(d.T.ea,{V:d,U:e})}});n.noExitRuntime&&(Ca=n.noExitRuntime);n.print&&(fa=n.print);n.printErr&&(w=n.printErr);n.wasmBinary&&(A=n.wasmBinary);n.ccall=Tb;n.cwrap=(b,a,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==a&&e&&!d?n["_"+b]:(...f)=>Tb(b,a,c,f,d)};
var Ub,Vb,nb,W,Sb,Qb,Rb,Wb={B:(b,a,c,d)=>sa(`Assertion failed: ${b?J(C,b):""}, at: `+[a?a?J(C,a):"":"unknown filename",c,d?d?J(C,d):"":"unknown function"]),v:(b,a,c)=>{var d=new Fa(b);G[d.U+16>>2]=0;G[d.U+4>>2]=a;G[d.U+8>>2]=c;Ga=b;Ha++;throw Ga;},C:()=>sa(""),y:b=>{var a=Ia[b];delete Ia[b];var c=a.ma,d=a.ba,e=a.pa,f=e.map(h=>h.ya).concat(e.map(h=>h.Fa));O([b],f,h=>{var g={};e.forEach((m,k)=>{var l=h[k],q=m.wa,t=m.xa,x=h[k+e.length],u=m.Ea,z=m.Ga;g[m.ta]={read:E=>l.fromWireType(q(t,E)),write:(E,U)=>
{var y=[];u(z,E,x.toWireType(y,U));Ja(y)},optional:h[k].optional}});return[{name:a.name,fromWireType:m=>{var k={},l;for(l in g)k[l]=g[l].read(m);d(m);return k},toWireType:(m,k)=>{for(var l in g)if(!(l in k||g[l].optional))throw new TypeError(`Missing field: "${l}"`);var q=c();for(l in g)g[l].write(q,k[l]);null!==m&&m.push(d,q);return q},aa:8,readValueFromPointer:K,Z:d}]})},u:(b,a,c,d,e)=>{a=P(a);d=0n===d;let f=h=>h;if(d){const h=8*c;f=g=>BigInt.asUintN(h,g);e=f(e)}N(b,{name:a,fromWireType:f,toWireType:(h,
g)=>{"number"==typeof g&&(g=BigInt(g));return g},aa:8,readValueFromPointer:Oa(a,c,!d),Z:null})},G:(b,a,c,d)=>{a=P(a);N(b,{name:a,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},aa:8,readValueFromPointer:function(e){return this.fromWireType(C[e])},Z:null})},x:(b,a,c,d,e,f,h,g,m,k,l,q,t)=>{l=P(l);f=T(e,f);g&&=T(h,g);k&&=T(m,k);t=T(q,t);var x=Ya(l);Xa(x,function(){pb(`Cannot construct ${l} due to unbound types`,[d])});O([b,a,c],d?[d]:[],u=>{u=u[0];if(d){var z=u.T;var E=z.ea}else E=
Ta.prototype;u=Ua(l,function(...Ea){if(Object.getPrototypeOf(this)!==U)throw new Q(`Use 'new' to construct ${l}`);if(void 0===y.da)throw new Q(`${l} has no accessible constructor`);var sb=y.da[Ea.length];if(void 0===sb)throw new Q(`Tried to invoke ctor of ${l} with invalid number of parameters (${Ea.length}) - expected (${Object.keys(y.da).toString()}) parameters instead!`);return sb.apply(this,Ea)});var U=Object.create(E,{constructor:{value:u}});u.prototype=U;var y=new Za(l,u,U,t,z,f,g,k);if(y.Y){var V;
(V=y.Y).na??(V.na=[]);y.Y.na.push(y)}z=new ib(l,y,!0,!1,!1);V=new ib(l+"*",y,!1,!1,!1);E=new ib(l+" const*",y,!1,!0,!1);Va[b]={pointerType:V,ra:E};jb(x,u);return[z,V,E]})},w:(b,a,c,d,e,f)=>{var h=qb(a,c);e=T(d,e);O([],[b],g=>{g=g[0];var m=`constructor ${g.name}`;void 0===g.T.da&&(g.T.da=[]);if(void 0!==g.T.da[a-1])throw new Q(`Cannot register multiple constructors with identical number of parameters (${a-1}) for class '${g.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
g.T.da[a-1]=()=>{pb(`Cannot construct ${g.name} due to unbound types`,h)};O([],h,k=>{k.splice(1,0,null);g.T.da[a-1]=tb(m,k,null,e,f);return[]});return[]})},h:(b,a,c,d,e,f,h,g,m)=>{var k=qb(c,d);a=P(a);a=ub(a);f=T(e,f);O([],[b],l=>{function q(){pb(`Cannot call ${t} due to unbound types`,k)}l=l[0];var t=`${l.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);g&&l.T.Ca.push(a);var x=l.T.ea,u=x[a];void 0===u||void 0===u.W&&u.className!==l.name&&u.fa===c-2?(q.fa=c-2,q.className=l.name,x[a]=q):
(Wa(x,a,t),x[a].W[c-2]=q);O([],k,z=>{z=tb(t,z,l,f,h,m);void 0===x[a].W?(z.fa=c-2,x[a]=z):x[a].W[c-2]=z;return[]});return[]})},E:b=>N(b,xb),t:(b,a,c)=>{a=P(a);N(b,{name:a,fromWireType:d=>d,toWireType:(d,e)=>e,aa:8,readValueFromPointer:yb(a,c),Z:null})},p:(b,a,c,d,e,f,h)=>{var g=qb(a,c);b=P(b);b=ub(b);e=T(d,e);Xa(b,function(){pb(`Cannot call ${b} due to unbound types`,g)},a-1);O([],g,m=>{m=[m[0],null].concat(m.slice(1));jb(b,tb(b,m,null,e,f,h),a-1);return[]})},k:(b,a,c,d,e)=>{a=P(a);let f=g=>g;if(0===
d){var h=32-8*c;f=g=>g<<h>>>h;e=f(e)}N(b,{name:a,fromWireType:f,toWireType:(g,m)=>m,aa:8,readValueFromPointer:Oa(a,c,0!==d),Z:null})},c:(b,a,c)=>{function d(f){return new e(ka.buffer,G[f+4>>2],G[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=P(c);N(b,{name:c,fromWireType:d,aa:8,readValueFromPointer:d},{za:!0})},F:(b,a)=>{a=P(a);N(b,{name:a,fromWireType:function(c){for(var d=G[c>>2],e=c+4,f,h=e,g=0;g<=d;++g){var m=
e+g;if(g==d||0==C[m])h=h?J(C,h,m-h):"",void 0===f?f=h:(f+=String.fromCharCode(0),f+=h),h=m+1}W(c);return f},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new Q("Cannot pass non-string to std::string");var f=e?Ab(d):d.length;var h=Ub(4+f+1),g=h+4;G[h>>2]=f;e?zb(d,g,f+1):C.set(d,g);null!==c&&c.push(W,h);return h},aa:8,readValueFromPointer:K,Z(c){W(c)}})},q:(b,a,c)=>{c=P(c);if(2===a){var d=
Cb;var e=Db;var f=Eb;var h=g=>D[g>>1]}else 4===a&&(d=Fb,e=Gb,f=Hb,h=g=>G[g>>2]);N(b,{name:c,fromWireType:g=>{for(var m=G[g>>2],k,l=g+4,q=0;q<=m;++q){var t=g+4+q*a;if(q==m||0==h(t))l=d(l,t-l),void 0===k?k=l:(k+=String.fromCharCode(0),k+=l),l=t+a}W(g);return k},toWireType:(g,m)=>{if("string"!=typeof m)throw new Q(`Cannot pass non-string to C++ string type ${c}`);var k=f(m),l=Ub(4+k+a);G[l>>2]=k/a;e(m,l+4,k+a);null!==g&&g.push(W,l);return l},aa:8,readValueFromPointer:K,Z(g){W(g)}})},z:(b,a,c,d,e,f)=>
{Ia[b]={name:P(a),ma:T(c,d),ba:T(e,f),pa:[]}},o:(b,a,c,d,e,f,h,g,m,k)=>{Ia[b].pa.push({ta:P(a),ya:c,wa:T(d,e),xa:f,Fa:h,Ea:T(g,m),Ga:k})},H:(b,a)=>{a=P(a);N(b,{Aa:!0,name:a,aa:0,fromWireType:()=>{},toWireType:()=>{}})},n:(b,a,c)=>{b=Y(b);a=Ib(a,"emval::as");return Jb(a,c,b)},l:(b,a,c,d)=>{b=Kb[b];a=Y(a);return b(null,a,c,d)},r:(b,a,c,d,e)=>{b=Kb[b];a=Y(a);c=Mb(c);return b(a,a[c],d,e)},a:wb,m:b=>{if(0===b)return S(globalThis);b=Mb(b);return S(globalThis[b])},g:(b,a,c)=>{a=Ob(b,a);var d=a.shift();b--;
var e="return function (obj, func, destructorsRef, args) {\n",f=0,h=[];0===c&&h.push("obj");for(var g=["retType"],m=[d],k=0;k<b;++k)h.push(`arg${k}`),g.push(`argType${k}`),m.push(a[k]),e+=`  var arg${k} = argType${k}.readValueFromPointer(args${f?"+"+f:""});\n`,f+=a[k].aa;e+=`  var rv = ${1===c?"new func":"func.call"}(${h.join(", ")});\n`;d.Aa||(g.push("emval_returnValue"),m.push(Jb),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");b=(new Function(...g,e+"};\n"))(...m);c=`methodCaller<(${a.map(l=>
l.name).join(", ")}) => ${d.name}>`;return Nb(Ua(c,b))},j:(b,a)=>{b=Y(b);a=Y(a);return S(b[a])},f:b=>{9<b&&(X[b+1]+=1)},e:b=>S(Mb(b)),A:()=>S({}),b:b=>{var a=Y(b);Ja(a);wb(b)},i:(b,a,c)=>{b=Y(b);a=Y(a);c=Y(c);b[a]=c},d:(b,a)=>{b=Ib(b,"_emval_take_value");b=b.readValueFromPointer(a);return S(b)},D:b=>{var a=C.length;b>>>=0;if(2147483648<b)return!1;for(var c=1;4>=c;c*=2){var d=a*(1+.2/c);d=Math.min(d,b+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(b,d)/65536))-B.buffer.byteLength+65535)/
65536|0;try{B.grow(d);ra();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},s:(b,a,c,d)=>{for(var e=0,f=0;f<c;f++){var h=G[a>>2],g=G[a+4>>2];a+=8;for(var m=0;m<g;m++){var k=b,l=C[h+m],q=Pb[k];0===l||10===l?((1===k?fa:w)(J(q)),q.length=0):q.push(l)}e+=g}G[d>>2]=e;return 0}},Z=await (async function(){function b(c){Z=c.exports;B=Z.I;ra();lb=Z.L;c=Z;Ub=c.K;n._main=Vb=c.M;nb=c.N;W=c.O;Sb=c.P;Qb=c.Q;Rb=c.R;H--;n.monitorRunDependencies?.(H);0==H&&I&&(c=I,I=null,c());return Z}H++;n.monitorRunDependencies?.(H);
var a={a:Wb};if(n.instantiateWasm)return new Promise(c=>{n.instantiateWasm(a,(d,e)=>{c(b(d,e))})});ta??=n.locateFile?n.locateFile("module.wasm",p):p+"module.wasm";return b((await wa(a)).instance)}());
function Xb(){function b(){n.calledRun=!0;if(!ha){qa=!0;Z.J();ia?.(n);n.onRuntimeInitialized?.();if(!n.noInitialRun){var a=Vb;try{var c=a(0,0);Ca||(n.onExit?.(c),ha=!0);da(c,new xa(c))}catch(d){d instanceof xa||"unwind"==d||da(1,d)}}if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;)a=n.postRun.shift(),za.push(a);ya(za)}}if(0<H)I=Xb;else{if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)Ba();ya(Aa);0<H?I=Xb:n.setStatus?(n.setStatus("Running..."),
setTimeout(()=>{setTimeout(()=>n.setStatus(""),1);b()},1)):b()}}if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.shift()();Xb();qa?moduleRtn=n:moduleRtn=new Promise((b,a)=>{ia=b;ja=a});


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = createWASMModule;
  // This default export looks redundant, but it allows TS to import this
  // commonjs style module.
  module.exports.default = createWASMModule;
} else if (typeof define === 'function' && define['amd'])
  define([], () => createWASMModule);
