var createWASMModule=(()=>{var _scriptName=typeof document!="undefined"?document.currentScript?.src:undefined;return async function(moduleArg={}){var moduleRtn;var l=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=(b,a)=>{throw a;};"undefined"!=typeof __filename?_scriptName=__filename:ba&&(_scriptName=self.location.href);var p="",ea,r;
if(ca){var fs=require("fs");p=__dirname+"/";r=b=>{b=t(b)?new URL(b):b;return fs.readFileSync(b)};ea=async b=>{b=t(b)?new URL(b):b;return fs.readFileSync(b,void 0)};process.argv.slice(2);da=(b,a)=>{process.exitCode=b;throw a;}}else if(aa||ba){try{p=(new URL(".",_scriptName)).href}catch{}ba&&(r=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)});ea=async b=>{if(t(b))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",
b,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var a=await fetch(b,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var fa=console.log.bind(console),w=console.error.bind(console),A,ha=!1,t=b=>b.startsWith("file://"),ia,ja,B,D,E,ka,F,la,G,ma,na,oa,pa,qa=!1;
function ra(){var b=B.buffer;D=new Int8Array(b);ka=new Int16Array(b);E=new Uint8Array(b);F=new Uint16Array(b);la=new Int32Array(b);G=new Uint32Array(b);ma=new Float32Array(b);na=new Float64Array(b);oa=new BigInt64Array(b);pa=new BigUint64Array(b)}var H=0,I=null;function sa(b){l.onAbort?.(b);b="Aborted("+b+")";w(b);ha=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ja?.(b);throw b;}var ta;
async function ua(b){if(!A)try{var a=await ea(b);return new Uint8Array(a)}catch{}if(b==ta&&A)b=new Uint8Array(A);else if(r)b=r(b);else throw"both async and sync fetching of the wasm failed";return b}async function va(b,a){try{var c=await ua(b);return await WebAssembly.instantiate(c,a)}catch(d){w(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}
async function wa(b){var a=ta;if(!A&&!t(a)&&!ca)try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){w(`wasm streaming compile failed: ${d}`),w("falling back to ArrayBuffer instantiation")}return va(a,b)}class xa{name="ExitStatus";constructor(b){this.message=`Program terminated with exit(${b})`;this.status=b}}
var ya=b=>{for(;0<b.length;)b.shift()(l)},za=[],Aa=[],Ba=()=>{var b=l.preRun.shift();Aa.push(b)},Ca=!0,Ea="undefined"!=typeof TextDecoder?new TextDecoder:void 0,Fa=(b,a,c,d)=>{c=a+c;if(d)return c;for(;b[a]&&!(a>=c);)++a;return a},J=(b,a=0,c,d)=>{c=Fa(b,a,c,d);if(16<c-a&&b.buffer&&Ea)return Ea.decode(b.subarray(a,c));for(d="";a<c;){var e=b[a++];if(e&128){var f=b[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=b[a++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|b[a++]&
63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d};class Ga{constructor(b){this.T=b-24}}var Ha=0,Ia=0,Ja={},Ka=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function K(b){return this.V(G[b>>2])}
var L={},M={},La={},Ma=class extends Error{constructor(b){super(b);this.name="InternalError"}},O=(b,a,c)=>{function d(g){g=c(g);if(g.length!==b.length)throw new Ma("Mismatched type converter count");for(var n=0;n<b.length;++n)N(b[n],g[n])}b.forEach(g=>La[g]=a);var e=Array(a.length),f=[],h=0;a.forEach((g,n)=>{M.hasOwnProperty(g)?e[n]=M[g]:(f.push(g),L.hasOwnProperty(g)||(L[g]=[]),L[g].push(()=>{e[n]=M[g];++h;h===f.length&&d(e)}))});0===f.length&&d(e)},P=b=>{for(var a="";;){var c=E[b++];if(!c)return a;
a+=String.fromCharCode(c)}},Q=class extends Error{constructor(b){super(b);this.name="BindingError"}},Na=b=>{throw new Q(b);};function Oa(b,a,c={}){var d=a.name;if(!b)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(M.hasOwnProperty(b)){if(c.Ba)return;throw new Q(`Cannot register type '${d}' twice`);}M[b]=a;delete La[b];L.hasOwnProperty(b)&&(a=L[b],delete L[b],a.forEach(e=>e()))}function N(b,a,c={}){return Oa(b,a,c)}
var Pa=(b,a,c)=>{switch(a){case 1:return c?d=>D[d]:d=>E[d];case 2:return c?d=>ka[d>>1]:d=>F[d>>1];case 4:return c?d=>la[d>>2]:d=>G[d>>2];case 8:return c?d=>oa[d>>3]:d=>pa[d>>3];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Qa=b=>{throw new Q(b.R.U.S.name+" instance already deleted");},Ra=!1,Sa=()=>{},R=b=>{if("undefined"===typeof FinalizationRegistry)return R=a=>a,b;Ra=new FinalizationRegistry(a=>{a=a.R;--a.count.value;0===a.count.value&&(a.X?a.aa.ba(a.X):a.U.S.ba(a.T))});R=
a=>{var c=a.R;c.X&&Ra.register(a,{R:c},a);return a};Sa=a=>{Ra.unregister(a)};return R(b)},Ta=[];function Ua(){}
var Va=(b,a)=>Object.defineProperty(a,"name",{value:b}),Wa={},Xa=(b,a,c)=>{if(void 0===b[a].W){var d=b[a];b[a]=function(...e){if(!b[a].W.hasOwnProperty(e.length))throw new Q(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].W})!`);return b[a].W[e.length].apply(this,e)};b[a].W=[];b[a].W[d.ga]=d}},Ya=(b,a,c)=>{if(l.hasOwnProperty(b)){if(void 0===c||void 0!==l[b].W&&void 0!==l[b].W[c])throw new Q(`Cannot register public name '${b}' twice`);Xa(l,b,b);if(l[b].W.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
l[b].W[c]=a}else l[b]=a,l[b].ga=c},Za=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function $a(b,a,c,d,e,f,h,g){this.name=b;this.constructor=a;this.fa=c;this.ba=d;this.Z=e;this.wa=f;this.ja=h;this.ua=g;this.Da=[]}
var ab=(b,a,c)=>{for(;a!==c;){if(!a.ja)throw new Q(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.ja(b);a=a.Z}return b},bb=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b};
function cb(b,a){if(null===a){if(this.ma)throw new Q(`null is not a valid ${this.name}`);return 0}if(!a.R)throw new Q(`Cannot pass "${bb(a)}" as a ${this.name}`);if(!a.R.T)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);return ab(a.R.T,a.R.U.S,this.S)}
function db(b,a){if(null===a){if(this.ma)throw new Q(`null is not a valid ${this.name}`);if(this.la){var c=this.na();null!==b&&b.push(this.ba,c);return c}return 0}if(!a||!a.R)throw new Q(`Cannot pass "${bb(a)}" as a ${this.name}`);if(!a.R.T)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ka&&a.R.U.ka)throw new Q(`Cannot convert argument of type ${a.R.aa?a.R.aa.name:a.R.U.name} to parameter type ${this.name}`);c=ab(a.R.T,a.R.U.S,this.S);if(this.la){if(void 0===
a.R.X)throw new Q("Passing raw pointer to smart pointer is illegal");switch(this.Ia){case 0:if(a.R.aa===this)c=a.R.X;else throw new Q(`Cannot convert argument of type ${a.R.aa?a.R.aa.name:a.R.U.name} to parameter type ${this.name}`);break;case 1:c=a.R.X;break;case 2:if(a.R.aa===this)c=a.R.X;else{var d=a.clone();c=this.Ea(c,S(()=>d["delete"]()));null!==b&&b.push(this.ba,c)}break;default:throw new Q("Unsupporting sharing policy");}}return c}
function eb(b,a){if(null===a){if(this.ma)throw new Q(`null is not a valid ${this.name}`);return 0}if(!a.R)throw new Q(`Cannot pass "${bb(a)}" as a ${this.name}`);if(!a.R.T)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.R.U.ka)throw new Q(`Cannot convert argument of type ${a.R.U.name} to parameter type ${this.name}`);return ab(a.R.T,a.R.U.S,this.S)}
var fb=(b,a,c)=>{if(a===c)return b;if(void 0===c.Z)return null;b=fb(b,a,c.Z);return null===b?null:c.ua(b)},gb={},hb=(b,a)=>{if(void 0===a)throw new Q("ptr should not be undefined");for(;b.Z;)a=b.ja(a),b=b.Z;return gb[a]},ib=(b,a)=>{if(!a.U||!a.T)throw new Ma("makeClassHandle requires ptr and ptrType");if(!!a.aa!==!!a.X)throw new Ma("Both smartPtrType and smartPtr must be specified");a.count={value:1};return R(Object.create(b,{R:{value:a,writable:!0}}))};
function jb(b,a,c,d,e,f,h,g,n,m,k){this.name=b;this.S=a;this.ma=c;this.ka=d;this.la=e;this.Ca=f;this.Ia=h;this.sa=g;this.na=n;this.Ea=m;this.ba=k;e||void 0!==a.Z?this.Y=db:(this.Y=d?cb:eb,this.$=null)}
var kb=(b,a,c)=>{if(!l.hasOwnProperty(b))throw new Ma("Replacing nonexistent public symbol");void 0!==l[b].W&&void 0!==c?l[b].W[c]=a:(l[b]=a,l[b].ga=c)},lb=[],mb,V=(b,a)=>{b=P(b);var c;(c=lb[a])||(lb[a]=c=mb.get(a));if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${b}: ${a}`);return c};class nb extends Error{}
var pb=b=>{b=ob(b);var a=P(b);W(b);return a},qb=(b,a)=>{function c(f){e[f]||M[f]||(La[f]?La[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};a.forEach(c);throw new nb(`${b}: `+d.map(pb).join([", "]));},rb=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(G[a+4*d>>2]);return c};function tb(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].$)return!0;return!1}
function ub(b,a,c,d,e,f){var h=a.length;if(2>h)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==a[1]&&null!==c,n=tb(a);c=!a[0].ra;var m=a[0],k=a[1];d=[b,Na,d,e,Ka,m.V.bind(m),k?.Y.bind(k)];for(e=2;e<h;++e)m=a[e],d.push(m.Y.bind(m));if(!n)for(e=g?1:2;e<a.length;++e)null!==a[e].$&&d.push(a[e].$);n=tb(a);e=a.length-2;k=[];m=["fn"];g&&m.push("thisWired");for(h=0;h<e;++h)k.push(`arg${h}`),m.push(`arg${h}Wired`);k=k.join(",");m=m.join(",");k=`return function (${k}) {\n`;
n&&(k+="var destructors = [];\n");var q=n?"destructors":"null",x="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");g&&(k+=`var thisWired = toClassParamWire(${q}, this);\n`);for(h=0;h<e;++h){var u=`toArg${h}Wire`;k+=`var arg${h}Wired = ${u}(${q}, arg${h});\n`;x.push(u)}k+=(c||f?"var rv = ":"")+`invoker(${m});\n`;if(n)k+="runDestructors(destructors);\n";else for(h=g?1:2;h<a.length;++h)f=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==a[h].$&&(k+=`${f}_dtor(${f});\n`,
x.push(`${f}_dtor`));c&&(k+="var ret = fromRetWire(rv);\nreturn ret;\n");a=(new Function(x,k+"}\n"))(...d);return Va(b,a)}
var vb=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},wb=[],X=[0,1,,1,null,1,!0,1,!1,1],xb=b=>{9<b&&0===--X[b+1]&&(X[b]=void 0,wb.push(b))},Y=b=>{if(!b)throw new Q(`Cannot use deleted val. handle = ${b}`);return X[b]},S=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=wb.pop()||X.length;X[a]=b;X[a+1]=1;return a}},yb={name:"emscripten::val",V:b=>{var a=Y(b);xb(b);return a},Y:(b,a)=>S(a),da:K,$:null},zb=(b,a)=>{switch(a){case 4:return function(c){return this.V(ma[c>>
2])};case 8:return function(c){return this.V(na[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);}},Ab=Object.assign({optional:!0},yb),Bb=(b,a,c)=>{var d=E;if(0<c){c=a+c-1;for(var e=0;e<b.length;++e){var f=b.codePointAt(e);if(127>=f){if(a>=c)break;d[a++]=f}else if(2047>=f){if(a+1>=c)break;d[a++]=192|f>>6;d[a++]=128|f&63}else if(65535>=f){if(a+2>=c)break;d[a++]=224|f>>12;d[a++]=128|f>>6&63;d[a++]=128|f&63}else{if(a+3>=c)break;d[a++]=240|f>>18;d[a++]=128|f>>12&63;d[a++]=128|f>>
6&63;d[a++]=128|f&63;e++}}d[a]=0}},Cb=b=>{for(var a=0,c=0;c<b.length;++c){var d=b.charCodeAt(c);127>=d?a++:2047>=d?a+=2:55296<=d&&57343>=d?(a+=4,++c):a+=3}return a},Db="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Eb=(b,a,c)=>{b>>=1;a=Fa(F,b,a/2,c);if(16<a-b&&Db)return Db.decode(F.subarray(b,a));for(c="";b<a;++b)c+=String.fromCharCode(F[b]);return c},Fb=(b,a,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)ka[a>>1]=b.charCodeAt(e),
a+=2;ka[a>>1]=0;return a-d},Gb=b=>2*b.length,Hb=(b,a,c)=>{var d="";b>>=2;for(var e=0;!(e>=a/4);e++){var f=G[b+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Ib=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var f=b.codePointAt(e);65535<f&&e++;la[a>>2]=f;a+=4;if(a+4>c)break}la[a>>2]=0;return a-d},Jb=b=>{for(var a=0,c=0;c<b.length;++c)65535<b.codePointAt(c)&&c++,a+=4;return a},Kb=[],Lb=b=>{var a=Kb.length;Kb.push(b);return a},Mb=(b,a)=>{for(var c=Array(b),
d=0;d<b;++d){var e=d,f=G[a+4*d>>2],h=M[f];if(void 0===h)throw b=`${`parameter ${d}`} has unknown type ${pb(f)}`,new Q(b);c[e]=h}return c},Nb=(b,a,c)=>{var d=[];b=b(d,c);d.length&&(G[a>>2]=S(d));return b},Ob={},Pb=b=>{var a=Ob[b];return void 0===a?P(b):a},Qb=[null,[],[]],Ub=(b,a,c,d)=>{var e={string:m=>{var k=0;if(null!==m&&void 0!==m&&0!==m){k=Cb(m)+1;var q=Rb(k);Bb(m,q,k);k=q}return k},array:m=>{var k=Rb(m.length);D.set(m,k);return k}};b=l["_"+b];var f=[],h=0;if(d)for(var g=0;g<d.length;g++){var n=
e[c[g]];n?(0===h&&(h=Sb()),f[g]=n(d[g])):f[g]=d[g]}c=b(...f);return c=function(m){0!==h&&Tb(h);return"string"===a?m?J(E,m):"":"boolean"===a?!!m:m}(c)};
(()=>{let b=Ua.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof Ua&&c instanceof Ua))return!1;var d=this.R.U.S,e=this.R.T;c.R=c.R;var f=c.R.U.S;for(c=c.R.T;d.Z;)e=d.ja(e),d=d.Z;for(;f.Z;)c=f.ja(c),f=f.Z;return d===f&&e===c},clone:function(){this.R.T||Qa(this);if(this.R.ia)return this.R.count.value+=1,this;var c=R,d=Object,e=d.create,f=Object.getPrototypeOf(this),h=this.R;c=c(e.call(d,f,{R:{value:{count:h.count,ha:h.ha,ia:h.ia,T:h.T,U:h.U,X:h.X,aa:h.aa}}}));c.R.count.value+=1;
c.R.ha=!1;return c},["delete"](){this.R.T||Qa(this);if(this.R.ha&&!this.R.ia)throw new Q("Object already scheduled for deletion");Sa(this);var c=this.R;--c.count.value;0===c.count.value&&(c.X?c.aa.ba(c.X):c.U.S.ba(c.T));this.R.ia||(this.R.X=void 0,this.R.T=void 0)},isDeleted:function(){return!this.R.T},deleteLater:function(){this.R.T||Qa(this);if(this.R.ha&&!this.R.ia)throw new Q("Object already scheduled for deletion");Ta.push(this);this.R.ha=!0;return this}});const a=Symbol.dispose;a&&(b[a]=b["delete"])})();
Object.assign(jb.prototype,{xa(b){this.sa&&(b=this.sa(b));return b},pa(b){this.ba?.(b)},da:K,V:function(b){function a(){return this.la?ib(this.S.fa,{U:this.Ca,T:c,aa:this,X:b}):ib(this.S.fa,{U:this,T:b})}var c=this.xa(b);if(!c)return this.pa(b),null;var d=hb(this.S,c);if(void 0!==d){if(0===d.R.count.value)return d.R.T=c,d.R.X=b,d.clone();d=d.clone();this.pa(b);return d}d=this.S.wa(c);d=Wa[d];if(!d)return a.call(this);d=this.ka?d.ta:d.pointerType;var e=fb(c,this.S,d.S);return null===e?a.call(this):
this.la?ib(d.S.fa,{U:d,T:e,aa:this,X:b}):ib(d.S.fa,{U:d,T:e})}});l.noExitRuntime&&(Ca=l.noExitRuntime);l.print&&(fa=l.print);l.printErr&&(w=l.printErr);l.wasmBinary&&(A=l.wasmBinary);l.ccall=Ub;l.cwrap=(b,a,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==a&&e&&!d?l["_"+b]:(...f)=>Ub(b,a,c,f,d)};
var Vb,Wb,ob,W,Tb,Rb,Sb,Xb={z:(b,a,c,d)=>sa(`Assertion failed: ${b?J(E,b):""}, at: `+[a?a?J(E,a):"":"unknown filename",c,d?d?J(E,d):"":"unknown function"]),p:(b,a,c)=>{var d=new Ga(b);G[d.T+16>>2]=0;G[d.T+4>>2]=a;G[d.T+8>>2]=c;Ha=b;Ia++;throw Ha;},A:()=>sa(""),x:b=>{var a=Ja[b];delete Ja[b];var c=a.na,d=a.ba,e=a.qa,f=e.map(h=>h.Aa).concat(e.map(h=>h.Ga));O([b],f,h=>{var g={};e.forEach((n,m)=>{var k=h[m],q=n.ya,x=n.za,u=h[m+e.length],v=n.Fa,z=n.Ha;g[n.va]={read:C=>k.V(q(x,C)),write:(C,T)=>{var y=[];
v(z,C,u.Y(y,T));Ka(y)},optional:h[m].optional}});return[{name:a.name,V:n=>{var m={},k;for(k in g)m[k]=g[k].read(n);d(n);return m},Y:(n,m)=>{for(var k in g)if(!(k in m||g[k].optional))throw new TypeError(`Missing field: "${k}"`);var q=c();for(k in g)g[k].write(q,m[k]);null!==n&&n.push(d,q);return q},da:K,$:d}]})},v:(b,a,c,d,e)=>{a=P(a);d=0n===d;let f=h=>h;if(d){const h=8*c;f=g=>BigInt.asUintN(h,g);e=f(e)}N(b,{name:a,V:f,Y:(h,g)=>{"number"==typeof g&&(g=BigInt(g));return g},da:Pa(a,c,!d),$:null})},
E:(b,a,c,d)=>{a=P(a);N(b,{name:a,V:function(e){return!!e},Y:function(e,f){return f?c:d},da:function(e){return this.V(E[e])},$:null})},r:(b,a,c,d,e,f,h,g,n,m,k,q,x)=>{k=P(k);f=V(e,f);g&&=V(h,g);m&&=V(n,m);x=V(q,x);var u=Za(k);Ya(u,function(){qb(`Cannot construct ${k} due to unbound types`,[d])});O([b,a,c],d?[d]:[],v=>{v=v[0];if(d){var z=v.S;var C=z.fa}else C=Ua.prototype;v=Va(k,function(...Da){if(Object.getPrototypeOf(this)!==T)throw new Q(`Use 'new' to construct ${k}`);if(void 0===y.ea)throw new Q(`${k} has no accessible constructor`);
var sb=y.ea[Da.length];if(void 0===sb)throw new Q(`Tried to invoke ctor of ${k} with invalid number of parameters (${Da.length}) - expected (${Object.keys(y.ea).toString()}) parameters instead!`);return sb.apply(this,Da)});var T=Object.create(C,{constructor:{value:v}});v.prototype=T;var y=new $a(k,v,T,x,z,f,g,m);if(y.Z){var U;(U=y.Z).oa??(U.oa=[]);y.Z.oa.push(y)}z=new jb(k,y,!0,!1,!1);U=new jb(k+"*",y,!1,!1,!1);C=new jb(k+" const*",y,!1,!0,!1);Wa[b]={pointerType:U,ta:C};kb(u,v);return[z,U,C]})},q:(b,
a,c,d,e,f)=>{var h=rb(a,c);e=V(d,e);O([],[b],g=>{g=g[0];var n=`constructor ${g.name}`;void 0===g.S.ea&&(g.S.ea=[]);if(void 0!==g.S.ea[a-1])throw new Q(`Cannot register multiple constructors with identical number of parameters (${a-1}) for class '${g.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);g.S.ea[a-1]=()=>{qb(`Cannot construct ${g.name} due to unbound types`,h)};O([],h,m=>{m.splice(1,0,null);g.S.ea[a-1]=ub(n,m,null,e,f);return[]});
return[]})},h:(b,a,c,d,e,f,h,g,n)=>{var m=rb(c,d);a=P(a);a=vb(a);f=V(e,f);O([],[b],k=>{function q(){qb(`Cannot call ${x} due to unbound types`,m)}k=k[0];var x=`${k.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);g&&k.S.Da.push(a);var u=k.S.fa,v=u[a];void 0===v||void 0===v.W&&v.className!==k.name&&v.ga===c-2?(q.ga=c-2,q.className=k.name,u[a]=q):(Xa(u,a,x),u[a].W[c-2]=q);O([],m,z=>{z=ub(x,z,k,f,h,n);void 0===u[a].W?(z.ga=c-2,u[a]=z):u[a].W[c-2]=z;return[]});return[]})},C:b=>N(b,yb),u:(b,
a,c)=>{a=P(a);N(b,{name:a,V:d=>d,Y:(d,e)=>e,da:zb(a,c),$:null})},n:(b,a,c,d,e,f,h)=>{var g=rb(a,c);b=P(b);b=vb(b);e=V(d,e);Ya(b,function(){qb(`Cannot call ${b} due to unbound types`,g)},a-1);O([],g,n=>{n=[n[0],null].concat(n.slice(1));kb(b,ub(b,n,null,e,f,h),a-1);return[]})},k:(b,a,c,d,e)=>{a=P(a);let f=g=>g;if(0===d){var h=32-8*c;f=g=>g<<h>>>h;e=f(e)}N(b,{name:a,V:f,Y:(g,n)=>n,da:Pa(a,c,0!==d),$:null})},i:(b,a,c)=>{function d(f){return new e(D.buffer,G[f+4>>2],G[f>>2])}var e=[Int8Array,Uint8Array,
Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=P(c);N(b,{name:c,V:d,da:d},{Ba:!0})},w:b=>{N(b,Ab)},D:(b,a)=>{a=P(a);N(b,{name:a,V(c){var d=(d=c+4)?J(E,d,G[c>>2],!0):"";W(c);return d},Y(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new Q("Cannot pass non-string to std::string");var f=e?Cb(d):d.length;var h=Vb(4+f+1),g=h+4;G[h>>2]=f;e?Bb(d,g,f+1):E.set(d,
g);null!==c&&c.push(W,h);return h},da:K,$(c){W(c)}})},o:(b,a,c)=>{c=P(c);if(2===a){var d=Eb;var e=Fb;var f=Gb}else d=Hb,e=Ib,f=Jb;N(b,{name:c,V:h=>{var g=d(h+4,G[h>>2]*a,!0);W(h);return g},Y:(h,g)=>{if("string"!=typeof g)throw new Q(`Cannot pass non-string to C++ string type ${c}`);var n=f(g),m=Vb(4+n+a);G[m>>2]=n/a;e(g,m+4,n+a);null!==h&&h.push(W,m);return m},da:K,$(h){W(h)}})},y:(b,a,c,d,e,f)=>{Ja[b]={name:P(a),na:V(c,d),ba:V(e,f),qa:[]}},l:(b,a,c,d,e,f,h,g,n,m)=>{Ja[b].qa.push({va:P(a),Aa:c,ya:V(d,
e),za:f,Ga:h,Fa:V(g,n),Ha:m})},F:(b,a)=>{a=P(a);N(b,{ra:!0,name:a,V:()=>{},Y:()=>{}})},d:(b,a,c)=>{var [d,...e]=Mb(b,a);a=d.Y.bind(d);var f=e.map(n=>n.da.bind(n));b--;var h={toValue:Y};b=f.map((n,m)=>{var k=`argFromPtr${m}`;h[k]=n;return`${k}(args${m?"+"+8*m:""})`});switch(c){case 0:var g="toValue(handle)";break;case 2:g="new (toValue(handle))";break;case 3:g="";break;case 1:h.getStringOrSymbol=Pb,g="toValue(handle)[getStringOrSymbol(methodName)]"}g+=`(${b})`;d.ra||(h.toReturnWire=a,h.emval_returnValue=
Nb,g=`return emval_returnValue(toReturnWire, destructorsRef, ${g})`);g=`return function (handle, methodName, destructorsRef, args) {\n  ${g}\n  }`;c=(new Function(Object.keys(h),g))(...Object.values(h));g=`methodCaller<(${e.map(n=>n.name)}) => ${d.name}>`;return Lb(Va(g,c))},a:xb,j:b=>{if(0===b)return S(globalThis);b=Pb(b);return S(globalThis[b])},g:(b,a)=>{b=Y(b);a=Y(a);return S(b[a])},e:b=>{9<b&&(X[b+1]+=1)},c:(b,a,c,d,e)=>Kb[b](a,c,d,e),f:b=>S(Pb(b)),s:()=>S({}),b:b=>{var a=Y(b);Ka(a);xb(b)},m:(b,
a,c)=>{b=Y(b);a=Y(a);c=Y(c);b[a]=c},B:b=>{var a=E.length;b>>>=0;if(2147483648<b)return!1;for(var c=1;4>=c;c*=2){var d=a*(1+.2/c);d=Math.min(d,b+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(b,d)/65536))-B.buffer.byteLength+65535)/65536|0;try{B.grow(d);ra();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},t:(b,a,c,d)=>{for(var e=0,f=0;f<c;f++){var h=G[a>>2],g=G[a+4>>2];a+=8;for(var n=0;n<g;n++){var m=b,k=E[h+n],q=Qb[m];0===k||10===k?((1===m?fa:w)(J(q)),q.length=0):q.push(k)}e+=
g}G[d>>2]=e;return 0}},Z=await (async function(){function b(c){Z=c.exports;B=Z.G;ra();mb=Z.I;c=Z;Vb=c.J;l._main=Wb=c.K;ob=c.L;W=c.M;Tb=c.N;Rb=c.O;Sb=c.P;H--;l.monitorRunDependencies?.(H);0==H&&I&&(c=I,I=null,c());return Z}H++;l.monitorRunDependencies?.(H);var a={a:Xb};if(l.instantiateWasm)return new Promise(c=>{l.instantiateWasm(a,(d,e)=>{c(b(d,e))})});ta??=l.locateFile?l.locateFile("module.wasm",p):p+"module.wasm";return b((await wa(a)).instance)}());
function Yb(){function b(){l.calledRun=!0;if(!ha){qa=!0;Z.H();ia?.(l);l.onRuntimeInitialized?.();if(!l.noInitialRun){var a=Wb;try{var c=a(0,0);Ca||(l.onExit?.(c),ha=!0);da(c,new xa(c))}catch(d){d instanceof xa||"unwind"==d||da(1,d)}}if(l.postRun)for("function"==typeof l.postRun&&(l.postRun=[l.postRun]);l.postRun.length;)a=l.postRun.shift(),za.push(a);ya(za)}}if(0<H)I=Yb;else{if(l.preRun)for("function"==typeof l.preRun&&(l.preRun=[l.preRun]);l.preRun.length;)Ba();ya(Aa);0<H?I=Yb:l.setStatus?(l.setStatus("Running..."),
setTimeout(()=>{setTimeout(()=>l.setStatus(""),1);b()},1)):b()}}if(l.preInit)for("function"==typeof l.preInit&&(l.preInit=[l.preInit]);0<l.preInit.length;)l.preInit.shift()();Yb();qa?moduleRtn=l:moduleRtn=new Promise((b,a)=>{ia=b;ja=a});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=createWASMModule;module.exports.default=createWASMModule}else if(typeof define==="function"&&define["amd"])define([],()=>createWASMModule);
