// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "primitives/Primitive3DGS.cuh"
#include "kernels/projection/ProjectionBwd_kernel.cuh"

template void projection_fused_bwd_kernel_wrapper<
    MipSplatting<0>,
    CameraModelType::EQUISOLID,
    CameraDistortionType::None
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    MipSplatting<0>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    MipSplatting<0>::ScreenBuffer v_splats_screen,
    // grad inputs
    MipSplatting<0>::WorldBuffer v_splats_world,
    float * v_viewmats, // [C, 4, 4] optional
    // SH VALUE-quant (active when sh_value_bits != 32). Mirrors fwd kernel
    // args; the bwd uses them to evaluate v_dir against the codec'd SH.
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_fused_bwd_kernel_wrapper<
    MipSplatting<0>,
    CameraModelType::EQUISOLID,
    CameraDistortionType::OpenCV
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    MipSplatting<0>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    MipSplatting<0>::ScreenBuffer v_splats_screen,
    // grad inputs
    MipSplatting<0>::WorldBuffer v_splats_world,
    float * v_viewmats, // [C, 4, 4] optional
    // SH VALUE-quant (active when sh_value_bits != 32). Mirrors fwd kernel
    // args; the bwd uses them to evaluate v_dir against the codec'd SH.
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_fused_bwd_kernel_wrapper<
    MipSplatting<0>,
    CameraModelType::EQUISOLID,
    CameraDistortionType::ThinPrism
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    MipSplatting<0>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    MipSplatting<0>::ScreenBuffer v_splats_screen,
    // grad inputs
    MipSplatting<0>::WorldBuffer v_splats_world,
    float * v_viewmats, // [C, 4, 4] optional
    // SH VALUE-quant (active when sh_value_bits != 32). Mirrors fwd kernel
    // args; the bwd uses them to evaluate v_dir against the codec'd SH.
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_fused_bwd_kernel_wrapper<
    MipSplatting<0>,
    CameraModelType::EQUIRECTANGULAR,
    CameraDistortionType::None
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    MipSplatting<0>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    MipSplatting<0>::ScreenBuffer v_splats_screen,
    // grad inputs
    MipSplatting<0>::WorldBuffer v_splats_world,
    float * v_viewmats, // [C, 4, 4] optional
    // SH VALUE-quant (active when sh_value_bits != 32). Mirrors fwd kernel
    // args; the bwd uses them to evaluate v_dir against the codec'd SH.
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGS<1>,
    CameraModelType::PINHOLE,
    CameraDistortionType::None
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<1>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGS<1>::ScreenBuffer v_splats_screen,
    // grad inputs
    Vanilla3DGS<1>::WorldBuffer v_splats_world,
    float * v_viewmats, // [C, 4, 4] optional
    // SH VALUE-quant (active when sh_value_bits != 32). Mirrors fwd kernel
    // args; the bwd uses them to evaluate v_dir against the codec'd SH.
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGS<1>,
    CameraModelType::PINHOLE,
    CameraDistortionType::OpenCV
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<1>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGS<1>::ScreenBuffer v_splats_screen,
    // grad inputs
    Vanilla3DGS<1>::WorldBuffer v_splats_world,
    float * v_viewmats, // [C, 4, 4] optional
    // SH VALUE-quant (active when sh_value_bits != 32). Mirrors fwd kernel
    // args; the bwd uses them to evaluate v_dir against the codec'd SH.
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGS<1>,
    CameraModelType::PINHOLE,
    CameraDistortionType::ThinPrism
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<1>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGS<1>::ScreenBuffer v_splats_screen,
    // grad inputs
    Vanilla3DGS<1>::WorldBuffer v_splats_world,
    float * v_viewmats, // [C, 4, 4] optional
    // SH VALUE-quant (active when sh_value_bits != 32). Mirrors fwd kernel
    // args; the bwd uses them to evaluate v_dir against the codec'd SH.
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGS<1>,
    CameraModelType::PINHOLE,
    CameraDistortionType::Rational
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<1>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGS<1>::ScreenBuffer v_splats_screen,
    // grad inputs
    Vanilla3DGS<1>::WorldBuffer v_splats_world,
    float * v_viewmats, // [C, 4, 4] optional
    // SH VALUE-quant (active when sh_value_bits != 32). Mirrors fwd kernel
    // args; the bwd uses them to evaluate v_dir against the codec'd SH.
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_fused_bwd_kernel_wrapper<
    Vanilla3DGS<1>,
    CameraModelType::FISHEYE,
    CameraDistortionType::None
>(
    cudaStream_t stream,
    // fwd inputs
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<1>::WorldBuffer splats_world,
    const float * viewmats, // [C, 4, 4]
    const float4 * intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // fwd outputs
    const int32_t * camera_ids,          // [nnz, 4]
    const int32_t * gaussian_ids,          // [nnz, 4]
    const float4 * aabb,          // [C, N, 4]
    // grad outputs
    Vanilla3DGS<1>::ScreenBuffer v_splats_screen,
    // grad inputs
    Vanilla3DGS<1>::WorldBuffer v_splats_world,
    float * v_viewmats, // [C, 4, 4] optional
    // SH VALUE-quant (active when sh_value_bits != 32). Mirrors fwd kernel
    // args; the bwd uses them to evaluate v_dir against the codec'd SH.
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);
