// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "primitives/Primitive3DGS.cuh"
#include "kernels/projection/ProjectionBwdQuantGrad_kernel.cuh"

template void projection_bwd_quantgrad_kernel_wrapper<
    MipSplatting<1>,
    CameraModelType::PINHOLE,
    CameraDistortionType::Rational
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    MipSplatting<1>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    MipSplatting<1>::WorldBuffer v_splats_world,
    MipSplatting<1>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    MipSplatting<1>,
    CameraModelType::FISHEYE,
    CameraDistortionType::None
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    MipSplatting<1>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    MipSplatting<1>::WorldBuffer v_splats_world,
    MipSplatting<1>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    MipSplatting<1>,
    CameraModelType::FISHEYE,
    CameraDistortionType::OpenCV
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    MipSplatting<1>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    MipSplatting<1>::WorldBuffer v_splats_world,
    MipSplatting<1>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    MipSplatting<1>,
    CameraModelType::FISHEYE,
    CameraDistortionType::ThinPrism
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    MipSplatting<1>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    MipSplatting<1>::WorldBuffer v_splats_world,
    MipSplatting<1>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    MipSplatting<1>,
    CameraModelType::EQUISOLID,
    CameraDistortionType::None
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    MipSplatting<1>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    MipSplatting<1>::WorldBuffer v_splats_world,
    MipSplatting<1>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    MipSplatting<1>,
    CameraModelType::EQUISOLID,
    CameraDistortionType::OpenCV
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    MipSplatting<1>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    MipSplatting<1>::WorldBuffer v_splats_world,
    MipSplatting<1>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    MipSplatting<1>,
    CameraModelType::EQUISOLID,
    CameraDistortionType::ThinPrism
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    MipSplatting<1>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    MipSplatting<1>::WorldBuffer v_splats_world,
    MipSplatting<1>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    MipSplatting<1>,
    CameraModelType::EQUIRECTANGULAR,
    CameraDistortionType::None
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    MipSplatting<1>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    MipSplatting<1>::WorldBuffer v_splats_world,
    MipSplatting<1>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);

template void projection_bwd_quantgrad_kernel_wrapper<
    Vanilla3DGS<2>,
    CameraModelType::PINHOLE,
    CameraDistortionType::None
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    const uint32_t num_sh_buffer,
    Vanilla3DGS<2>::WorldBuffer splats_world,
    const float * viewmats,
    const float4 * intrins,
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int32_t * camera_id_bounds,
    const int32_t * camera_ids,
    const int32_t * perm,
    const float4 * aabb,
    Vanilla3DGS<2>::WorldBuffer v_splats_world,
    Vanilla3DGS<2>::ScreenBuffer v_splats_screen,
    GradQuantBuffers gq,
    const uint8_t* sh_value_packed,
    const float2* sh_value_bounds,
    const int64_t sh_value_bounds_stride,
    const int sh_value_bits
);
