// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "primitives/Primitive3DGUT.cuh"
#include "kernels/projection/ProjectionPackedFwd_kernel.cuh"

template void projection_packed_fwd_kernel_wrapper<
    Vanilla3DGUT<4>,
    CameraModelType::PINHOLE,
    CameraDistortionType::OpenCV
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<4>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int64_t* __restrict__ intersection_mask_scan,  // [C, N], inclusive scan
    // outputs
    int32_t *__restrict__ camera_ids,    // [nnz]
    int32_t *__restrict__ gaussian_ids,  // [nnz]
    float4 *__restrict__ aabbs,         // [nnz, 4]
    float *__restrict__ sorting_depths,         // [nnz]
    float *__restrict__ radii,  // [N]
    Vanilla3DGUT<4>::ScreenBuffer splats_screen,  // [nnz, ...]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_fwd_kernel_wrapper<
    Vanilla3DGUT<4>,
    CameraModelType::PINHOLE,
    CameraDistortionType::ThinPrism
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<4>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int64_t* __restrict__ intersection_mask_scan,  // [C, N], inclusive scan
    // outputs
    int32_t *__restrict__ camera_ids,    // [nnz]
    int32_t *__restrict__ gaussian_ids,  // [nnz]
    float4 *__restrict__ aabbs,         // [nnz, 4]
    float *__restrict__ sorting_depths,         // [nnz]
    float *__restrict__ radii,  // [N]
    Vanilla3DGUT<4>::ScreenBuffer splats_screen,  // [nnz, ...]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_fwd_kernel_wrapper<
    Vanilla3DGUT<4>,
    CameraModelType::PINHOLE,
    CameraDistortionType::Rational
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<4>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int64_t* __restrict__ intersection_mask_scan,  // [C, N], inclusive scan
    // outputs
    int32_t *__restrict__ camera_ids,    // [nnz]
    int32_t *__restrict__ gaussian_ids,  // [nnz]
    float4 *__restrict__ aabbs,         // [nnz, 4]
    float *__restrict__ sorting_depths,         // [nnz]
    float *__restrict__ radii,  // [N]
    Vanilla3DGUT<4>::ScreenBuffer splats_screen,  // [nnz, ...]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_fwd_kernel_wrapper<
    Vanilla3DGUT<4>,
    CameraModelType::FISHEYE,
    CameraDistortionType::None
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<4>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int64_t* __restrict__ intersection_mask_scan,  // [C, N], inclusive scan
    // outputs
    int32_t *__restrict__ camera_ids,    // [nnz]
    int32_t *__restrict__ gaussian_ids,  // [nnz]
    float4 *__restrict__ aabbs,         // [nnz, 4]
    float *__restrict__ sorting_depths,         // [nnz]
    float *__restrict__ radii,  // [N]
    Vanilla3DGUT<4>::ScreenBuffer splats_screen,  // [nnz, ...]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_fwd_kernel_wrapper<
    Vanilla3DGUT<4>,
    CameraModelType::FISHEYE,
    CameraDistortionType::OpenCV
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<4>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int64_t* __restrict__ intersection_mask_scan,  // [C, N], inclusive scan
    // outputs
    int32_t *__restrict__ camera_ids,    // [nnz]
    int32_t *__restrict__ gaussian_ids,  // [nnz]
    float4 *__restrict__ aabbs,         // [nnz, 4]
    float *__restrict__ sorting_depths,         // [nnz]
    float *__restrict__ radii,  // [N]
    Vanilla3DGUT<4>::ScreenBuffer splats_screen,  // [nnz, ...]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_fwd_kernel_wrapper<
    Vanilla3DGUT<4>,
    CameraModelType::FISHEYE,
    CameraDistortionType::ThinPrism
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<4>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int64_t* __restrict__ intersection_mask_scan,  // [C, N], inclusive scan
    // outputs
    int32_t *__restrict__ camera_ids,    // [nnz]
    int32_t *__restrict__ gaussian_ids,  // [nnz]
    float4 *__restrict__ aabbs,         // [nnz, 4]
    float *__restrict__ sorting_depths,         // [nnz]
    float *__restrict__ radii,  // [N]
    Vanilla3DGUT<4>::ScreenBuffer splats_screen,  // [nnz, ...]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_fwd_kernel_wrapper<
    Vanilla3DGUT<4>,
    CameraModelType::EQUISOLID,
    CameraDistortionType::None
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<4>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int64_t* __restrict__ intersection_mask_scan,  // [C, N], inclusive scan
    // outputs
    int32_t *__restrict__ camera_ids,    // [nnz]
    int32_t *__restrict__ gaussian_ids,  // [nnz]
    float4 *__restrict__ aabbs,         // [nnz, 4]
    float *__restrict__ sorting_depths,         // [nnz]
    float *__restrict__ radii,  // [N]
    Vanilla3DGUT<4>::ScreenBuffer splats_screen,  // [nnz, ...]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_fwd_kernel_wrapper<
    Vanilla3DGUT<4>,
    CameraModelType::EQUISOLID,
    CameraDistortionType::OpenCV
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<4>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int64_t* __restrict__ intersection_mask_scan,  // [C, N], inclusive scan
    // outputs
    int32_t *__restrict__ camera_ids,    // [nnz]
    int32_t *__restrict__ gaussian_ids,  // [nnz]
    float4 *__restrict__ aabbs,         // [nnz, 4]
    float *__restrict__ sorting_depths,         // [nnz]
    float *__restrict__ radii,  // [N]
    Vanilla3DGUT<4>::ScreenBuffer splats_screen,  // [nnz, ...]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_fwd_kernel_wrapper<
    Vanilla3DGUT<4>,
    CameraModelType::EQUISOLID,
    CameraDistortionType::ThinPrism
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGUT<4>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    const int64_t* __restrict__ intersection_mask_scan,  // [C, N], inclusive scan
    // outputs
    int32_t *__restrict__ camera_ids,    // [nnz]
    int32_t *__restrict__ gaussian_ids,  // [nnz]
    float4 *__restrict__ aabbs,         // [nnz, 4]
    float *__restrict__ sorting_depths,         // [nnz]
    float *__restrict__ radii,  // [N]
    Vanilla3DGUT<4>::ScreenBuffer splats_screen,  // [nnz, ...]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);
