// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "primitives/Primitive3DGS.cuh"
#include "kernels/projection/ProjectionPackedFwd_kernel.cuh"

template void projection_packed_mask_kernel_wrapper<
    Vanilla3DGS<0>,
    CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<0>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    bool *__restrict__ intersection_mask,  // [C, N]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_mask_kernel_wrapper<
    Vanilla3DGS<0>,
    CameraModelType::FISHEYE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<0>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    bool *__restrict__ intersection_mask,  // [C, N]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_mask_kernel_wrapper<
    Vanilla3DGS<0>,
    CameraModelType::EQUISOLID
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<0>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    bool *__restrict__ intersection_mask,  // [C, N]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_mask_kernel_wrapper<
    Vanilla3DGS<0>,
    CameraModelType::EQUIRECTANGULAR
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<0>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    bool *__restrict__ intersection_mask,  // [C, N]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_mask_kernel_wrapper<
    MipSplatting<0>,
    CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    MipSplatting<0>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    bool *__restrict__ intersection_mask,  // [C, N]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_mask_kernel_wrapper<
    MipSplatting<0>,
    CameraModelType::FISHEYE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    MipSplatting<0>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    bool *__restrict__ intersection_mask,  // [C, N]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_mask_kernel_wrapper<
    MipSplatting<0>,
    CameraModelType::EQUISOLID
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    MipSplatting<0>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    bool *__restrict__ intersection_mask,  // [C, N]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_mask_kernel_wrapper<
    MipSplatting<0>,
    CameraModelType::EQUIRECTANGULAR
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    MipSplatting<0>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    bool *__restrict__ intersection_mask,  // [C, N]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);

template void projection_packed_mask_kernel_wrapper<
    Vanilla3DGS<1>,
    CameraModelType::PINHOLE
>(
    cudaStream_t stream,
    const uint32_t C,
    const uint32_t N,
    Vanilla3DGS<1>::WorldBuffer splats_world,  // [N, ...]
    const float *__restrict__ viewmats, // [C, 4, 4]
    const float4 *__restrict__ intrins,  // [C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const uint32_t image_width,
    const uint32_t image_height,
    // outputs
    bool *__restrict__ intersection_mask,  // [C, N]
    const uint8_t* __restrict__ sh_value_packed,
    const float2* __restrict__ sh_value_bounds,
    const uint32_t num_sh_buffer,
    const int sh_value_bits,
    const int64_t sh_bounds_stride
);
