// This file is auto generated by `generate_kernel_instantiation.py`

#define NO_TORCH
#include "primitives/Primitive3DGUT.cuh"
#include "kernels/raster/RasterizationEval3DBwd_kernel.cuh"

template void rasterize_to_pixels_eval3d_bwd_kernel_wrapper<
    Vanilla3DGUT<0>,
    CameraModelType::FISHEYE,
    CameraDistortionType::ThinPrism,
    DistortionType::None,
    false,
    DensifyAccumMode::None,
    false
>(
    cudaStream_t stream,
    const uint32_t I,
    const uint32_t N,   // zero if packed
    const uint32_t n_isects,
    // fwd inputs
    const uint32_t *__restrict__ gaussian_ids,  // [nnz] optional, for packed mode
    const Vanilla3DGUT<0>::WorldBuffer splat_wbuffer,
    const Vanilla3DGUT<0>::ScreenBuffer splat_sbuffer,
    const float *__restrict__ viewmats, // [B, C, 4, 4]
    const float4 *__restrict__ intrins,  // [B, C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const float4 *__restrict__ aabb,  // [..., N] projected 2D AABB
    const uint32_t image_width,
    const uint32_t image_height,
    const uint32_t tile_width,
    const uint32_t tile_height,
    const int32_t *__restrict__ tile_offsets, // [..., tile_height, tile_width]
    const int32_t *__restrict__ flatten_ids,  // [n_isects]
    // fwd outputs
    const float *__restrict__ render_Ts,      // [..., image_height, image_width, 1]
    const int32_t *__restrict__ last_ids, // [..., image_height, image_width]
    RenderOutput::Buffer render_output_buffer,
    RenderOutput::Buffer render_distortion_buffer,
    const float *__restrict__ loss_map_buffer,           // [..., image_height, image_width, 1]
    const float *__restrict__ accum_weight_map_buffer,           // [..., image_height, image_width, 1]
    // grad outputs
    RenderOutput::Buffer v_render_output_buffer,
    const float *__restrict__ v_render_Ts, // [..., image_height, image_width, 1]
    const float *__restrict__ v_median, // [..., image_height, image_width, 1], optional
    RenderOutput::Buffer v_distortions_output_buffer,
    // grad inputs
    Vanilla3DGUT<0>::WorldBuffer v_splat_wbuffer,
    Vanilla3DGUT<0>::ScreenBuffer v_splat_sbuffer,
    float *__restrict__ o_accum_weight,
    float *__restrict__ o_accum_weight_den,
    float *__restrict__ v_viewmats // [B, C, 4, 4]
);

template void rasterize_to_pixels_eval3d_bwd_kernel_wrapper<
    Vanilla3DGUT<0>,
    CameraModelType::FISHEYE,
    CameraDistortionType::ThinPrism,
    DistortionType::None,
    false,
    DensifyAccumMode::Max,
    true
>(
    cudaStream_t stream,
    const uint32_t I,
    const uint32_t N,   // zero if packed
    const uint32_t n_isects,
    // fwd inputs
    const uint32_t *__restrict__ gaussian_ids,  // [nnz] optional, for packed mode
    const Vanilla3DGUT<0>::WorldBuffer splat_wbuffer,
    const Vanilla3DGUT<0>::ScreenBuffer splat_sbuffer,
    const float *__restrict__ viewmats, // [B, C, 4, 4]
    const float4 *__restrict__ intrins,  // [B, C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const float4 *__restrict__ aabb,  // [..., N] projected 2D AABB
    const uint32_t image_width,
    const uint32_t image_height,
    const uint32_t tile_width,
    const uint32_t tile_height,
    const int32_t *__restrict__ tile_offsets, // [..., tile_height, tile_width]
    const int32_t *__restrict__ flatten_ids,  // [n_isects]
    // fwd outputs
    const float *__restrict__ render_Ts,      // [..., image_height, image_width, 1]
    const int32_t *__restrict__ last_ids, // [..., image_height, image_width]
    RenderOutput::Buffer render_output_buffer,
    RenderOutput::Buffer render_distortion_buffer,
    const float *__restrict__ loss_map_buffer,           // [..., image_height, image_width, 1]
    const float *__restrict__ accum_weight_map_buffer,           // [..., image_height, image_width, 1]
    // grad outputs
    RenderOutput::Buffer v_render_output_buffer,
    const float *__restrict__ v_render_Ts, // [..., image_height, image_width, 1]
    const float *__restrict__ v_median, // [..., image_height, image_width, 1], optional
    RenderOutput::Buffer v_distortions_output_buffer,
    // grad inputs
    Vanilla3DGUT<0>::WorldBuffer v_splat_wbuffer,
    Vanilla3DGUT<0>::ScreenBuffer v_splat_sbuffer,
    float *__restrict__ o_accum_weight,
    float *__restrict__ o_accum_weight_den,
    float *__restrict__ v_viewmats // [B, C, 4, 4]
);

template void rasterize_to_pixels_eval3d_bwd_kernel_wrapper<
    Vanilla3DGUT<0>,
    CameraModelType::FISHEYE,
    CameraDistortionType::ThinPrism,
    DistortionType::None,
    false,
    DensifyAccumMode::Max,
    false
>(
    cudaStream_t stream,
    const uint32_t I,
    const uint32_t N,   // zero if packed
    const uint32_t n_isects,
    // fwd inputs
    const uint32_t *__restrict__ gaussian_ids,  // [nnz] optional, for packed mode
    const Vanilla3DGUT<0>::WorldBuffer splat_wbuffer,
    const Vanilla3DGUT<0>::ScreenBuffer splat_sbuffer,
    const float *__restrict__ viewmats, // [B, C, 4, 4]
    const float4 *__restrict__ intrins,  // [B, C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const float4 *__restrict__ aabb,  // [..., N] projected 2D AABB
    const uint32_t image_width,
    const uint32_t image_height,
    const uint32_t tile_width,
    const uint32_t tile_height,
    const int32_t *__restrict__ tile_offsets, // [..., tile_height, tile_width]
    const int32_t *__restrict__ flatten_ids,  // [n_isects]
    // fwd outputs
    const float *__restrict__ render_Ts,      // [..., image_height, image_width, 1]
    const int32_t *__restrict__ last_ids, // [..., image_height, image_width]
    RenderOutput::Buffer render_output_buffer,
    RenderOutput::Buffer render_distortion_buffer,
    const float *__restrict__ loss_map_buffer,           // [..., image_height, image_width, 1]
    const float *__restrict__ accum_weight_map_buffer,           // [..., image_height, image_width, 1]
    // grad outputs
    RenderOutput::Buffer v_render_output_buffer,
    const float *__restrict__ v_render_Ts, // [..., image_height, image_width, 1]
    const float *__restrict__ v_median, // [..., image_height, image_width, 1], optional
    RenderOutput::Buffer v_distortions_output_buffer,
    // grad inputs
    Vanilla3DGUT<0>::WorldBuffer v_splat_wbuffer,
    Vanilla3DGUT<0>::ScreenBuffer v_splat_sbuffer,
    float *__restrict__ o_accum_weight,
    float *__restrict__ o_accum_weight_den,
    float *__restrict__ v_viewmats // [B, C, 4, 4]
);

template void rasterize_to_pixels_eval3d_bwd_kernel_wrapper<
    Vanilla3DGUT<0>,
    CameraModelType::FISHEYE,
    CameraDistortionType::ThinPrism,
    DistortionType::None,
    false,
    DensifyAccumMode::Sum,
    true
>(
    cudaStream_t stream,
    const uint32_t I,
    const uint32_t N,   // zero if packed
    const uint32_t n_isects,
    // fwd inputs
    const uint32_t *__restrict__ gaussian_ids,  // [nnz] optional, for packed mode
    const Vanilla3DGUT<0>::WorldBuffer splat_wbuffer,
    const Vanilla3DGUT<0>::ScreenBuffer splat_sbuffer,
    const float *__restrict__ viewmats, // [B, C, 4, 4]
    const float4 *__restrict__ intrins,  // [B, C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const float4 *__restrict__ aabb,  // [..., N] projected 2D AABB
    const uint32_t image_width,
    const uint32_t image_height,
    const uint32_t tile_width,
    const uint32_t tile_height,
    const int32_t *__restrict__ tile_offsets, // [..., tile_height, tile_width]
    const int32_t *__restrict__ flatten_ids,  // [n_isects]
    // fwd outputs
    const float *__restrict__ render_Ts,      // [..., image_height, image_width, 1]
    const int32_t *__restrict__ last_ids, // [..., image_height, image_width]
    RenderOutput::Buffer render_output_buffer,
    RenderOutput::Buffer render_distortion_buffer,
    const float *__restrict__ loss_map_buffer,           // [..., image_height, image_width, 1]
    const float *__restrict__ accum_weight_map_buffer,           // [..., image_height, image_width, 1]
    // grad outputs
    RenderOutput::Buffer v_render_output_buffer,
    const float *__restrict__ v_render_Ts, // [..., image_height, image_width, 1]
    const float *__restrict__ v_median, // [..., image_height, image_width, 1], optional
    RenderOutput::Buffer v_distortions_output_buffer,
    // grad inputs
    Vanilla3DGUT<0>::WorldBuffer v_splat_wbuffer,
    Vanilla3DGUT<0>::ScreenBuffer v_splat_sbuffer,
    float *__restrict__ o_accum_weight,
    float *__restrict__ o_accum_weight_den,
    float *__restrict__ v_viewmats // [B, C, 4, 4]
);

template void rasterize_to_pixels_eval3d_bwd_kernel_wrapper<
    Vanilla3DGUT<0>,
    CameraModelType::FISHEYE,
    CameraDistortionType::ThinPrism,
    DistortionType::None,
    false,
    DensifyAccumMode::Sum,
    false
>(
    cudaStream_t stream,
    const uint32_t I,
    const uint32_t N,   // zero if packed
    const uint32_t n_isects,
    // fwd inputs
    const uint32_t *__restrict__ gaussian_ids,  // [nnz] optional, for packed mode
    const Vanilla3DGUT<0>::WorldBuffer splat_wbuffer,
    const Vanilla3DGUT<0>::ScreenBuffer splat_sbuffer,
    const float *__restrict__ viewmats, // [B, C, 4, 4]
    const float4 *__restrict__ intrins,  // [B, C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const float4 *__restrict__ aabb,  // [..., N] projected 2D AABB
    const uint32_t image_width,
    const uint32_t image_height,
    const uint32_t tile_width,
    const uint32_t tile_height,
    const int32_t *__restrict__ tile_offsets, // [..., tile_height, tile_width]
    const int32_t *__restrict__ flatten_ids,  // [n_isects]
    // fwd outputs
    const float *__restrict__ render_Ts,      // [..., image_height, image_width, 1]
    const int32_t *__restrict__ last_ids, // [..., image_height, image_width]
    RenderOutput::Buffer render_output_buffer,
    RenderOutput::Buffer render_distortion_buffer,
    const float *__restrict__ loss_map_buffer,           // [..., image_height, image_width, 1]
    const float *__restrict__ accum_weight_map_buffer,           // [..., image_height, image_width, 1]
    // grad outputs
    RenderOutput::Buffer v_render_output_buffer,
    const float *__restrict__ v_render_Ts, // [..., image_height, image_width, 1]
    const float *__restrict__ v_median, // [..., image_height, image_width, 1], optional
    RenderOutput::Buffer v_distortions_output_buffer,
    // grad inputs
    Vanilla3DGUT<0>::WorldBuffer v_splat_wbuffer,
    Vanilla3DGUT<0>::ScreenBuffer v_splat_sbuffer,
    float *__restrict__ o_accum_weight,
    float *__restrict__ o_accum_weight_den,
    float *__restrict__ v_viewmats // [B, C, 4, 4]
);

template void rasterize_to_pixels_eval3d_bwd_kernel_wrapper<
    Vanilla3DGUT<0>,
    CameraModelType::FISHEYE,
    CameraDistortionType::ThinPrism,
    DistortionType::None,
    false,
    DensifyAccumMode::Avg,
    true
>(
    cudaStream_t stream,
    const uint32_t I,
    const uint32_t N,   // zero if packed
    const uint32_t n_isects,
    // fwd inputs
    const uint32_t *__restrict__ gaussian_ids,  // [nnz] optional, for packed mode
    const Vanilla3DGUT<0>::WorldBuffer splat_wbuffer,
    const Vanilla3DGUT<0>::ScreenBuffer splat_sbuffer,
    const float *__restrict__ viewmats, // [B, C, 4, 4]
    const float4 *__restrict__ intrins,  // [B, C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const float4 *__restrict__ aabb,  // [..., N] projected 2D AABB
    const uint32_t image_width,
    const uint32_t image_height,
    const uint32_t tile_width,
    const uint32_t tile_height,
    const int32_t *__restrict__ tile_offsets, // [..., tile_height, tile_width]
    const int32_t *__restrict__ flatten_ids,  // [n_isects]
    // fwd outputs
    const float *__restrict__ render_Ts,      // [..., image_height, image_width, 1]
    const int32_t *__restrict__ last_ids, // [..., image_height, image_width]
    RenderOutput::Buffer render_output_buffer,
    RenderOutput::Buffer render_distortion_buffer,
    const float *__restrict__ loss_map_buffer,           // [..., image_height, image_width, 1]
    const float *__restrict__ accum_weight_map_buffer,           // [..., image_height, image_width, 1]
    // grad outputs
    RenderOutput::Buffer v_render_output_buffer,
    const float *__restrict__ v_render_Ts, // [..., image_height, image_width, 1]
    const float *__restrict__ v_median, // [..., image_height, image_width, 1], optional
    RenderOutput::Buffer v_distortions_output_buffer,
    // grad inputs
    Vanilla3DGUT<0>::WorldBuffer v_splat_wbuffer,
    Vanilla3DGUT<0>::ScreenBuffer v_splat_sbuffer,
    float *__restrict__ o_accum_weight,
    float *__restrict__ o_accum_weight_den,
    float *__restrict__ v_viewmats // [B, C, 4, 4]
);

template void rasterize_to_pixels_eval3d_bwd_kernel_wrapper<
    Vanilla3DGUT<0>,
    CameraModelType::FISHEYE,
    CameraDistortionType::ThinPrism,
    DistortionType::None,
    false,
    DensifyAccumMode::Avg,
    false
>(
    cudaStream_t stream,
    const uint32_t I,
    const uint32_t N,   // zero if packed
    const uint32_t n_isects,
    // fwd inputs
    const uint32_t *__restrict__ gaussian_ids,  // [nnz] optional, for packed mode
    const Vanilla3DGUT<0>::WorldBuffer splat_wbuffer,
    const Vanilla3DGUT<0>::ScreenBuffer splat_sbuffer,
    const float *__restrict__ viewmats, // [B, C, 4, 4]
    const float4 *__restrict__ intrins,  // [B, C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const float4 *__restrict__ aabb,  // [..., N] projected 2D AABB
    const uint32_t image_width,
    const uint32_t image_height,
    const uint32_t tile_width,
    const uint32_t tile_height,
    const int32_t *__restrict__ tile_offsets, // [..., tile_height, tile_width]
    const int32_t *__restrict__ flatten_ids,  // [n_isects]
    // fwd outputs
    const float *__restrict__ render_Ts,      // [..., image_height, image_width, 1]
    const int32_t *__restrict__ last_ids, // [..., image_height, image_width]
    RenderOutput::Buffer render_output_buffer,
    RenderOutput::Buffer render_distortion_buffer,
    const float *__restrict__ loss_map_buffer,           // [..., image_height, image_width, 1]
    const float *__restrict__ accum_weight_map_buffer,           // [..., image_height, image_width, 1]
    // grad outputs
    RenderOutput::Buffer v_render_output_buffer,
    const float *__restrict__ v_render_Ts, // [..., image_height, image_width, 1]
    const float *__restrict__ v_median, // [..., image_height, image_width, 1], optional
    RenderOutput::Buffer v_distortions_output_buffer,
    // grad inputs
    Vanilla3DGUT<0>::WorldBuffer v_splat_wbuffer,
    Vanilla3DGUT<0>::ScreenBuffer v_splat_sbuffer,
    float *__restrict__ o_accum_weight,
    float *__restrict__ o_accum_weight_den,
    float *__restrict__ v_viewmats // [B, C, 4, 4]
);

template void rasterize_to_pixels_eval3d_bwd_kernel_wrapper<
    Vanilla3DGUT<0>,
    CameraModelType::FISHEYE,
    CameraDistortionType::ThinPrism,
    DistortionType::D,
    true,
    DensifyAccumMode::None,
    true
>(
    cudaStream_t stream,
    const uint32_t I,
    const uint32_t N,   // zero if packed
    const uint32_t n_isects,
    // fwd inputs
    const uint32_t *__restrict__ gaussian_ids,  // [nnz] optional, for packed mode
    const Vanilla3DGUT<0>::WorldBuffer splat_wbuffer,
    const Vanilla3DGUT<0>::ScreenBuffer splat_sbuffer,
    const float *__restrict__ viewmats, // [B, C, 4, 4]
    const float4 *__restrict__ intrins,  // [B, C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const float4 *__restrict__ aabb,  // [..., N] projected 2D AABB
    const uint32_t image_width,
    const uint32_t image_height,
    const uint32_t tile_width,
    const uint32_t tile_height,
    const int32_t *__restrict__ tile_offsets, // [..., tile_height, tile_width]
    const int32_t *__restrict__ flatten_ids,  // [n_isects]
    // fwd outputs
    const float *__restrict__ render_Ts,      // [..., image_height, image_width, 1]
    const int32_t *__restrict__ last_ids, // [..., image_height, image_width]
    RenderOutput::Buffer render_output_buffer,
    RenderOutput::Buffer render_distortion_buffer,
    const float *__restrict__ loss_map_buffer,           // [..., image_height, image_width, 1]
    const float *__restrict__ accum_weight_map_buffer,           // [..., image_height, image_width, 1]
    // grad outputs
    RenderOutput::Buffer v_render_output_buffer,
    const float *__restrict__ v_render_Ts, // [..., image_height, image_width, 1]
    const float *__restrict__ v_median, // [..., image_height, image_width, 1], optional
    RenderOutput::Buffer v_distortions_output_buffer,
    // grad inputs
    Vanilla3DGUT<0>::WorldBuffer v_splat_wbuffer,
    Vanilla3DGUT<0>::ScreenBuffer v_splat_sbuffer,
    float *__restrict__ o_accum_weight,
    float *__restrict__ o_accum_weight_den,
    float *__restrict__ v_viewmats // [B, C, 4, 4]
);

template void rasterize_to_pixels_eval3d_bwd_kernel_wrapper<
    Vanilla3DGUT<0>,
    CameraModelType::FISHEYE,
    CameraDistortionType::ThinPrism,
    DistortionType::D,
    true,
    DensifyAccumMode::None,
    false
>(
    cudaStream_t stream,
    const uint32_t I,
    const uint32_t N,   // zero if packed
    const uint32_t n_isects,
    // fwd inputs
    const uint32_t *__restrict__ gaussian_ids,  // [nnz] optional, for packed mode
    const Vanilla3DGUT<0>::WorldBuffer splat_wbuffer,
    const Vanilla3DGUT<0>::ScreenBuffer splat_sbuffer,
    const float *__restrict__ viewmats, // [B, C, 4, 4]
    const float4 *__restrict__ intrins,  // [B, C, 4], fx, fy, cx, cy
    const CameraDistortionCoeffsBuffer dist_coeffs_buffer,
    const float4 *__restrict__ aabb,  // [..., N] projected 2D AABB
    const uint32_t image_width,
    const uint32_t image_height,
    const uint32_t tile_width,
    const uint32_t tile_height,
    const int32_t *__restrict__ tile_offsets, // [..., tile_height, tile_width]
    const int32_t *__restrict__ flatten_ids,  // [n_isects]
    // fwd outputs
    const float *__restrict__ render_Ts,      // [..., image_height, image_width, 1]
    const int32_t *__restrict__ last_ids, // [..., image_height, image_width]
    RenderOutput::Buffer render_output_buffer,
    RenderOutput::Buffer render_distortion_buffer,
    const float *__restrict__ loss_map_buffer,           // [..., image_height, image_width, 1]
    const float *__restrict__ accum_weight_map_buffer,           // [..., image_height, image_width, 1]
    // grad outputs
    RenderOutput::Buffer v_render_output_buffer,
    const float *__restrict__ v_render_Ts, // [..., image_height, image_width, 1]
    const float *__restrict__ v_median, // [..., image_height, image_width, 1], optional
    RenderOutput::Buffer v_distortions_output_buffer,
    // grad inputs
    Vanilla3DGUT<0>::WorldBuffer v_splat_wbuffer,
    Vanilla3DGUT<0>::ScreenBuffer v_splat_sbuffer,
    float *__restrict__ o_accum_weight,
    float *__restrict__ o_accum_weight_den,
    float *__restrict__ v_viewmats // [B, C, 4, 4]
);
