
var createModule = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir ||= __filename;
  return (
function(moduleArg = {}) {

var k=moduleArg,aa,ba;k.ready=new Promise((a,b)=>{aa=a;ba=b});var ea=Object.assign({},k),fa=(a,b)=>{throw b;},ha="object"==typeof window,p="function"==typeof importScripts,ia="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,r="",ja,ka,la;
if(ia){var fs=require("fs"),ma=require("path");r=p?ma.dirname(r)+"/":__dirname+"/";ja=(a,b)=>{a=na(a)?new URL(a):ma.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};la=a=>{a=ja(a,!0);a.buffer||(a=new Uint8Array(a));return a};ka=(a,b,c,d=!0)=>{a=na(a)?new URL(a):ma.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,f)=>{e?c(e):b(d?f.buffer:f)})};process.argv.slice(2);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(ha||p)p?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&
(r=document.currentScript.src),_scriptDir&&(r=_scriptDir),r.startsWith("blob:")?r="":r=r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1),ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},p&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):
c()};d.onerror=c;d.send(null)};var oa=k.print||console.log.bind(console),t=k.printErr||console.error.bind(console);Object.assign(k,ea);ea=null;k.quit&&(fa=k.quit);var w;k.wasmBinary&&(w=k.wasmBinary);"object"!=typeof WebAssembly&&pa("no native wasm support detected");var qa,ra=!1,sa,z,A,ta,C,D,ua,va;
function wa(){var a=qa.buffer;k.HEAP8=sa=new Int8Array(a);k.HEAP16=A=new Int16Array(a);k.HEAPU8=z=new Uint8Array(a);k.HEAPU16=ta=new Uint16Array(a);k.HEAP32=C=new Int32Array(a);k.HEAPU32=D=new Uint32Array(a);k.HEAPF32=ua=new Float32Array(a);k.HEAPF64=va=new Float64Array(a)}var xa=[],ya=[],za=[],Aa=[];function Ba(){var a=k.preRun.shift();xa.unshift(a)}var E=0,Ca=null,F=null;
function pa(a){k.onAbort?.(a);a="Aborted("+a+")";t(a);ra=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Da=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),G;G="module.wasm";if(!Da(G)){var Ea=G;G=k.locateFile?k.locateFile(Ea,r):r+Ea}function Fa(a){if(a==G&&w)return new Uint8Array(w);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}
function Ga(a){if(!w&&(ha||p)){if("function"==typeof fetch&&!na(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Fa(a));if(ka)return new Promise((b,c)=>{ka(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Fa(a))}function Ha(a,b,c){return Ga(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{t(`failed to asynchronously prepare wasm: ${d}`);pa(d)})}
function Ia(a,b){var c=G;return w||"function"!=typeof WebAssembly.instantiateStreaming||Da(c)||na(c)||ia||"function"!=typeof fetch?Ha(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){t(`wasm streaming compile failed: ${e}`);t("falling back to ArrayBuffer instantiation");return Ha(c,a,b)}))}function Ja(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ka=a=>{for(;0<a.length;)a.shift()(k)},La=k.noExitRuntime||!0,Ma="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,H=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ma)return Ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d};class Na{constructor(a){this.W=a-24}}var Oa=0,Pa=0,Ra={},Sa=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function J(a){return this.fromWireType(D[a>>2])}
var K={},L={},Ta={},M,O=(a,b,c)=>{function d(g){g=c(g);if(g.length!==a.length)throw new M("Mismatched type converter count");for(var m=0;m<a.length;++m)N(a[m],g[m])}a.forEach(function(g){Ta[g]=b});var e=Array(b.length),f=[],h=0;b.forEach((g,m)=>{L.hasOwnProperty(g)?e[m]=L[g]:(f.push(g),K.hasOwnProperty(g)||(K[g]=[]),K[g].push(()=>{e[m]=L[g];++h;h===f.length&&d(e)}))});0===f.length&&d(e)},Ua,P=a=>{for(var b="";z[a];)b+=Ua[z[a++]];return b},Q,Va=a=>{throw new Q(a);};
function Wa(a,b,c={}){var d=b.name;if(!a)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(L.hasOwnProperty(a)){if(c.Aa)return;throw new Q(`Cannot register type '${d}' twice`);}L[a]=b;delete Ta[a];K.hasOwnProperty(a)&&(b=K[a],delete K[a],b.forEach(e=>e()))}function N(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");return Wa(a,b,c)}
var Xa=a=>{throw new Q(a.T.X.V.name+" instance already deleted");},Ya=!1,Za=()=>{},$a=(a,b,c)=>{if(b===c)return a;if(void 0===c.$)return null;a=$a(a,b,c.$);return null===a?null:c.ta(a)},ab={},R=[],bb=()=>{for(;R.length;){var a=R.pop();a.T.fa=!1;a["delete"]()}},S,T={},cb=(a,b)=>{if(void 0===b)throw new Q("ptr should not be undefined");for(;a.$;)b=a.ia(b),a=a.$;return T[b]},eb=(a,b)=>{if(!b.X||!b.W)throw new M("makeClassHandle requires ptr and ptrType");if(!!b.aa!==!!b.Y)throw new M("Both smartPtrType and smartPtr must be specified");
b.count={value:1};return db(Object.create(a,{T:{value:b,writable:!0}}))},db=a=>{if("undefined"===typeof FinalizationRegistry)return db=b=>b,a;Ya=new FinalizationRegistry(b=>{b=b.T;--b.count.value;0===b.count.value&&(b.Y?b.aa.da(b.Y):b.X.V.da(b.W))});db=b=>{var c=b.T;c.Y&&Ya.register(b,{T:c},b);return b};Za=b=>{Ya.unregister(b)};return db(a)};function fb(){}
var gb=(a,b)=>Object.defineProperty(b,"name",{value:a}),hb=(a,b,c)=>{if(void 0===a[b].Z){var d=a[b];a[b]=function(...e){if(!a[b].Z.hasOwnProperty(e.length))throw new Q(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].Z})!`);return a[b].Z[e.length].apply(this,e)};a[b].Z=[];a[b].Z[d.ja]=d}},ib=(a,b,c)=>{if(k.hasOwnProperty(a)){if(void 0===c||void 0!==k[a].Z&&void 0!==k[a].Z[c])throw new Q(`Cannot register public name '${a}' twice`);hb(k,a,a);if(k.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
k[a].Z[c]=b}else k[a]=b,void 0!==c&&(k[a].Ja=c)},jb=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function kb(a,b,c,d,e,f,h,g){this.name=a;this.constructor=b;this.ga=c;this.da=d;this.$=e;this.va=f;this.ia=h;this.ta=g;this.Da=[]}var lb=(a,b,c)=>{for(;b!==c;){if(!b.ia)throw new Q(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ia(a);b=b.$}return a};
function mb(a,b){if(null===b){if(this.ma)throw new Q(`null is not a valid ${this.name}`);return 0}if(!b.T)throw new Q(`Cannot pass "${nb(b)}" as a ${this.name}`);if(!b.T.W)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);return lb(b.T.W,b.T.X.V,this.V)}
function ob(a,b){if(null===b){if(this.ma)throw new Q(`null is not a valid ${this.name}`);if(this.la){var c=this.na();null!==a&&a.push(this.da,c);return c}return 0}if(!b||!b.T)throw new Q(`Cannot pass "${nb(b)}" as a ${this.name}`);if(!b.T.W)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ka&&b.T.X.ka)throw new Q(`Cannot convert argument of type ${b.T.aa?b.T.aa.name:b.T.X.name} to parameter type ${this.name}`);c=lb(b.T.W,b.T.X.V,this.V);if(this.la){if(void 0===
b.T.Y)throw new Q("Passing raw pointer to smart pointer is illegal");switch(this.Ia){case 0:if(b.T.aa===this)c=b.T.Y;else throw new Q(`Cannot convert argument of type ${b.T.aa?b.T.aa.name:b.T.X.name} to parameter type ${this.name}`);break;case 1:c=b.T.Y;break;case 2:if(b.T.aa===this)c=b.T.Y;else{var d=b.clone();c=this.Ea(c,U(()=>d["delete"]()));null!==a&&a.push(this.da,c)}break;default:throw new Q("Unsupporting sharing policy");}}return c}
function pb(a,b){if(null===b){if(this.ma)throw new Q(`null is not a valid ${this.name}`);return 0}if(!b.T)throw new Q(`Cannot pass "${nb(b)}" as a ${this.name}`);if(!b.T.W)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.T.X.ka)throw new Q(`Cannot convert argument of type ${b.T.X.name} to parameter type ${this.name}`);return lb(b.T.W,b.T.X.V,this.V)}
function qb(a,b,c,d,e,f,h,g,m,l,n){this.name=a;this.V=b;this.ma=c;this.ka=d;this.la=e;this.Ca=f;this.Ia=h;this.ra=g;this.na=m;this.Ea=l;this.da=n;e||void 0!==b.$?this.toWireType=ob:(this.toWireType=d?mb:pb,this.ba=null)}
var rb=(a,b,c)=>{if(!k.hasOwnProperty(a))throw new M("Replacing nonexistent public symbol");void 0!==k[a].Z&&void 0!==c?k[a].Z[c]=b:(k[a]=b,k[a].ja=c)},sb=[],tb,ub=a=>{var b=sb[a];b||(a>=sb.length&&(sb.length=a+1),sb[a]=b=tb.get(a));return b},vb=(a,b,c=[])=>a.includes("j")?(0,k["dynCall_"+a])(b,...c):ub(b)(...c),wb=(a,b)=>(...c)=>vb(a,b,c),V=(a,b)=>{a=P(a);var c=a.includes("j")?wb(a,b):ub(b);if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${a}: ${b}`);return c},xb,zb=
a=>{a=yb(a);var b=P(a);W(a);return b},Ab=(a,b)=>{function c(f){e[f]||L[f]||(Ta[f]?Ta[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new xb(`${a}: `+d.map(zb).join([", "]));},Bb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c};function Cb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].ba)return!0;return!1}
function Db(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=gb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Eb(a,b,c,d,e,f){var h=b.length;if(2>h)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,m=Cb(b);c="void"!==b[0].name;d=[a,Va,d,e,Sa,b[0],b[1]];for(e=0;e<h-2;++e)d.push(b[e+2]);if(!m)for(e=g?1:2;e<b.length;++e)null!==b[e].ba&&d.push(b[e].ba);m=Cb(b);e=b.length;var l="",n="";for(h=0;h<e-2;++h)l+=(0!==h?", ":"")+"arg"+h,n+=(0!==h?", ":"")+"arg"+h+"Wired";l=`\n        return function (${l}) {\n        if (arguments.length !== ${e-
2}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${e-2}');\n        }`;m&&(l+="var destructors = [];\n");var q=m?"destructors":"null",u="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");g&&(l+="var thisWired = classParam['toWireType']("+q+", this);\n");for(h=0;h<e-2;++h)l+="var arg"+h+"Wired = argType"+h+"['toWireType']("+q+", arg"+h+");\n",u.push("argType"+h);g&&(n="thisWired"+(0<n.length?", ":
"")+n);l+=(c||f?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(m)l+="runDestructors(destructors);\n";else for(h=g?1:2;h<b.length;++h)f=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==b[h].ba&&(l+=`${f}_dtor(${f});\n`,u.push(`${f}_dtor`));c&&(l+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [x,v]=[u,l+"}\n"];x.push(v);b=Db(x)(...d);return gb(a,b)}
var Fb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Hb=[],X=[],Ib=a=>{9<a&&0===--X[a+1]&&(X[a]=void 0,Hb.push(a))},Y=a=>{if(!a)throw new Q("Cannot use deleted val. handle = "+a);return X[a]},U=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Hb.pop()||X.length;X[b]=a;X[b+1]=1;return b}},Jb={name:"emscripten::val",fromWireType:a=>{var b=Y(a);Ib(a);return b},toWireType:(a,b)=>U(b),argPackAdvance:8,readValueFromPointer:J,ba:null},
nb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Kb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ua[c>>2])};case 8:return function(c){return this.fromWireType(va[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Lb=(a,b,c)=>{switch(b){case 1:return c?d=>sa[d]:d=>z[d];case 2:return c?d=>A[d>>1]:d=>ta[d>>1];case 4:return c?d=>C[d>>2]:d=>D[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}},Mb=(a,b,c)=>{var d=z;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0}},Nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=
d?(b+=4,++c):b+=3}return b},Ob="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Pb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-a&&Ob)return Ob.decode(z.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=A[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Qb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)A[b>>1]=a.charCodeAt(e),b+=2;A[b>>1]=0;return b-d},Rb=a=>2*a.length,Sb=(a,b)=>{for(var c=0,
d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Tb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d},Ub=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Vb=(a,
b)=>{var c=L[a];if(void 0===c)throw a=`${b} has unknown type ${zb(a)}`,new Q(a);return c},Wb=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(D[b>>2]=U(d));return a},Xb=[],Yb={},Zb=a=>{var b=Yb[a];return void 0===b?P(a):b},$b=()=>"object"==typeof globalThis?globalThis:Function("return this")(),ac=a=>{var b=Xb.length;Xb.push(a);return b},bc=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Vb(D[b+4*d>>2],"parameter "+d);return c},cc=[null,[],[]],gc=(a,b,c,d)=>{var e={string:l=>{var n=0;if(null!==l&&void 0!==
l&&0!==l){n=Nb(l)+1;var q=dc(n);Mb(l,q,n);n=q}return n},array:l=>{var n=dc(l.length);sa.set(l,n);return n}};a=k["_"+a];var f=[],h=0;if(d)for(var g=0;g<d.length;g++){var m=e[c[g]];m?(0===h&&(h=ec()),f[g]=m(d[g])):f[g]=d[g]}c=a(...f);return c=function(l){0!==h&&fc(h);return"string"===b?l?H(z,l):"":"boolean"===b?!!l:l}(c)};M=k.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var hc=Array(256),ic=0;256>ic;++ic)hc[ic]=String.fromCharCode(ic);Ua=hc;
Q=k.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(fb.prototype,{isAliasOf:function(a){if(!(this instanceof fb&&a instanceof fb))return!1;var b=this.T.X.V,c=this.T.W;a.T=a.T;var d=a.T.X.V;for(a=a.T.W;b.$;)c=b.ia(c),b=b.$;for(;d.$;)a=d.ia(a),d=d.$;return b===d&&c===a},clone:function(){this.T.W||Xa(this);if(this.T.ha)return this.T.count.value+=1,this;var a=db,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.T;a=a(c.call(b,d,{T:{value:{count:e.count,fa:e.fa,ha:e.ha,W:e.W,X:e.X,Y:e.Y,aa:e.aa}}}));a.T.count.value+=1;a.T.fa=!1;return a},
["delete"](){this.T.W||Xa(this);if(this.T.fa&&!this.T.ha)throw new Q("Object already scheduled for deletion");Za(this);var a=this.T;--a.count.value;0===a.count.value&&(a.Y?a.aa.da(a.Y):a.X.V.da(a.W));this.T.ha||(this.T.Y=void 0,this.T.W=void 0)},isDeleted:function(){return!this.T.W},deleteLater:function(){this.T.W||Xa(this);if(this.T.fa&&!this.T.ha)throw new Q("Object already scheduled for deletion");R.push(this);1===R.length&&S&&S(bb);this.T.fa=!0;return this}});k.getInheritedInstanceCount=()=>Object.keys(T).length;
k.getLiveInheritedInstances=()=>{var a=[],b;for(b in T)T.hasOwnProperty(b)&&a.push(T[b]);return a};k.flushPendingDeletes=bb;k.setDelayFunction=a=>{S=a;R.length&&S&&S(bb)};
Object.assign(qb.prototype,{wa(a){this.ra&&(a=this.ra(a));return a},pa(a){this.da?.(a)},argPackAdvance:8,readValueFromPointer:J,fromWireType:function(a){function b(){return this.la?eb(this.V.ga,{X:this.Ca,W:c,aa:this,Y:a}):eb(this.V.ga,{X:this,W:a})}var c=this.wa(a);if(!c)return this.pa(a),null;var d=cb(this.V,c);if(void 0!==d){if(0===d.T.count.value)return d.T.W=c,d.T.Y=a,d.clone();d=d.clone();this.pa(a);return d}d=this.V.va(c);d=ab[d];if(!d)return b.call(this);d=this.ka?d.sa:d.pointerType;var e=
$a(c,this.V,d.V);return null===e?b.call(this):this.la?eb(d.V.ga,{X:d,W:e,aa:this,Y:a}):eb(d.V.ga,{X:d,W:e})}});xb=k.UnboundTypeError=((a,b)=>{var c=gb(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
X.push(0,1,void 0,1,null,1,!0,1,!1,1);k.count_emval_handles=()=>X.length/2-5-Hb.length;
var kc={I:(a,b,c,d)=>{pa(`Assertion failed: ${a?H(z,a):""}, at: `+[b?b?H(z,b):"":"unknown filename",c,d?d?H(z,d):"":"unknown function"])},u:(a,b,c)=>{var d=new Na(a);D[d.W+16>>2]=0;D[d.W+4>>2]=b;D[d.W+8>>2]=c;Oa=a;Pa++;throw Oa;},y:a=>{var b=Ra[a];delete Ra[a];var c=b.na,d=b.da,e=b.qa,f=e.map(h=>h.za).concat(e.map(h=>h.Ga));O([a],f,h=>{var g={};e.forEach((m,l)=>{var n=h[l],q=m.xa,u=m.ya,x=h[l+e.length],v=m.Fa,B=m.Ha;g[m.ua]={read:I=>n.fromWireType(q(u,I)),write:(I,ca)=>{var y=[];v(B,I,x.toWireType(y,
ca));Sa(y)}}});return[{name:b.name,fromWireType:m=>{var l={},n;for(n in g)l[n]=g[n].read(m);d(m);return l},toWireType:(m,l)=>{for(var n in g)if(!(n in l))throw new TypeError(`Missing field: "${n}"`);var q=c();for(n in g)g[n].write(q,l[n]);null!==m&&m.push(d,q);return q},argPackAdvance:8,readValueFromPointer:J,ba:d}]})},C:()=>{},G:(a,b,c,d)=>{b=P(b);N(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(z[e])},
ba:null})},w:(a,b,c,d,e,f,h,g,m,l,n,q,u)=>{n=P(n);f=V(e,f);g&&=V(h,g);l&&=V(m,l);u=V(q,u);var x=jb(n);ib(x,function(){Ab(`Cannot construct ${n} due to unbound types`,[d])});O([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var B=v.V;var I=B.ga}else I=fb.prototype;v=gb(n,function(...Qa){if(Object.getPrototypeOf(this)!==ca)throw new Q("Use 'new' to construct "+n);if(void 0===y.ea)throw new Q(n+" has no accessible constructor");var Gb=y.ea[Qa.length];if(void 0===Gb)throw new Q(`Tried to invoke ctor of ${n} with invalid number of parameters (${Qa.length}) - expected (${Object.keys(y.ea).toString()}) parameters instead!`);
return Gb.apply(this,Qa)});var ca=Object.create(I,{constructor:{value:v}});v.prototype=ca;var y=new kb(n,v,ca,u,B,f,g,l);if(y.$){var da;(da=y.$).oa??(da.oa=[]);y.$.oa.push(y)}B=new qb(n,y,!0,!1,!1);da=new qb(n+"*",y,!1,!1,!1);I=new qb(n+" const*",y,!1,!0,!1);ab[a]={pointerType:da,sa:I};rb(x,v);return[B,da,I]})},v:(a,b,c,d,e,f)=>{var h=Bb(b,c);e=V(d,e);O([],[a],g=>{g=g[0];var m=`constructor ${g.name}`;void 0===g.V.ea&&(g.V.ea=[]);if(void 0!==g.V.ea[b-1])throw new Q(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${g.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);g.V.ea[b-1]=()=>{Ab(`Cannot construct ${g.name} due to unbound types`,h)};O([],h,l=>{l.splice(1,0,null);g.V.ea[b-1]=Eb(m,l,null,e,f);return[]});return[]})},e:(a,b,c,d,e,f,h,g,m)=>{var l=Bb(c,d);b=P(b);b=Fb(b);f=V(e,f);O([],[a],n=>{function q(){Ab(`Cannot call ${u} due to unbound types`,l)}n=n[0];var u=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);g&&n.V.Da.push(b);
var x=n.V.ga,v=x[b];void 0===v||void 0===v.Z&&v.className!==n.name&&v.ja===c-2?(q.ja=c-2,q.className=n.name,x[b]=q):(hb(x,b,u),x[b].Z[c-2]=q);O([],l,B=>{B=Eb(u,B,n,f,h,m);void 0===x[b].Z?(B.ja=c-2,x[b]=B):x[b].Z[c-2]=B;return[]});return[]})},F:a=>N(a,Jb),s:(a,b,c)=>{b=P(b);N(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Kb(b,c),ba:null})},x:(a,b,c,d,e,f,h)=>{var g=Bb(b,c);a=P(a);a=Fb(a);e=V(d,e);ib(a,function(){Ab(`Cannot call ${a} due to unbound types`,g)},
b-1);O([],g,m=>{m=[m[0],null].concat(m.slice(1));rb(a,Eb(a,m,null,e,f,h),b-1);return[]})},f:(a,b,c,d,e)=>{b=P(b);-1===e&&(e=4294967295);e=g=>g;if(0===d){var f=32-8*c;e=g=>g<<f>>>f}var h=b.includes("unsigned")?function(g,m){return m>>>0}:function(g,m){return m};N(a,{name:b,fromWireType:e,toWireType:h,argPackAdvance:8,readValueFromPointer:Lb(b,c,0!==d),ba:null})},b:(a,b,c)=>{function d(f){return new e(sa.buffer,D[f+4>>2],D[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,
Float32Array,Float64Array][b];c=P(c);N(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Aa:!0})},r:(a,b)=>{b=P(b);var c="std::string"===b;N(a,{name:b,fromWireType:function(d){var e=D[d>>2],f=d+4;if(c)for(var h=f,g=0;g<=e;++g){var m=f+g;if(g==e||0==z[m]){h=h?H(z,h,m-h):"";if(void 0===l)var l=h;else l+=String.fromCharCode(0),l+=h;h=m+1}}else{l=Array(e);for(g=0;g<e;++g)l[g]=String.fromCharCode(z[f+g]);l=l.join("")}W(d);return l},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=
new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new Q("Cannot pass non-string to std::string");var h=c&&f?Nb(e):e.length;var g=jc(4+h+1),m=g+4;D[g>>2]=h;if(c&&f)Mb(e,m,h+1);else if(f)for(f=0;f<h;++f){var l=e.charCodeAt(f);if(255<l)throw W(m),new Q("String has UTF-16 code units that do not fit in 8 bits");z[m+f]=l}else for(f=0;f<h;++f)z[m+f]=e[f];null!==d&&d.push(W,g);return g},argPackAdvance:8,readValueFromPointer:J,
ba(d){W(d)}})},o:(a,b,c)=>{c=P(c);if(2===b){var d=Pb;var e=Qb;var f=Rb;var h=g=>ta[g>>1]}else 4===b&&(d=Sb,e=Tb,f=Ub,h=g=>D[g>>2]);N(a,{name:c,fromWireType:g=>{for(var m=D[g>>2],l,n=g+4,q=0;q<=m;++q){var u=g+4+q*b;if(q==m||0==h(u))n=d(n,u-n),void 0===l?l=n:(l+=String.fromCharCode(0),l+=n),n=u+b}W(g);return l},toWireType:(g,m)=>{if("string"!=typeof m)throw new Q(`Cannot pass non-string to C++ string type ${c}`);var l=f(m),n=jc(4+l+b);D[n>>2]=l/b;e(m,n+4,l+b);null!==g&&g.push(W,n);return n},argPackAdvance:8,
readValueFromPointer:J,ba(g){W(g)}})},z:(a,b,c,d,e,f)=>{Ra[a]={name:P(b),na:V(c,d),da:V(e,f),qa:[]}},h:(a,b,c,d,e,f,h,g,m,l)=>{Ra[a].qa.push({ua:P(b),za:c,xa:V(d,e),ya:f,Ga:h,Fa:V(g,m),Ha:l})},H:(a,b)=>{b=P(b);N(a,{Ba:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},k:(a,b,c)=>{a=Y(a);b=Vb(b,"emval::as");return Wb(b,c,a)},m:(a,b,c,d)=>{a=Xb[a];b=Y(b);return a(null,b,c,d)},t:(a,b,c,d,e)=>{a=Xb[a];b=Y(b);c=Zb(c);return a(b,b[c],d,e)},a:Ib,n:a=>{if(0===a)return U($b());a=Zb(a);return U($b()[a])},
j:(a,b,c)=>{b=bc(a,b);var d=b.shift();a--;var e="return function (obj, func, destructorsRef, args) {\n",f=0,h=[];0===c&&h.push("obj");for(var g=["retType"],m=[d],l=0;l<a;++l)h.push("arg"+l),g.push("argType"+l),m.push(b[l]),e+=`  var arg${l} = argType${l}.readValueFromPointer(args${f?"+"+f:""});\n`,f+=b[l].argPackAdvance;e+=`  var rv = ${1===c?"new func":"func.call"}(${h.join(", ")});\n`;d.Ba||(g.push("emval_returnValue"),m.push(Wb),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");
g.push(e+"};\n");a=Db(g)(...m);c=`methodCaller<(${b.map(n=>n.name).join(", ")}) => ${d.name}>`;return ac(gb(c,a))},g:(a,b)=>{a=Y(a);b=Y(b);return U(a[b])},d:a=>{9<a&&(X[a+1]+=1)},l:a=>U(Zb(a)),B:()=>U({}),c:a=>{var b=Y(a);Sa(b);Ib(a)},A:(a,b,c)=>{a=Y(a);b=Y(b);c=Y(c);a[b]=c},i:(a,b)=>{a=Vb(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},p:()=>{pa("")},E:(a,b,c)=>z.copyWithin(a,b,b+c),D:a=>{var b=z.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,
a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-qa.buffer.byteLength+65535)/65536;try{qa.grow(e);wa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},q:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var h=D[b>>2],g=D[b+4>>2];b+=8;for(var m=0;m<g;m++){var l=z[h+m],n=cc[a];0===l||10===l?((1===a?oa:t)(H(n,0)),n.length=0):n.push(l)}e+=g}D[d>>2]=e;return 0}},Z=function(){function a(c){Z=c.exports;qa=Z.J;wa();tb=Z.N;ya.unshift(Z.K);E--;k.monitorRunDependencies?.(E);
0==E&&(null!==Ca&&(clearInterval(Ca),Ca=null),F&&(c=F,F=null,c()));return Z}var b={a:kc};E++;k.monitorRunDependencies?.(E);if(k.instantiateWasm)try{return k.instantiateWasm(b,a)}catch(c){t(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Ia(b,function(c){a(c.instance)}).catch(ba);return{}}(),jc=a=>(jc=Z.L)(a),lc=k._main=(a,b)=>(lc=k._main=Z.M)(a,b),yb=a=>(yb=Z.O)(a),W=a=>(W=Z.P)(a),ec=()=>(ec=Z.Q)(),fc=a=>(fc=Z.R)(a),dc=a=>(dc=Z.S)(a);
k.dynCall_jiji=(a,b,c,d,e)=>(k.dynCall_jiji=Z.U)(a,b,c,d,e);k.ccall=gc;k.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?k["_"+a]:(...f)=>gc(a,b,c,f,d)};var mc;F=function nc(){mc||oc();mc||(F=nc)};
function oc(){function a(){if(!mc&&(mc=!0,k.calledRun=!0,!ra)){Ka(ya);Ka(za);aa(k);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(pc){var b=lc;try{var c=b(0,0);La||(k.onExit?.(c),ra=!0);fa(c,new Ja(c))}catch(d){d instanceof Ja||"unwind"==d||fa(1,d)}}if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;)b=k.postRun.shift(),Aa.unshift(b);Ka(Aa)}}if(!(0<E)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Ba();Ka(xa);0<E||(k.setStatus?
(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);a()},1)):a())}}if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();var pc=!0;k.noInitialRun&&(pc=!1);oc();


  return moduleArg.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createModule;
else if (typeof define === 'function' && define['amd'])
  define([], () => createModule);
