"""Embed SPIR-V blobs (compiled into the build tree by slang/build_spirv.py)
into one C++ translation unit for the Vulkan backend's pipeline registry.
Invoked by CMake (SSPLAT_BACKEND=vulkan) at build time. When the content is
unchanged the output's mtime is still refreshed so the driving custom
command's OUTPUT stays newer than its dependencies.

Usage: python3 spirulae_splat/embed_spirv.py <spirv_dir> <out_cpp>
"""

import os
import struct
import sys


def main():
    spirv_dir, out_cpp = sys.argv[1], sys.argv[2]
    blobs = sorted(f for f in os.listdir(spirv_dir) if f.endswith(".spv"))

    lines = [
        "// GENERATED by spirulae_splat/embed_spirv.py -- DO NOT EDIT.",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace backend {",
        "namespace vk {",
        "",
        "struct SpirvBlob { const char* name; const uint32_t* data;"
        " size_t size_bytes; };",
        "",
    ]
    names = []
    for i, fname in enumerate(blobs):
        data = open(os.path.join(spirv_dir, fname), "rb").read()
        assert len(data) % 4 == 0, fname
        words = struct.unpack(f"<{len(data) // 4}I", data)
        name = fname[:-len(".spv")]
        names.append((name, i, len(data)))
        lines.append(f"static const uint32_t _blob{i}[] = {{")
        for off in range(0, len(words), 8):
            chunk = ", ".join(f"0x{w:08x}u" for w in words[off:off + 8])
            lines.append(f"    {chunk},")
        lines.append("};")
    lines.append("")
    lines.append("extern const SpirvBlob g_spirv_blobs[];")
    lines.append("extern const size_t g_spirv_blob_count;")
    lines.append("const SpirvBlob g_spirv_blobs[] = {")
    for name, i, size in names:
        lines.append(f'    {{"{name}", _blob{i}, {size}}},')
    if not names:
        lines.append("    {nullptr, nullptr, 0},  // keep the array non-empty")
    lines.append("};")
    lines.append(f"const size_t g_spirv_blob_count = {len(names)};")
    lines.append("")
    lines.append("}  // namespace vk")
    lines.append("}  // namespace backend")

    text = "\n".join(lines) + "\n"
    if os.path.exists(out_cpp) and open(out_cpp).read() == text:
        os.utime(out_cpp)  # keep the build graph's OUTPUT fresh
        return
    os.makedirs(os.path.dirname(out_cpp), exist_ok=True)
    with open(out_cpp, "w") as f:
        f.write(text)


if __name__ == "__main__":
    main()
