import os
from pathlib import Path
from typing import Tuple, List, Dict, Optional

import re
import itertools


CSRC_DIR = Path("spirulae_splat", "splat", "cuda", "csrc")
DST_DIR = Path("spirulae_splat", "splat", "cuda", "ins")


def extract_kernel_definition(header_src: Path, kernel_name: str):
    header_src = CSRC_DIR / header_src
    src = open(header_src, "r").read()

    pattern = re.compile(
        f"""(void\\s+{kernel_name}(.*?)\\)\\s*;)""",
        re.MULTILINE | re.VERBOSE | re.DOTALL
    )

    matches = pattern.findall(src)
    assert len(matches) == 1, matches

    return matches[0][0]


def write_if_changed(path, new_text):
    old = None
    if os.path.exists(path):
        with open(path, "r") as f:
            old = f.read()
    if old != new_text:
        with open(path, "w") as f:
            f.write(new_text)
        return True
    return False


def generate_kernel_instantiation(
        predix: str,
        template_definition: str,
        map_header: List[Optional[str]],
        maps: List[List[str]],
        includes: List[List[str]],
        _names: set = set()
    ):
    assert len(maps) == len(includes)
    for map, includes in zip(maps, includes):
        definition = "template " + template_definition
        assert len(map) == len(map_header)
        for src, dst in zip(map_header, map):
            if src is not None:
                definition = definition.replace(src, dst)
        template = "<\n    " + ',\n    '.join(map) + "\n>"
        definition = definition.replace('(', template + "(", 1)

        filename = [predix]
        for name in map:
            if '<' in name:
                name = name.replace('<', '_').replace('>', '')
            match = re.search(r'\w+$', name)
            assert match, name
            filename.append(match.group(0))
        filename = '_'.join(filename) + ".cu"

        # shorten filename to avoid exceeding 32k command line length when linking on Windows
        namemap = {
            'PINHOLE': 'P',
            'FISHEYE': 'F',
            'Vanilla3DGS': '3g',
            'Vanilla3DGUT': '3u',
            'SphericalVoronoi3DGUT': 'Sv3u',
        }
        filename = ''.join([
            ''.join([c for c in seg.replace('3D', '3') if c.isupper() or c.isnumeric()]).capitalize() or seg[0]
            if seg not in namemap else namemap[seg]
            for seg in filename.rstrip('.cu').split('_')
        ]) + '.cu'
        assert filename not in _names, "Duplicate file name"  # TODO: append a hash suffix?
        _names.add(filename)

        content = ""
        content += "// This file is auto generated by `generate_kernel_instantiation.py`\n\n"
        content += "#define NO_TORCH\n"
        for include in includes:
            content += f"#include \"{include}\"\n"
        content += "\n"
        content += definition
        content += "\n"

        os.makedirs(DST_DIR, exist_ok=True)
        if write_if_changed(DST_DIR / filename, content):
            print("Generated", filename)


def generate_ProjectionFwd():
    for filename, kernel_filename, prefix, wrapper_name in [
        ("ProjectionFwd.cu", "ProjectionFwd_kernel.cuh", "ProjectionFwd", "projection_fused_fwd_kernel_wrapper"),
        ("ProjectionPackedFwd.cu", "ProjectionPackedFwd_kernel.cuh", "ProjectionPackedMask", "projection_packed_mask_kernel_wrapper"),
        ("ProjectionPackedFwd.cu", "ProjectionPackedFwd_kernel.cuh", "ProjectionPackedFwd", "projection_packed_fwd_kernel_wrapper"),
    ]:
        definition = extract_kernel_definition(filename, wrapper_name)
        map_header = ["typename SplatPrimitive", None]
        map_body = [
            ("Vanilla3DGS", "ssplat::CameraModelType::PINHOLE"),
            ("Vanilla3DGS", "ssplat::CameraModelType::FISHEYE"),
            ("MipSplatting", "ssplat::CameraModelType::PINHOLE"),
            ("MipSplatting", "ssplat::CameraModelType::FISHEYE"),
            ("Vanilla3DGUT", "ssplat::CameraModelType::PINHOLE"),
            ("Vanilla3DGUT", "ssplat::CameraModelType::FISHEYE"),
            # ("SphericalVoronoi3DGUT<2>", "ssplat::CameraModelType::PINHOLE"),
            # ("SphericalVoronoi3DGUT<2>", "ssplat::CameraModelType::FISHEYE"),
            # ("SphericalVoronoi3DGUT<3>", "ssplat::CameraModelType::PINHOLE"),
            # ("SphericalVoronoi3DGUT<3>", "ssplat::CameraModelType::FISHEYE"),
            # ("SphericalVoronoi3DGUT<4>", "ssplat::CameraModelType::PINHOLE"),
            # ("SphericalVoronoi3DGUT<4>", "ssplat::CameraModelType::FISHEYE"),
            # ("SphericalVoronoi3DGUT<5>", "ssplat::CameraModelType::PINHOLE"),
            # ("SphericalVoronoi3DGUT<5>", "ssplat::CameraModelType::FISHEYE"),
            # ("SphericalVoronoi3DGUT<6>", "ssplat::CameraModelType::PINHOLE"),
            # ("SphericalVoronoi3DGUT<6>", "ssplat::CameraModelType::FISHEYE"),
            # ("SphericalVoronoi3DGUT<7>", "ssplat::CameraModelType::PINHOLE"),
            # ("SphericalVoronoi3DGUT<7>", "ssplat::CameraModelType::FISHEYE"),
            # ("SphericalVoronoi3DGUT<8>", "ssplat::CameraModelType::PINHOLE"),
            # ("SphericalVoronoi3DGUT<8>", "ssplat::CameraModelType::FISHEYE"),
            # ("OpaqueTriangle", "ssplat::CameraModelType::PINHOLE"),
            # ("OpaqueTriangle", "ssplat::CameraModelType::FISHEYE"),
            # ("VoxelPrimitive", "ssplat::CameraModelType::PINHOLE"),
            # ("VoxelPrimitive", "ssplat::CameraModelType::FISHEYE"),
        ]
        includes = [("Primitive3DGS.cuh", kernel_filename)] * 4 + \
            [("Primitive3DGUT.cuh", kernel_filename)] * 2 #+ \
            # [("Primitive3DGUT_SV.cuh", kernel_filename)] * 14 + \
            # [("PrimitiveOpaqueTriangle.cuh", kernel_filename)] * 2 + \
            # [("PrimitiveVoxel.cuh", kernel_filename)] * 2

        generate_kernel_instantiation(prefix, definition, map_header, map_body, includes)


def generate_ProjectionBwd():
    definition = extract_kernel_definition("ProjectionBwd.cu", "projection_fused_bwd_kernel_wrapper")
    map_header = ["typename SplatPrimitive", None, None]
    map_body = [
        ("Vanilla3DGS", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("Vanilla3DGS", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("Vanilla3DGS", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::Position"),
        ("Vanilla3DGS", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::Position"),
        ("Vanilla3DGS", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::AllReasonable"),
        ("Vanilla3DGS", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::AllReasonable"),
        ("MipSplatting", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("MipSplatting", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("MipSplatting", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::Position"),
        ("MipSplatting", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::Position"),
        ("MipSplatting", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::AllReasonable"),
        ("MipSplatting", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::AllReasonable"),
        ("Vanilla3DGUT", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("Vanilla3DGUT", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("Vanilla3DGUT", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::Position"),
        ("Vanilla3DGUT", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::Position"),
        ("Vanilla3DGUT", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::AllReasonable"),
        ("Vanilla3DGUT", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::AllReasonable"),
        # ("SphericalVoronoi3DGUT<2>", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<2>", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<3>", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<3>", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<4>", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<4>", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<5>", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<5>", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<6>", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<6>", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<7>", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<7>", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<8>", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        # ("SphericalVoronoi3DGUT<8>", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        # ("OpaqueTriangle", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        # ("OpaqueTriangle", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        # ("VoxelPrimitive", "ssplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        # ("VoxelPrimitive", "ssplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
    ]
    includes = [("Primitive3DGS.cuh", "ProjectionBwd_kernel.cuh")] * 12 + \
        [("Primitive3DGUT.cuh", "ProjectionBwd_kernel.cuh")] * 6 #+ \
        # [("Primitive3DGUT_SV.cuh", "ProjectionBwd_kernel.cuh")] * 14 + \
        # [("PrimitiveOpaqueTriangle.cuh", "ProjectionBwd_kernel.cuh")] * 2 + \
        # [("PrimitiveVoxel.cuh", "ProjectionBwd_kernel.cuh")] * 2

    generate_kernel_instantiation("ProjectionBwd", definition, map_header, map_body, includes)


def generate_RasterizationFwd():
    definition = extract_kernel_definition("RasterizationFwd.cu", "rasterize_to_pixels_fwd_kernel_wrapper")
    map_header = ["typename SplatPrimitive", None]
    map_body = [*itertools.product(
        ["Vanilla3DGS"],
        ["true", "false"],
    )]
    includes = [("Primitive3DGS.cuh", "RasterizationFwd_kernel.cuh")] * 2

    generate_kernel_instantiation("RasterizationFwd", definition, map_header, map_body, includes)


def generate_RasterizationBwd():
    definition = extract_kernel_definition("RasterizationBwd.cu", "rasterize_to_pixels_bwd_kernel_wrapper")
    map_header = ["typename SplatPrimitive", None, None, None]
    map_body = [*itertools.product(
        ["Vanilla3DGS"],
        ["true", "false"],
        ["true", "false"],
        ["true", "false"],
    )]
    includes = [("Primitive3DGS.cuh", "RasterizationBwd_kernel.cuh")] * 8

    generate_kernel_instantiation("RasterizationBwd", definition, map_header, map_body, includes)


def generate_RasterizationEval3DFwd():
    definition = extract_kernel_definition("RasterizationEval3DFwd.cu", "rasterize_to_pixels_eval3d_fwd_kernel_wrapper")
    map_header = ["typename SplatPrimitive", None, None]
    map_body = [
        *itertools.product(
            ["Vanilla3DGUT"],
            ["ssplat::CameraModelType::PINHOLE", "ssplat::CameraModelType::FISHEYE"],
            ["true", "false"],
        ),
        # ("VoxelPrimitive", "ssplat::CameraModelType::PINHOLE", "true", "true"),
        # ("VoxelPrimitive", "ssplat::CameraModelType::FISHEYE", "true", "true"),
    ]
    includes = [("Primitive3DGUT.cuh", "RasterizationEval3DFwd_kernel.cuh")] * 4 #+ \
        # [("Primitive3DGUT_SV.cuh", "RasterizationEval3DFwd_kernel.cuh")] * 0 + \
        # [("PrimitiveVoxel.cuh", "RasterizationEval3DFwd_kernel.cuh")] * 2

    generate_kernel_instantiation("RasterizationEval3DFwd", definition, map_header, map_body, includes)


def generate_RasterizationEval3DBwd():
    definition = extract_kernel_definition("RasterizationEval3DBwd.cu", "rasterize_to_pixels_eval3d_bwd_kernel_wrapper")
    map_header = ["typename SplatPrimitive", None, None, None, None, None]
    map_body = [
        *itertools.product(
            ["Vanilla3DGUT"],
            ["ssplat::CameraModelType::PINHOLE", "ssplat::CameraModelType::FISHEYE"],
            ['true', 'false'],
            ['true', 'false'],
            ['true', 'false'],
            ['true', 'false'],
        ),
        # ("VoxelPrimitive", "ssplat::CameraModelType::PINHOLE", "false", "false", "false", "false"),
        # ("VoxelPrimitive", "ssplat::CameraModelType::PINHOLE", "false", "true", "false", "false"),
        # ("VoxelPrimitive", "ssplat::CameraModelType::FISHEYE", "false", "false", "false", "false"),
        # ("VoxelPrimitive", "ssplat::CameraModelType::FISHEYE", "false", "true", "false", "false"),
    ]
    includes = [("Primitive3DGUT.cuh", "RasterizationEval3DBwd_kernel.cuh")] * 32 #+ \
        # [("Primitive3DGUT_SV.cuh", "RasterizationEval3DBwd_kernel.cuh")] * 0 + \
        # [("PrimitiveVoxel.cuh", "RasterizationEval3DBwd_kernel.cuh")] * 4

    generate_kernel_instantiation("RasterizationEval3DBwd", definition, map_header, map_body, includes)


generate_ProjectionFwd()
generate_ProjectionBwd()
generate_RasterizationFwd()
generate_RasterizationBwd()
generate_RasterizationEval3DFwd()
generate_RasterizationEval3DBwd()
