import os
from pathlib import Path
from typing import Tuple, List, Dict, Optional

import re


CSRC_DIR = Path("spirulae_splat", "splat", "cuda", "csrc")
DST_DIR = Path("spirulae_splat", "splat", "cuda", "csrc", "generated", "kernel_instantiation")


def extract_kernel_definition(header_src: Path, kernel_name: str):
    header_src = CSRC_DIR / header_src
    src = open(header_src, "r").read()

    pattern = re.compile(
        f"""(void\\s+{kernel_name}(.*?)\\)\\s*;)""",
        re.MULTILINE | re.VERBOSE | re.DOTALL
    )

    matches = pattern.findall(src)
    assert len(matches) == 1, matches

    return matches[0][0]


def generate_kernel_instantiation(
        predix: str,
        template_definition: str,
        map_header: List[Optional[str]],
        maps: List[List[str]],
        includes: List[List[str]]
    ):
    assert len(maps) == len(includes)
    for map, includes in zip(maps, includes):
        definition = "template " + template_definition
        assert len(map) == len(map_header)
        for src, dst in zip(map_header, map):
            if src is not None:
                definition = definition.replace(src, dst)
        template = "<\n    " + ',\n    '.join(map) + "\n>"
        definition = definition.replace('(', template + "(", 1)

        filename = [predix]
        for name in map:
            if '<' in name:
                name = name.replace('<', '_').replace('>', '')
            match = re.search(r'\w+$', name)
            assert match, name
            filename.append(match.group(0))
        filename = '_'.join(filename) + ".cu"

        with open(DST_DIR / filename, 'w') as fp:
            fp.write("// This file is auto generated by `generate_kernel_instantiation.py`\n\n")
            fp.write("#define NO_TORCH\n")
            for include in includes:
                fp.write(f"#include \"{include}\"\n")
            fp.write("\n")
            fp.write(definition)
            fp.write("\n")

        print("Generated", filename)


def generate_ProjectionFwd():
    for filename, kernel_filename, prefix, wrapper_name in [
        ("ProjectionFwd.cu", "ProjectionFwd_kernel.cuh", "ProjectionFwd", "projection_fused_fwd_kernel_wrapper"),
        ("ProjectionPackedFwd.cu", "ProjectionPackedFwd_kernel.cuh", "ProjectionPackedMask", "projection_packed_mask_kernel_wrapper"),
        ("ProjectionPackedFwd.cu", "ProjectionPackedFwd_kernel.cuh", "ProjectionPackedFwd", "projection_packed_fwd_kernel_wrapper"),
    ]:
        definition = extract_kernel_definition(filename, wrapper_name)
        map_header = ["typename SplatPrimitive", None]
        map_body = [
            ("Vanilla3DGS", "gsplat::CameraModelType::PINHOLE"),
            ("Vanilla3DGS", "gsplat::CameraModelType::FISHEYE"),
            ("MipSplatting", "gsplat::CameraModelType::PINHOLE"),
            ("MipSplatting", "gsplat::CameraModelType::FISHEYE"),
            ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE"),
            ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE"),
            ("SphericalVoronoi3DGUT<2>", "gsplat::CameraModelType::PINHOLE"),
            ("SphericalVoronoi3DGUT<2>", "gsplat::CameraModelType::FISHEYE"),
            ("SphericalVoronoi3DGUT<3>", "gsplat::CameraModelType::PINHOLE"),
            ("SphericalVoronoi3DGUT<3>", "gsplat::CameraModelType::FISHEYE"),
            ("SphericalVoronoi3DGUT<4>", "gsplat::CameraModelType::PINHOLE"),
            ("SphericalVoronoi3DGUT<4>", "gsplat::CameraModelType::FISHEYE"),
            ("SphericalVoronoi3DGUT<5>", "gsplat::CameraModelType::PINHOLE"),
            ("SphericalVoronoi3DGUT<5>", "gsplat::CameraModelType::FISHEYE"),
            ("SphericalVoronoi3DGUT<6>", "gsplat::CameraModelType::PINHOLE"),
            ("SphericalVoronoi3DGUT<6>", "gsplat::CameraModelType::FISHEYE"),
            ("SphericalVoronoi3DGUT<7>", "gsplat::CameraModelType::PINHOLE"),
            ("SphericalVoronoi3DGUT<7>", "gsplat::CameraModelType::FISHEYE"),
            ("SphericalVoronoi3DGUT<8>", "gsplat::CameraModelType::PINHOLE"),
            ("SphericalVoronoi3DGUT<8>", "gsplat::CameraModelType::FISHEYE"),
            ("OpaqueTriangle", "gsplat::CameraModelType::PINHOLE"),
            ("OpaqueTriangle", "gsplat::CameraModelType::FISHEYE"),
            ("VoxelPrimitive", "gsplat::CameraModelType::PINHOLE"),
            ("VoxelPrimitive", "gsplat::CameraModelType::FISHEYE"),
        ]
        includes = [("Primitive3DGS.cuh", kernel_filename)] * 4 + \
            [("Primitive3DGUT.cuh", kernel_filename)] * 2 + \
            [("Primitive3DGUT_SV.cuh", kernel_filename)] * 14 + \
            [("PrimitiveOpaqueTriangle.cuh", kernel_filename)] * 2 + \
            [("PrimitiveVoxel.cuh", kernel_filename)] * 2

        generate_kernel_instantiation(prefix, definition, map_header, map_body, includes)


def generate_ProjectionBwd():
    definition = extract_kernel_definition("ProjectionBwd.cu", "projection_fused_bwd_kernel_wrapper")
    map_header = ["typename SplatPrimitive", None, None]
    map_body = [
        ("Vanilla3DGS", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("Vanilla3DGS", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("Vanilla3DGS", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::Position"),
        ("Vanilla3DGS", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::Position"),
        ("Vanilla3DGS", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::AllReasonable"),
        ("Vanilla3DGS", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::AllReasonable"),
        ("MipSplatting", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("MipSplatting", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("MipSplatting", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::Position"),
        ("MipSplatting", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::Position"),
        ("MipSplatting", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::AllReasonable"),
        ("MipSplatting", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::AllReasonable"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::Position"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::Position"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::AllReasonable"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::AllReasonable"),
        ("SphericalVoronoi3DGUT<2>", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<2>", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<3>", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<3>", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<4>", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<4>", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<5>", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<5>", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<6>", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<6>", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<7>", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<7>", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<8>", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("SphericalVoronoi3DGUT<8>", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("OpaqueTriangle", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("OpaqueTriangle", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
        ("VoxelPrimitive", "gsplat::CameraModelType::PINHOLE", "HessianDiagonalOutputMode::None"),
        ("VoxelPrimitive", "gsplat::CameraModelType::FISHEYE", "HessianDiagonalOutputMode::None"),
    ]
    includes = [("Primitive3DGS.cuh", "ProjectionBwd_kernel.cuh")] * 12 + \
        [("Primitive3DGUT.cuh", "ProjectionBwd_kernel.cuh")] * 6 + \
        [("Primitive3DGUT_SV.cuh", "ProjectionBwd_kernel.cuh")] * 14 + \
        [("PrimitiveOpaqueTriangle.cuh", "ProjectionBwd_kernel.cuh")] * 2 + \
        [("PrimitiveVoxel.cuh", "ProjectionBwd_kernel.cuh")] * 2

    generate_kernel_instantiation("ProjectionBwd", definition, map_header, map_body, includes)


def generate_RasterizationFwd():
    definition = extract_kernel_definition("RasterizationFwd.cu", "rasterize_to_pixels_fwd_kernel_wrapper")
    map_header = ["typename SplatPrimitive"]
    map_body = [
        ("Vanilla3DGS",),
        # ("MipSplatting",),
    ]
    includes = [("Primitive3DGS.cuh", "RasterizationFwd_kernel.cuh")] * 1

    generate_kernel_instantiation("RasterizationFwd", definition, map_header, map_body, includes)


def generate_RasterizationBwd():
    definition = extract_kernel_definition("RasterizationBwd.cu", "rasterize_to_pixels_bwd_kernel_wrapper")
    map_header = ["typename SplatPrimitive", None, None]
    map_body = [
        ("Vanilla3DGS", "false", "false"),
        ("Vanilla3DGS", "false", "true"),
        ("Vanilla3DGS", "true", "true"),
        # ("MipSplatting", "false", "false"),
        # ("MipSplatting", "false", "true"),
        # ("MipSplatting", "true", "true"),
    ]
    includes = [("Primitive3DGS.cuh", "RasterizationBwd_kernel.cuh")] * 3

    generate_kernel_instantiation("RasterizationBwd", definition, map_header, map_body, includes)


def generate_RasterizationEval3DFwd():
    definition = extract_kernel_definition("RasterizationEval3DFwd.cu", "rasterize_to_pixels_eval3d_fwd_kernel_wrapper")
    map_header = ["typename SplatPrimitive", None, None, None]
    map_body = [
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "false", "false"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "true", "false"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "false", "false"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "true", "false"),
        # ("SphericalVoronoi3DGUT_Default", "gsplat::CameraModelType::PINHOLE", "false", "false"),
        # ("SphericalVoronoi3DGUT_Default", "gsplat::CameraModelType::PINHOLE", "true", "false"),
        # ("SphericalVoronoi3DGUT_Default", "gsplat::CameraModelType::FISHEYE", "false", "false"),
        # ("SphericalVoronoi3DGUT_Default", "gsplat::CameraModelType::FISHEYE", "true", "false"),
        ("VoxelPrimitive", "gsplat::CameraModelType::PINHOLE", "true", "true"),
        ("VoxelPrimitive", "gsplat::CameraModelType::FISHEYE", "true", "true"),
    ]
    includes = [("Primitive3DGUT.cuh", "RasterizationEval3DFwd_kernel.cuh")] * 4 + \
        [("Primitive3DGUT_SV.cuh", "RasterizationEval3DFwd_kernel.cuh")] * 0 + \
        [("PrimitiveVoxel.cuh", "RasterizationEval3DFwd_kernel.cuh")] * 2

    generate_kernel_instantiation("RasterizationEval3DFwd", definition, map_header, map_body, includes)


def generate_RasterizationEval3DBwd():
    definition = extract_kernel_definition("RasterizationEval3DBwd.cu", "rasterize_to_pixels_eval3d_bwd_kernel_wrapper")
    map_header = ["typename SplatPrimitive", None, None, None, None]
    map_body = [
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "false", "false", "false"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "false", "true", "false"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "true", "false", "false"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "true", "true", "false"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "false", "false", "false"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "false", "true", "false"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "true", "false", "false"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "true", "true", "false"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "false", "false", "true"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "false", "true", "true"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "true", "false", "true"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::PINHOLE", "true", "true", "true"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "false", "false", "true"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "false", "true", "true"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "true", "false", "true"),
        ("Vanilla3DGUT", "gsplat::CameraModelType::FISHEYE", "true", "true", "true"),
        # ("SphericalVoronoi3DGUT_Default", "gsplat::CameraModelType::PINHOLE", "false", "false", "false"),
        # ("SphericalVoronoi3DGUT_Default", "gsplat::CameraModelType::PINHOLE", "false", "true", "false"),
        # ("SphericalVoronoi3DGUT_Default", "gsplat::CameraModelType::PINHOLE", "true", "false", "false"),
        # ("SphericalVoronoi3DGUT_Default", "gsplat::CameraModelType::PINHOLE", "true", "true", "false"),
        # ("SphericalVoronoi3DGUT_Default", "gsplat::CameraModelType::FISHEYE", "false", "false", "false"),
        # ("SphericalVoronoi3DGUT_Default", "gsplat::CameraModelType::FISHEYE", "false", "true", "false"),
        # ("SphericalVoronoi3DGUT_Default", "gsplat::CameraModelType::FISHEYE", "true", "false", "false"),
        # ("SphericalVoronoi3DGUT_Default", "gsplat::CameraModelType::FISHEYE", "true", "true", "false"),
        ("VoxelPrimitive", "gsplat::CameraModelType::PINHOLE", "false", "false", "false"),
        ("VoxelPrimitive", "gsplat::CameraModelType::PINHOLE", "false", "true", "false"),
        ("VoxelPrimitive", "gsplat::CameraModelType::FISHEYE", "false", "false", "false"),
        ("VoxelPrimitive", "gsplat::CameraModelType::FISHEYE", "false", "true", "false"),
    ]
    includes = [("Primitive3DGUT.cuh", "RasterizationEval3DBwd_kernel.cuh")] * 16 + \
        [("Primitive3DGUT_SV.cuh", "RasterizationEval3DBwd_kernel.cuh")] * 0 + \
        [("PrimitiveVoxel.cuh", "RasterizationEval3DBwd_kernel.cuh")] * 4

    generate_kernel_instantiation("RasterizationEval3DBwd", definition, map_header, map_body, includes)


generate_ProjectionFwd()
generate_ProjectionBwd()
generate_RasterizationFwd()
generate_RasterizationBwd()
generate_RasterizationEval3DFwd()
generate_RasterizationEval3DBwd()
