/*
 * MeshExport.cpp -- see MeshExport.h.
 *
 * All writers emit files by hand (PLY/OBJ/GLTF JSON/GLB container); the only
 * shared code is the vendored stb_image_write PNG encoder.
 */

#include "MeshExport.h"

#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <functional>
#include <stdexcept>
#include <unordered_map>
#include <unordered_set>

#include "external/stb_image_write.h"

namespace meshing {

namespace {

// ---------------------------------------------------------------------------
// Small shared helpers
// ---------------------------------------------------------------------------

[[noreturn]] void fail(const std::string& msg) { throw std::runtime_error("mesh export: " + msg); }

std::string basename_of(const std::string& path) {
    size_t p = path.find_last_of("/\\");
    return p == std::string::npos ? path : path.substr(p + 1);
}

std::ofstream open_binary(const std::string& path) {
    std::ofstream f(path, std::ios::binary);
    if (!f) fail("cannot open " + path + " for writing");
    return f;
}

// sRGB (display, [0,1]) -> linear. glTF COLOR_0 is a linear multiplier, so
// the baked display-referred colors are linearized on export.
inline float srgb_to_linear(float c) {
    return c <= 0.04045f ? c / 12.92f : std::pow((c + 0.055f) / 1.055f, 2.4f);
}

void write_tex_file(const MeshData& mesh, const MeshFormatSpec& spec,
                    const std::string& path) {
    int ok = spec.jpeg
        ? stbi_write_jpg(path.c_str(), mesh.tex_width, mesh.tex_height, 3,
                         mesh.texture.data(), spec.quality)
        : stbi_write_png(path.c_str(), mesh.tex_width, mesh.tex_height, 3,
                         mesh.texture.data(), mesh.tex_width * 3);
    if (!ok) fail("failed to write " + path);
}

std::vector<unsigned char> encode_tex_mem(const MeshData& mesh,
                                          const MeshFormatSpec& spec) {
    std::vector<unsigned char> out;
    out.reserve((size_t)mesh.tex_width * mesh.tex_height);  // rough
    auto sink = [](void* ctx, void* data, int size) {
        auto* v = static_cast<std::vector<unsigned char>*>(ctx);
        v->insert(v->end(), (unsigned char*)data, (unsigned char*)data + size);
    };
    int ok = spec.jpeg
        ? stbi_write_jpg_to_func(sink, &out, mesh.tex_width, mesh.tex_height, 3,
                                 mesh.texture.data(), spec.quality)
        : stbi_write_png_to_func(sink, &out, mesh.tex_width, mesh.tex_height, 3,
                                 mesh.texture.data(), mesh.tex_width * 3);
    if (!ok) fail(std::string("failed to encode texture ") + spec.tex_ext());
    return out;
}

void check_mesh(const MeshData& mesh, MeshColorMode mode) {
    if (mode == MeshColorMode::Vertex && mesh.C.size() != mesh.V.size())
        fail("vertex-color mode but mesh has no per-vertex colors");
    if (mode == MeshColorMode::Texture) {
        if (mesh.UV.size() != mesh.V.size())
            fail("texture mode but mesh has no per-vertex UVs");
        if (mesh.tex_width <= 0 || mesh.tex_height <= 0 ||
            mesh.texture.size() != (size_t)mesh.tex_width * mesh.tex_height * 3)
            fail("texture mode but the baked texture is missing/mis-sized");
    }
}

// ---------------------------------------------------------------------------
// PLY (binary little-endian)
// ---------------------------------------------------------------------------

void write_ply_file(const MeshData& mesh, MeshColorMode mode,
                    const std::string& base) {
    const bool has_n = mesh.N.size() == mesh.V.size();
    const bool has_c = mode == MeshColorMode::Vertex;
    auto f = open_binary(base + ".ply");
    f << "ply\nformat binary_little_endian 1.0\n";
    f << "comment generated by spirulae-splat meshing\n";
    f << "element vertex " << mesh.V.size() << "\n";
    f << "property float x\nproperty float y\nproperty float z\n";
    if (has_n)
        f << "property float nx\nproperty float ny\nproperty float nz\n";
    if (has_c)
        f << "property uchar red\nproperty uchar green\nproperty uchar blue\n";
    f << "element face " << mesh.F.size() << "\n";
    f << "property list uchar int vertex_indices\n";
    f << "end_header\n";

    // row-buffered writes (a row is at most 6 floats + 3 bytes)
    std::vector<char> buf;
    buf.reserve(1 << 20);
    auto put = [&](const void* p, size_t n) {
        const char* c = (const char*)p;
        buf.insert(buf.end(), c, c + n);
        if (buf.size() > (1 << 20) - 64) { f.write(buf.data(), buf.size()); buf.clear(); }
    };
    for (size_t i = 0; i < mesh.V.size(); ++i) {
        put(mesh.V[i].data(), 12);
        if (has_n) put(mesh.N[i].data(), 12);
        if (has_c) put(mesh.C[i].data(), 3);
    }
    for (const auto& t : mesh.F) {
        unsigned char n3 = 3;
        put(&n3, 1);
        int idx[3] = {t[0], t[1], t[2]};
        put(idx, sizeof idx);
    }
    f.write(buf.data(), buf.size());
    if (!f) fail("write failed for " + base + ".ply");
}

// ---------------------------------------------------------------------------
// OBJ (+ MTL + PNG when textured)
// ---------------------------------------------------------------------------

void write_obj_file(const MeshData& mesh, MeshColorMode mode,
                    const MeshFormatSpec& spec, const std::string& base) {
    const bool has_uv = mode == MeshColorMode::Texture;
    const bool has_n = mesh.N.size() == mesh.V.size();
    const std::string name = basename_of(base);

    FILE* f = std::fopen((base + ".obj").c_str(), "w");
    if (!f) fail("cannot open " + base + ".obj for writing");
    std::vector<char> iobuf(1 << 20);
    setvbuf(f, iobuf.data(), _IOFBF, iobuf.size());

    std::fprintf(f, "# generated by spirulae-splat meshing\n");
    if (has_uv) std::fprintf(f, "mtllib %s.mtl\n", name.c_str());
    std::fprintf(f, "o %s\n", name.c_str());
    for (const auto& v : mesh.V)
        std::fprintf(f, "v %.7g %.7g %.7g\n", v[0], v[1], v[2]);
    if (has_uv)
        for (const auto& uv : mesh.UV)     // OBJ v runs bottom-up
            std::fprintf(f, "vt %.7g %.7g\n", uv[0], 1.0f - uv[1]);
    if (has_n)
        for (const auto& n : mesh.N)
            std::fprintf(f, "vn %.5g %.5g %.5g\n", n[0], n[1], n[2]);
    if (has_uv) std::fprintf(f, "usemtl %s\n", name.c_str());
    for (const auto& t : mesh.F) {
        int a = t[0] + 1, b = t[1] + 1, c = t[2] + 1;
        if (has_uv && has_n)
            std::fprintf(f, "f %d/%d/%d %d/%d/%d %d/%d/%d\n", a,a,a, b,b,b, c,c,c);
        else if (has_uv)
            std::fprintf(f, "f %d/%d %d/%d %d/%d\n", a,a, b,b, c,c);
        else if (has_n)
            std::fprintf(f, "f %d//%d %d//%d %d//%d\n", a,a, b,b, c,c);
        else
            std::fprintf(f, "f %d %d %d\n", a, b, c);
    }
    bool ok = !std::ferror(f);
    std::fclose(f);
    if (!ok) fail("write failed for " + base + ".obj");

    if (has_uv) {
        FILE* m = std::fopen((base + ".mtl").c_str(), "w");
        if (!m) fail("cannot open " + base + ".mtl for writing");
        std::fprintf(m,
            "newmtl %s\nKa 1 1 1\nKd 1 1 1\nKs 0 0 0\nd 1\nillum 1\nmap_Kd %s.%s\n",
            name.c_str(), name.c_str(), spec.tex_ext());
        std::fclose(m);
        write_tex_file(mesh, spec, base + "." + spec.tex_ext());
    }
}

// ---------------------------------------------------------------------------
// glTF 2.0 (.gltf JSON + .bin [+ .png], or single-file .glb)
// ---------------------------------------------------------------------------

inline void pad_to_4(std::vector<unsigned char>& v, unsigned char fill) {
    while (v.size() % 4) v.push_back(fill);
}

void append_bytes(std::vector<unsigned char>& v, const void* p, size_t n) {
    const unsigned char* c = (const unsigned char*)p;
    v.insert(v.end(), c, c + n);
}

void write_gltf_file(const MeshData& mesh, MeshColorMode mode,
                     const MeshFormatSpec& spec, const std::string& base,
                     bool glb) {
    const bool has_uv = mode == MeshColorMode::Texture;
    const bool has_c = mode == MeshColorMode::Vertex;
    const bool has_n = mesh.N.size() == mesh.V.size();
    const size_t nv = mesh.V.size(), nf = mesh.F.size();
    const std::string name = basename_of(base);
    // 16-bit indices whenever they fit -- larger viewer compatibility (some
    // WebGL1-era viewers need an extension for 32-bit element indices), and
    // it matches the convention of the Khronos sample models.
    const bool idx16 = nv <= 65535;

    // ---- binary buffer ----
    std::vector<unsigned char> bin;
    bin.reserve(nf * (idx16 ? 6 : 12) +
                nv * (12 + (has_n ? 12 : 0) + (has_c ? 12 : 0) +
                      (has_uv ? 8 : 0)) + 64);
    struct View { size_t off, len; int target; };  // target 0 = none
    std::vector<View> views;
    auto add_view = [&](const void* p, size_t n, int target) -> int {
        pad_to_4(bin, 0);
        views.push_back({bin.size(), n, target});
        append_bytes(bin, p, n);
        return (int)views.size() - 1;
    };

    int view_idx;
    if (idx16) {
        std::vector<uint16_t> idx(nf * 3);
        for (size_t t = 0; t < nf; ++t)
            for (int k = 0; k < 3; ++k) idx[3*t + k] = (uint16_t)mesh.F[t][k];
        view_idx = add_view(idx.data(), idx.size() * 2, 34963);
    } else {
        std::vector<uint32_t> idx(nf * 3);
        for (size_t t = 0; t < nf; ++t)
            for (int k = 0; k < 3; ++k) idx[3*t + k] = (uint32_t)mesh.F[t][k];
        view_idx = add_view(idx.data(), idx.size() * 4, 34963);
    }
    int view_pos = add_view(mesh.V.data(), nv * 12, 34962);
    int view_nrm = -1, view_col = -1, view_uv = -1, view_img = -1;
    if (has_n) view_nrm = add_view(mesh.N.data(), nv * 12, 34962);
    if (has_c) {
        // COLOR_0 as float VEC3 of the LINEARIZED color (glTF colors are
        // linear) -- the most widely supported layout (what the Khronos
        // vertex-color sample uses).
        std::vector<float> col(nv * 3);
        for (size_t i = 0; i < nv; ++i)
            for (int k = 0; k < 3; ++k)
                col[3*i + k] = srgb_to_linear(mesh.C[i][k] / 255.0f);
        view_col = add_view(col.data(), col.size() * 4, 34962);
    }
    if (has_uv) view_uv = add_view(mesh.UV.data(), nv * 8, 34962);

    std::vector<unsigned char> img;
    if (has_uv && glb) {
        img = encode_tex_mem(mesh, spec);
        view_img = add_view(img.data(), img.size(), 0);
    }
    pad_to_4(bin, 0);

    // ---- POSITION min/max (required by the spec) ----
    float mn[3] = {1e30f, 1e30f, 1e30f}, mx[3] = {-1e30f, -1e30f, -1e30f};
    for (const auto& v : mesh.V)
        for (int k = 0; k < 3; ++k) {
            mn[k] = std::min(mn[k], v[k]);
            mx[k] = std::max(mx[k], v[k]);
        }
    if (nv == 0) { for (int k = 0; k < 3; ++k) mn[k] = mx[k] = 0.0f; }

    // ---- JSON ----
    std::string j;
    j.reserve(4096);
    char tmp[1024];
    auto add = [&](const char* fmt, ...) {
        va_list ap;
        va_start(ap, fmt);
        std::vsnprintf(tmp, sizeof tmp, fmt, ap);
        va_end(ap);
        j += tmp;
    };
    // NOTE: no KHR_materials_unlit. Viewers with partial support for the
    // extension were observed rendering the material as plain white; a rough
    // non-metal PBR material displays baked colors acceptably everywhere.
    j += "{\"asset\":{\"version\":\"2.0\",\"generator\":\"spirulae-splat meshing\"},";
    j += "\"scene\":0,\"scenes\":[{\"nodes\":[0]}],";
    add("\"nodes\":[{\"mesh\":0,\"name\":\"%s\"}],", name.c_str());

    // mesh + primitive
    j += "\"meshes\":[{\"primitives\":[{\"attributes\":{";
    int acc = 0;
    int acc_idx = acc++;
    int acc_pos = acc++;
    add("\"POSITION\":%d", acc_pos);
    int acc_nrm = -1, acc_col = -1, acc_uv = -1;
    if (has_n)  { acc_nrm = acc++; add(",\"NORMAL\":%d", acc_nrm); }
    if (has_c)  { acc_col = acc++; add(",\"COLOR_0\":%d", acc_col); }
    if (has_uv) { acc_uv = acc++; add(",\"TEXCOORD_0\":%d", acc_uv); }
    add("},\"indices\":%d,\"material\":0,\"mode\":4}]}],", acc_idx);

    // material
    j += "\"materials\":[{";
    if (has_uv)
        j += "\"pbrMetallicRoughness\":{\"baseColorTexture\":{\"index\":0},"
             "\"metallicFactor\":0,\"roughnessFactor\":1},";
    else
        j += "\"pbrMetallicRoughness\":{\"baseColorFactor\":[1,1,1,1],"
             "\"metallicFactor\":0,\"roughnessFactor\":1},";
    j += "\"doubleSided\":true}],";

    // texture / image / sampler
    if (has_uv) {
        const char* mime = spec.jpeg ? "image/jpeg" : "image/png";
        j += "\"samplers\":[{\"magFilter\":9729,\"minFilter\":9987,"
             "\"wrapS\":33071,\"wrapT\":33071}],";
        j += "\"textures\":[{\"sampler\":0,\"source\":0}],";
        if (glb)
            add("\"images\":[{\"bufferView\":%d,\"mimeType\":\"%s\"}],",
                view_img, mime);
        else
            add("\"images\":[{\"uri\":\"%s.%s\"}],", name.c_str(), spec.tex_ext());
    }

    // accessors
    j += "\"accessors\":[";
    add("{\"bufferView\":%d,\"componentType\":%d,\"count\":%zu,\"type\":\"SCALAR\"}",
        view_idx, idx16 ? 5123 : 5125, nf * 3);
    // %.17g: the validator parses JSON min/max as doubles and compares them
    // against the (float) accessor data widened to double -- 17 significant
    // digits reproduce that double exactly.
    add(",{\"bufferView\":%d,\"componentType\":5126,\"count\":%zu,\"type\":\"VEC3\","
        "\"min\":[%.17g,%.17g,%.17g],\"max\":[%.17g,%.17g,%.17g]}",
        view_pos, nv, mn[0], mn[1], mn[2], mx[0], mx[1], mx[2]);
    if (has_n)
        add(",{\"bufferView\":%d,\"componentType\":5126,\"count\":%zu,\"type\":\"VEC3\"}",
            view_nrm, nv);
    if (has_c)
        add(",{\"bufferView\":%d,\"componentType\":5126,\"count\":%zu,"
            "\"type\":\"VEC3\"}", view_col, nv);
    if (has_uv)
        add(",{\"bufferView\":%d,\"componentType\":5126,\"count\":%zu,\"type\":\"VEC2\"}",
            view_uv, nv);
    j += "],";

    // bufferViews + buffer
    j += "\"bufferViews\":[";
    for (size_t i = 0; i < views.size(); ++i) {
        add("%s{\"buffer\":0,\"byteOffset\":%zu,\"byteLength\":%zu",
            i ? "," : "", views[i].off, views[i].len);
        if (views[i].target) add(",\"target\":%d", views[i].target);
        j += "}";
    }
    j += "],";
    if (glb)
        add("\"buffers\":[{\"byteLength\":%zu}]}", bin.size());
    else
        add("\"buffers\":[{\"uri\":\"%s.bin\",\"byteLength\":%zu}]}", name.c_str(), bin.size());

    // ---- write ----
    if (glb) {
        while (j.size() % 4) j += ' ';
        uint32_t total = 12 + 8 + (uint32_t)j.size() + 8 + (uint32_t)bin.size();
        auto f = open_binary(base + ".glb");
        uint32_t hdr[3] = {0x46546C67u, 2u, total};
        f.write((const char*)hdr, 12);
        uint32_t jc[2] = {(uint32_t)j.size(), 0x4E4F534Au};
        f.write((const char*)jc, 8);
        f.write(j.data(), j.size());
        uint32_t bc[2] = {(uint32_t)bin.size(), 0x004E4942u};
        f.write((const char*)bc, 8);
        f.write((const char*)bin.data(), bin.size());
        if (!f) fail("write failed for " + base + ".glb");
    } else {
        {
            std::ofstream f(base + ".gltf");
            if (!f) fail("cannot open " + base + ".gltf for writing");
            f << j;
            if (!f) fail("write failed for " + base + ".gltf");
        }
        auto f = open_binary(base + ".bin");
        f.write((const char*)bin.data(), bin.size());
        if (!f) fail("write failed for " + base + ".bin");
        if (has_uv) write_tex_file(mesh, spec, base + "." + spec.tex_ext());
    }
}

} // namespace


// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

MeshFormatSpec parse_one_mesh_format(const std::string& token) {
    std::string s = token;
    std::transform(s.begin(), s.end(), s.begin(),
                   [](unsigned char c) { return (char)std::tolower(c); });
    if (!s.empty() && s[0] == '.') s.erase(s.begin());

    MeshFormatSpec spec;
    std::string enc;
    size_t plus = s.find('+');
    if (plus != std::string::npos) {
        enc = s.substr(plus + 1);
        s.resize(plus);
    }
    if (s != "ply" && s != "obj" && s != "gltf" && s != "glb")
        fail("unknown mesh format '" + token + "' (expected ply, obj, gltf, "
             "or glb, optionally with +png / +jpg / +jpeg<quality>)");
    spec.fmt = s;
    if (enc.empty()) return spec;                       // default: PNG

    // split the encoding into name + optional quality digits
    size_t d = enc.find_first_of("0123456789");
    std::string ename = enc.substr(0, d);
    std::string digits = d == std::string::npos ? "" : enc.substr(d);
    if (ename == "png") {
        if (!digits.empty())
            fail("'" + token + "': png takes no quality value");
    } else if (ename == "jpg" || ename == "jpeg") {
        spec.jpeg = true;
        if (!digits.empty()) {
            try { spec.quality = std::stoi(digits); } catch (...) { spec.quality = 0; }
            if (spec.quality < 1 || spec.quality > 100)
                fail("'" + token + "': JPEG quality must be in 1..100");
        }
    } else {
        fail("'" + token + "': unknown texture encoding '+" + enc +
             "' (expected +png, +jpg, or +jpeg<quality>)");
    }
    return spec;
}

std::vector<MeshFormatSpec> parse_mesh_formats(const std::string& csv) {
    std::vector<MeshFormatSpec> out;
    size_t pos = 0;
    while (pos <= csv.size()) {
        size_t comma = csv.find(',', pos);
        std::string tok = csv.substr(
            pos, comma == std::string::npos ? std::string::npos : comma - pos);
        // trim
        while (!tok.empty() && std::isspace((unsigned char)tok.front())) tok.erase(tok.begin());
        while (!tok.empty() && std::isspace((unsigned char)tok.back())) tok.pop_back();
        if (!tok.empty()) {
            MeshFormatSpec spec = parse_one_mesh_format(tok);
            for (const auto& o : out)
                if (o.fmt == spec.fmt)
                    fail("format '" + spec.fmt + "' requested more than once "
                         "(the outputs would overwrite each other)");
            out.push_back(std::move(spec));
        }
        if (comma == std::string::npos) break;
        pos = comma + 1;
    }
    return out;
}

std::string check_export_support(const MeshFormatSpec& spec, MeshColorMode mode) {
    if (spec.fmt == "ply" && mode == MeshColorMode::Texture)
        return "PLY does not support textured meshes; use vertex color "
               "(or export OBJ/GLTF/GLB)";
    if (spec.fmt == "obj" && mode == MeshColorMode::Vertex)
        return "OBJ has no standard per-vertex color; use a texture "
               "(or export PLY/GLTF/GLB)";
    if (spec.jpeg && mode != MeshColorMode::Texture)
        return "'" + spec.token() + "': a texture encoding was given but the "
               "color mode is not 'texture'";
    return "";
}

void write_mesh(const MeshData& mesh, MeshColorMode mode,
                const MeshFormatSpec& spec, const std::string& base_path,
                bool verbose) {
    std::string err = check_export_support(spec, mode);
    if (!err.empty()) fail(err);
    check_mesh(mesh, mode);

    const std::string& fmt = spec.fmt;
    if (fmt == "ply")       write_ply_file(mesh, mode, base_path);
    else if (fmt == "obj")  write_obj_file(mesh, mode, spec, base_path);
    else if (fmt == "gltf") write_gltf_file(mesh, mode, spec, base_path, false);
    else                    write_gltf_file(mesh, mode, spec, base_path, true);

    if (verbose) {
        std::string extra;
        if (fmt == "obj" && mode == MeshColorMode::Texture)
            extra = std::string(" (+ .mtl, .") + spec.tex_ext() + ")";
        else if (fmt == "gltf")
            extra = mode == MeshColorMode::Texture
                ? std::string(" (+ .bin, .") + spec.tex_ext() + ")"
                : std::string(" (+ .bin)");
        printf("[meshing] wrote %s.%s%s: %zu vertices, %zu faces\n",
               base_path.c_str(), fmt.c_str(), extra.c_str(),
               mesh.V.size(), mesh.F.size());
    }
}

void compute_vertex_normals(MeshData& mesh) {
    const size_t nv = mesh.V.size();
    mesh.N.assign(nv, {0.f, 0.f, 0.f});
    for (const auto& t : mesh.F) {
        const auto& a = mesh.V[t[0]];
        const auto& b = mesh.V[t[1]];
        const auto& c = mesh.V[t[2]];
        float e1[3] = {b[0]-a[0], b[1]-a[1], b[2]-a[2]};
        float e2[3] = {c[0]-a[0], c[1]-a[1], c[2]-a[2]};
        // cross product = 2*area-weighted face normal
        float n[3] = {e1[1]*e2[2] - e1[2]*e2[1],
                      e1[2]*e2[0] - e1[0]*e2[2],
                      e1[0]*e2[1] - e1[1]*e2[0]};
        for (int k = 0; k < 3; ++k) {
            mesh.N[t[k]][0] += n[0];
            mesh.N[t[k]][1] += n[1];
            mesh.N[t[k]][2] += n[2];
        }
    }
    for (auto& n : mesh.N) {
        float l = std::sqrt(n[0]*n[0] + n[1]*n[1] + n[2]*n[2]);
        if (l > 1e-20f) { n[0] /= l; n[1] /= l; n[2] /= l; }
        else            { n[0] = 0.f; n[1] = 0.f; n[2] = 1.f; }
    }
}

void print_mesh_stats(const MeshData& mesh) {
    const size_t nv = mesh.V.size(), nf = mesh.F.size();
    if (nf == 0) { printf("[meshing] stats: empty mesh\n"); return; }

    // undirected edge -> (face count, winding balance). For a consistently
    // oriented 2-face edge the two traversals are opposite: balance == 0.
    std::unordered_map<int64_t, std::pair<int,int>> edges;
    edges.reserve(nf * 3);
    const int64_t P = (int64_t)nv;
    for (const auto& f : mesh.F)
        for (int k = 0; k < 3; ++k) {
            int a = f[k], b = f[(k+1)%3];
            int64_t lo = a < b ? a : b, hi = a < b ? b : a;
            auto& e = edges[lo * P + hi];
            e.first += 1;
            e.second += (a < b) ? 1 : -1;
        }
    long n_bnd = 0, n_nonmanif = 0, n_misoriented = 0;
    for (const auto& kv : edges) {
        if (kv.second.first == 1) ++n_bnd;
        else if (kv.second.first > 2) ++n_nonmanif;
        else if (kv.second.second != 0) ++n_misoriented;
    }

    // duplicate faces
    std::unordered_set<int64_t> seen;
    seen.reserve(nf * 2);
    long n_dup = 0;
    for (const auto& f : mesh.F) {
        int a = f[0], b = f[1], c = f[2];
        if (a > b) std::swap(a, b);
        if (b > c) std::swap(b, c);
        if (a > b) std::swap(a, b);
        if (!seen.insert((int64_t)a * P * P + (int64_t)b * P + c).second) ++n_dup;
    }

    // connected components (union-find over vertices)
    std::vector<int> parent(nv);
    for (size_t i = 0; i < nv; ++i) parent[i] = (int)i;
    std::function<int(int)> find = [&](int x) {
        while (parent[x] != x) { parent[x] = parent[parent[x]]; x = parent[x]; }
        return x;
    };
    for (const auto& f : mesh.F) {
        int a = find(f[0]), b = find(f[1]), c = find(f[2]);
        if (a != b) parent[a] = b;
        b = find(b);
        if (b != c) parent[b] = c;
    }
    std::unordered_set<int> roots;
    for (const auto& f : mesh.F) roots.insert(find(f[0]));

    // triangle min-angle stats
    long n_deg5 = 0, n_deg15 = 0;
    double min_angle = 180.0;
    for (const auto& f : mesh.F) {
        const auto& A = mesh.V[f[0]];
        const auto& B = mesh.V[f[1]];
        const auto& C2 = mesh.V[f[2]];
        auto d2 = [](const std::array<float,3>& p, const std::array<float,3>& q) {
            double dx = p[0]-q[0], dy = p[1]-q[1], dz = p[2]-q[2];
            return dx*dx + dy*dy + dz*dz;
        };
        double la = d2(B, C2), lb = d2(C2, A), lc = d2(A, B);
        auto ang = [](double opp, double s1, double s2) {
            double dn = 2.0 * std::sqrt(s1 * s2);
            double c = dn > 1e-300 ? (s1 + s2 - opp) / dn : 1.0;
            return std::acos(std::min(std::max(c, -1.0), 1.0)) * 57.29577951308232;
        };
        double m = std::min(ang(la, lb, lc), std::min(ang(lb, lc, la), ang(lc, la, lb)));
        min_angle = std::min(min_angle, m);
        if (m < 5.0) ++n_deg5;
        if (m < 15.0) ++n_deg15;
    }

    printf("[meshing] stats: %zu verts, %zu faces, %zu components; "
           "edges: %ld boundary, %ld non-manifold, %ld mis-oriented; "
           "%ld duplicate faces; min angle %.2f deg (%ld faces < 5, %ld < 15)\n",
           nv, nf, roots.size(), n_bnd, n_nonmanif, n_misoriented,
           n_dup, min_angle, n_deg5, n_deg15);
}

} // namespace meshing
