#!/usr/bin/env python3
"""Generate the EXR conformance corpus src/core/tests/exr_decode.cpp reads.

Dev-time only, and the output is deliberately not committed: it is ~4 MB of
binary and it must be regenerated by OpenEXR itself, which is the whole point
-- every case ships the reference decode OpenEXR produced for it, so the C++
test needs no python and no OpenEXR at run time.

    pip install OpenEXR
    python tools/gen_exr_cases.py /tmp/exr_cases
    ./build/exr_decode /tmp/exr_cases

Cases whose name starts with `err_` must be REFUSED by the reader; every other
case must decode bit-exactly to its .f32 companion.
"""
import os
import struct
import sys

import numpy as np
import OpenEXR

C = OpenEXR
COMP = {
    "none": C.NO_COMPRESSION, "rle": C.RLE_COMPRESSION, "zips": C.ZIPS_COMPRESSION,
    "zip": C.ZIP_COMPRESSION, "piz": C.PIZ_COMPRESSION, "pxr24": C.PXR24_COMPRESSION,
    "b44": C.B44_COMPRESSION, "b44a": C.B44A_COMPRESSION,
    "dwaa": C.DWAA_COMPRESSION, "dwab": C.DWAB_COMPRESSION,
}


def img(h, w, seed=0):
    """Smooth structure (so PIZ and B44 do real work), noise, and a patch above
    1.0 (so the half exponent range is exercised)."""
    rng = np.random.default_rng(seed)
    y, x = np.mgrid[0:h, 0:w]
    base = np.sin(x / 7.0) * np.cos(y / 5.0) * 0.5 + 0.5
    out = []
    for k in range(3):
        v = base * (0.4 + 0.3 * k) + rng.random((h, w)) * 0.05
        v[h // 3:h // 3 + 4, w // 4:w // 4 + 9] = 12.5 * (k + 1)
        out.append(v.astype(np.float32))
    return out


def rgb(h, w, dtype="float16", seed=0):
    r, g, b = img(h, w, seed)
    return {"R": r.astype(dtype), "G": g.astype(dtype), "B": b.astype(dtype)}


def reference(path):
    """What OpenEXR itself decodes, in display-window space. The legacy
    InputFile API is the reference: the new one mis-combines channels whose
    pixel types differ."""
    import Imath
    FLOAT = Imath.PixelType(Imath.PixelType.FLOAT)
    with OpenEXR.File(path) as probe:
        multipart = len(probe.parts) > 1
    if multipart:
        with OpenEXR.File(path) as f:
            part = next(p for p in f.parts
                        if {"R", "G", "B"} <= set(p.channels) or "RGB" in p.channels)
            ch = part.channels
            arr = np.asarray(ch["RGB" if "RGB" in ch else "RGBA"].pixels, np.float32)
            arr = arr[..., :3]
            (dx0, dy0), (dx1, dy1) = part.header["dataWindow"]
            (px0, py0), (px1, py1) = part.header["displayWindow"]
    else:
        f = OpenEXR.InputFile(path)
        hdr = f.header()
        names = list(hdr["channels"].keys())
        pref = ""
        if "R" not in names and "Y" not in names and any("." in n for n in names):
            pref = names[0].rsplit(".", 1)[0] + "."
        dw, pw = hdr["dataWindow"], hdr["displayWindow"]
        dx0, dy0, dx1, dy1 = dw.min.x, dw.min.y, dw.max.x, dw.max.y
        px0, py0, px1, py1 = pw.min.x, pw.min.y, pw.max.x, pw.max.y
        h, w = dy1 - dy0 + 1, dx1 - dx0 + 1

        def rd(n):
            return np.frombuffer(f.channel(n, FLOAT), np.float32).reshape(h, w)

        if pref + "R" in names:
            arr = np.stack([rd(pref + c) for c in "RGB"], -1)
        else:
            y = rd(pref + "Y" if pref + "Y" in names else names[0])
            arr = np.stack([y, y, y], -1)
    W, H = int(px1 - px0 + 1), int(py1 - py0 + 1)
    if (int(dx0), int(dy0), int(dx1), int(dy1)) == (int(px0), int(py0), int(px1), int(py1)):
        return arr
    full = np.zeros((H, W, 3), np.float32)
    full[int(dy0 - py0):int(dy0 - py0) + arr.shape[0],
         int(dx0 - px0):int(dx0 - px0) + arr.shape[1]] = arr
    return full


class Corpus:
    def __init__(self, out):
        self.out = out
        self.rows = []
        os.makedirs(out, exist_ok=True)

    def add(self, name, header, pixels, expect=None):
        path = os.path.join(self.out, name + ".exr")
        OpenEXR.File(header, pixels).write(path)
        self.finish(name, path, expect)

    def finish(self, name, path, expect=None):
        if name.startswith("err_"):
            self.rows.append((name, 0, 0))
            return
        ref = reference(path) if expect is None else expect
        ref.astype(np.float32).tofile(os.path.join(self.out, name + ".f32"))
        self.rows.append((name, ref.shape[1], ref.shape[0]))

    def write_manifest(self):
        with open(os.path.join(self.out, "cases.txt"), "w") as f:
            for name, w, h in sorted(self.rows):
                f.write(f"{name} {w} {h}\n")
        print(f"{len(self.rows)} cases in {self.out}")


# --- hand-built files, for what the OpenEXR python writer will not produce ---

def attr(name, typ, payload):
    return (name.encode() + b"\0" + typ.encode() + b"\0" +
            struct.pack("<i", len(payload)) + payload)


def raw_header(w, h, chans, compression=0, version_flags=0, part_type=None):
    a = b""
    for cname, ptype, xs, ys in chans:
        a += cname.encode() + b"\0" + struct.pack("<iBBBBii", ptype, 0, 0, 0, 0, xs, ys)
    a = attr("channels", "chlist", a + b"\0")
    a += attr("compression", "compression", bytes([compression]))
    a += attr("dataWindow", "box2i", struct.pack("<4i", 0, 0, w - 1, h - 1))
    a += attr("displayWindow", "box2i", struct.pack("<4i", 0, 0, w - 1, h - 1))
    a += attr("lineOrder", "lineOrder", bytes([0]))
    a += attr("pixelAspectRatio", "float", struct.pack("<f", 1.0))
    a += attr("screenWindowCenter", "v2f", struct.pack("<2f", 0.0, 0.0))
    a += attr("screenWindowWidth", "float", struct.pack("<f", 1.0))
    if part_type is not None:
        a += attr("type", "string", part_type.encode())
    return struct.pack("<ii", 20000630, 2 | version_flags) + a + b"\0"


def add_luminance_chroma(corpus, name, w, h):
    """Y plus RY/BY at half resolution. The python binding refuses to write
    channels whose sampling differs, so this file is assembled by hand and its
    reference is the documented reconstruction."""
    rng = np.random.default_rng(4)
    Y = (rng.random((h, w)) * 0.8 + 0.1).astype(np.float16)
    RY = (rng.random(((h + 1) // 2, (w + 1) // 2)) * 0.6 - 0.3).astype(np.float16)
    BY = (rng.random(((h + 1) // 2, (w + 1) // 2)) * 0.6 - 0.3).astype(np.float16)
    hdr = raw_header(w, h, [("BY", 1, 2, 2), ("RY", 1, 2, 2), ("Y", 1, 1, 1)])
    rows = []
    for y in range(h):
        row = BY[y // 2].tobytes() + RY[y // 2].tobytes() if y % 2 == 0 else b""
        rows.append(row + Y[y].tobytes())
    at = len(hdr) + 8 * h
    blob = hdr
    for r in rows:
        blob += struct.pack("<Q", at)
        at += 8 + len(r)
    for y, r in enumerate(rows):
        blob += struct.pack("<ii", y, len(r)) + r
    path = os.path.join(corpus.out, name + ".exr")
    open(path, "wb").write(blob)

    ys = Y.astype(np.float32)
    ry = RY.astype(np.float32)[np.arange(h) // 2][:, np.arange(w) // 2]
    by = BY.astype(np.float32)[np.arange(h) // 2][:, np.arange(w) // 2]
    R = (ry + 1.0) * ys
    B = (by + 1.0) * ys
    G = (ys - R * 0.2126 - B * 0.0722) / 0.7152
    corpus.finish(name, path, np.stack([R, G, B], -1))


def build(out):
    c = Corpus(out)

    for name, comp in COMP.items():
        bad = "err_" if name.startswith("dwa") else ""
        for tag, (h, w) in (("small", (23, 37)), ("big", (77, 129))):
            c.add(f"{bad}half_{name}_{tag}", {"compression": comp}, rgb(h, w))

    for name in ("none", "zip", "piz", "pxr24", "b44"):
        c.add(f"float_{name}", {"compression": COMP[name]}, rgb(45, 61, "float32"))

    for name in ("zip", "piz", "rle"):
        c.add(f"uint_{name}", {"compression": COMP[name]},
              {k: (v * 1000).astype(np.uint32) for k, v in rgb(31, 29, "float32").items()})

    d = rgb(40, 50)
    d["A"] = np.linspace(0, 1, 40 * 50).reshape(40, 50).astype("float16")
    c.add("rgba_zip", {"compression": COMP["zip"]}, d)

    lum = img(40, 50)[0]
    c.add("y_only_zip", {"compression": COMP["zip"]}, {"Y": lum.astype("float16")})
    c.add("single_depth_zip", {"compression": COMP["zip"]}, {"Z": lum.astype("float32")})

    d = rgb(33, 47)
    d["G"] = d["G"].astype("float32")
    c.add("mixed_types_zip", {"compression": COMP["zip"]}, d)

    c.add("layer_one_zip", {"compression": COMP["zip"]},
          {f"diffuse.{k}": v for k, v in rgb(29, 31).items()})
    two = {f"diffuse.{k}": v for k, v in rgb(29, 31).items()}
    two.update({f"specular.{k}": v for k, v in rgb(29, 31, seed=3).items()})
    c.add("err_layer_two_zip", {"compression": COMP["zip"]}, two)

    for tag, mode, comp in (("one", C.ONE_LEVEL, "zip"), ("one_piz", C.ONE_LEVEL, "piz")):
        t = OpenEXR.TileDescription()
        t.xSize, t.ySize, t.mode = 16, 16, mode
        c.add(f"tiled_{tag}", {"compression": COMP[comp], "type": OpenEXR.tiledimage,
                               "tiles": t}, rgb(70, 90))

    c.add("datawindow_zip", {
        "compression": COMP["zip"],
        "dataWindow": (np.array([3, 2], "int32"), np.array([52, 41], "int32")),
        "displayWindow": (np.array([0, 0], "int32"), np.array([59, 49], "int32")),
    }, rgb(40, 50))
    c.add("lineorder_dec", {"compression": COMP["zip"], "lineOrder": C.DECREASING_Y},
          rgb(60, 70))

    for tag, v in (("aces2065", (0.7347, 0.2653, 0.0, 1.0, 0.0001, -0.0770, 0.32168, 0.33767)),
                   ("acescg", (0.713, 0.293, 0.165, 0.830, 0.128, 0.044, 0.32168, 0.33767)),
                   ("rec2020", (0.708, 0.292, 0.170, 0.797, 0.131, 0.046, 0.3127, 0.3290)),
                   ("p3d65", (0.680, 0.320, 0.265, 0.690, 0.150, 0.060, 0.3127, 0.3290))):
        c.add(f"chroma_{tag}", {"compression": COMP["zip"], "chromaticities": v},
              rgb(20, 24))

    p0 = OpenEXR.Part({"compression": COMP["zip"], "name": "depth"},
                      {"Z": lum.astype("float32")})
    p1 = OpenEXR.Part({"compression": COMP["piz"], "name": "beauty"}, rgb(40, 50, seed=7))
    path = os.path.join(out, "multipart.exr")
    OpenEXR.File([p0, p1]).write(path)
    c.finish("multipart", path)

    c.add("tiny_1x1", {"compression": COMP["zip"]}, rgb(1, 1))
    c.add("tiny_col", {"compression": COMP["piz"]}, rgb(64, 1))
    c.add("tiny_row", {"compression": COMP["piz"]}, rgb(1, 64))

    add_luminance_chroma(c, "ycbcr_even", 48, 40)
    add_luminance_chroma(c, "ycbcr_odd", 37, 23)

    open(os.path.join(out, "err_deep.exr"), "wb").write(
        raw_header(8, 8, [("R", 1, 1, 1)], version_flags=1 << 11,
                   part_type="deepscanline") + b"\0" * 64)
    c.finish("err_deep", "")
    whole = open(os.path.join(out, "half_piz_big.exr"), "rb").read()
    open(os.path.join(out, "err_truncated.exr"), "wb").write(whole[:len(whole) // 3])
    c.finish("err_truncated", "")
    open(os.path.join(out, "err_notexr.exr"), "wb").write(b"\x89PNG\r\n\x1a\n" + b"\0" * 64)
    c.finish("err_notexr", "")

    c.write_manifest()


if __name__ == "__main__":
    build(sys.argv[1] if len(sys.argv) > 1 else "exr_cases")
