// GENERATED by spirulae_splat/generate_vulkan_stubs.py — DO NOT EDIT.
//
// Throwing stubs for kernel-launch functions the Vulkan backend does not
// implement yet (training/meshing phases). They satisfy the linker for the
// portable engine layer; calling one throws. Regenerate after porting a
// module (a ported symbol must lose its stub) or when the engine grows new
// kernel calls.

#include <BilagridBindings.h>
#include <EngineInternal.h>
#include <PerPixelLoss.cuh>
#include <PixelWise.cuh>

#include <stdexcept>
#include <string>

namespace {
[[noreturn]] void _vk_stub(const char* name) {
    throw std::runtime_error(std::string("Vulkan backend: ") + name +
                             " is not implemented yet (training phase)");
}
}  // namespace

// from EngineInternal.h
void bilagrid_affine_identity_init(
    float* grids, int N, int L, int H, int W, backend::Stream stream) { _vk_stub("bilagrid_affine_identity_init"); }

// from BilagridBindings.h
void bilagrid_depth_patched_sample_backward_v1(
    BilagridReader bilagrid,
    const float* depth,
    const float* scalars,
    const int* offsets,
    const float* v_output,
    float* v_bilagrid,
    float* v_depth,
    int N, int L, int H, int W,
    int m, int h, int w, int h0, int w0,
    const int target_tile_size,
    const int mi_batch_size,
    backend::Stream stream
) { _vk_stub("bilagrid_depth_patched_sample_backward_v1"); }

// from BilagridBindings.h
void bilagrid_depth_patched_sample_forward(
    BilagridReader bilagrid,
    const float* depth,
    const float* scalars,
    const int* offsets,
    float* output,
    int N, int L, int H, int W,
    int m, int h, int w, int h0, int w0,
    backend::Stream stream
) { _vk_stub("bilagrid_depth_patched_sample_forward"); }

// from BilagridBindings.h
void bilagrid_depth_uniform_sample_backward_v1(
    BilagridReader bilagrid,
    const float* depth,
    const float* scalars,
    const float* v_output,
    float* v_bilagrid,
    float* v_depth,
    int N, int L, int H, int W,
    int h, int w,
    const int target_tile_size,
    backend::Stream stream,
    const int* grid_indices ) { _vk_stub("bilagrid_depth_uniform_sample_backward_v1"); }

// from BilagridBindings.h
void bilagrid_depth_uniform_sample_forward(
    BilagridReader bilagrid,
    const float* depth,
    const float* scalars,
    float* output,
    int N, int L, int H, int W,
    int h, int w,
    backend::Stream stream,
    const int* grid_indices ) { _vk_stub("bilagrid_depth_uniform_sample_forward"); }

// from EngineInternal.h
void bilagrid_encode_q16_launch(
    const float* grids,
    uint16_t* grids_q16,
    float2* value_bounds,
    int64_t total_cells,
    backend::Stream stream
) { _vk_stub("bilagrid_encode_q16_launch"); }

// from BilagridBindings.h
void bilagrid_loglinear_patched_sample_backward_v1(
    BilagridReader bilagrid,
    const float* rgb,
    const int* offsets,
    const float* v_output,
    float* v_bilagrid,
    float* v_rgb,
    int N, int L, int H, int W,
    int m, int h, int w, int h0, int w0,
    const int target_tile_size,
    const int mi_batch_size,
    backend::Stream stream
) { _vk_stub("bilagrid_loglinear_patched_sample_backward_v1"); }

// from BilagridBindings.h
void bilagrid_loglinear_patched_sample_forward(
    BilagridReader bilagrid,
    const float* rgb,
    const int* offsets,
    float* output,
    int N, int L, int H, int W,
    int m, int h, int w, int h0, int w0,
    backend::Stream stream
) { _vk_stub("bilagrid_loglinear_patched_sample_forward"); }

// from BilagridBindings.h
void bilagrid_loglinear_uniform_sample_backward_v1(
    BilagridReader bilagrid,
    const float* rgb,
    const float* v_output,
    float* v_bilagrid,
    float* v_rgb,
    int N, int L, int H, int W,
    int h, int w,
    const int target_tile_size,
    backend::Stream stream,
    const int* grid_indices ) { _vk_stub("bilagrid_loglinear_uniform_sample_backward_v1"); }

// from BilagridBindings.h
void bilagrid_loglinear_uniform_sample_forward(
    BilagridReader bilagrid,
    const float* rgb,
    float* output,
    int N, int L, int H, int W,
    int h, int w,
    backend::Stream stream,
    const int* grid_indices ) { _vk_stub("bilagrid_loglinear_uniform_sample_forward"); }

// from BilagridBindings.h
void bilagrid_normal_patched_sample_backward_v1(
    BilagridReader bilagrid,
    const float* rgb,
    const int* offsets,
    const float* v_output,
    float* v_bilagrid,
    float* v_rgb,
    int N, int L, int H, int W,
    int m, int h, int w, int h0, int w0,
    const int target_tile_size,
    const int mi_batch_size,
    backend::Stream stream
) { _vk_stub("bilagrid_normal_patched_sample_backward_v1"); }

// from BilagridBindings.h
void bilagrid_normal_patched_sample_forward(
    BilagridReader bilagrid,
    const float* rgb,
    const int* offsets,
    float* output,
    int N, int L, int H, int W,
    int m, int h, int w, int h0, int w0,
    backend::Stream stream
) { _vk_stub("bilagrid_normal_patched_sample_forward"); }

// from BilagridBindings.h
void bilagrid_normal_uniform_sample_backward_v1(
    BilagridReader bilagrid,
    const float* rgb,
    const float* v_output,
    float* v_bilagrid,
    float* v_rgb,
    int N, int L, int H, int W,
    int h, int w,
    const int target_tile_size,
    backend::Stream stream,
    const int* grid_indices ) { _vk_stub("bilagrid_normal_uniform_sample_backward_v1"); }

// from BilagridBindings.h
void bilagrid_normal_uniform_sample_forward(
    BilagridReader bilagrid,
    const float* rgb,
    float* output,
    int N, int L, int H, int W,
    int h, int w,
    backend::Stream stream,
    const int* grid_indices ) { _vk_stub("bilagrid_normal_uniform_sample_forward"); }

// from BilagridBindings.h
void bilagrid_patched_sample_backward_v2(
    BilagridReader bilagrid,
    const float* rgb,
    const int* offsets,
    const float* v_output,
    float* v_bilagrid,
    float* v_rgb,
    int N, int L, int H, int W,
    int m, int h, int w, int h0, int w0,
    backend::Stream stream
) { _vk_stub("bilagrid_patched_sample_backward_v2"); }

// from BilagridBindings.h
void bilagrid_patched_sample_forward(
    BilagridReader bilagrid,
    const float* rgb,
    const int* offsets,
    float* output,
    int N, int L, int H, int W,
    int m, int h, int w, int h0, int w0,
    backend::Stream stream
) { _vk_stub("bilagrid_patched_sample_forward"); }

// from BilagridBindings.h
void bilagrid_ppisp_packed_sample_backward(
    BilagridReader bilagrid,
    const int64_t* image_indices,
    const float* coords,
    const float* rgb,
    const float* v_output,
    float* v_bilagrid,
    float* v_coords,
    float* v_rgb,
    int N, int L, int H, int W,
    int nnz,
    backend::Stream stream
) { _vk_stub("bilagrid_ppisp_packed_sample_backward"); }

// from BilagridBindings.h
void bilagrid_ppisp_packed_sample_forward(
    BilagridReader bilagrid,
    const int64_t* image_indices,
    const float* coords,
    const float* rgb,
    float* output,
    int N, int L, int H, int W,
    int nnz,
    backend::Stream stream
) { _vk_stub("bilagrid_ppisp_packed_sample_forward"); }

// from BilagridBindings.h
void bilagrid_ppisp_patched_sample_backward_v1(
    BilagridReader bilagrid,
    const float* rgb,
    const int* offsets,
    const float* v_output,
    float* v_bilagrid,
    float* v_rgb,
    int N, int L, int H, int W,
    int m, int h, int w, int h0, int w0,
    const int target_tile_size,
    const int mi_batch_size,
    backend::Stream stream
) { _vk_stub("bilagrid_ppisp_patched_sample_backward_v1"); }

// from BilagridBindings.h
void bilagrid_ppisp_patched_sample_forward(
    BilagridReader bilagrid,
    const float* rgb,
    const int* offsets,
    float* output,
    int N, int L, int H, int W,
    int m, int h, int w, int h0, int w0,
    backend::Stream stream
) { _vk_stub("bilagrid_ppisp_patched_sample_forward"); }

// from BilagridBindings.h
void bilagrid_ppisp_sample_backward(
    BilagridReader bilagrid,
    const float* coords,
    const float* rgb,
    const float* v_output,
    float* v_bilagrid,
    float* v_coords,
    float* v_rgb,
    int N, int L, int H, int W,
    int m, int h, int w,
    backend::Stream stream
) { _vk_stub("bilagrid_ppisp_sample_backward"); }

// from BilagridBindings.h
void bilagrid_ppisp_sample_forward(
    BilagridReader bilagrid,
    const float* coords,
    const float* rgb,
    float* output,
    int N, int L, int H, int W,
    int m, int h, int w,
    backend::Stream stream
) { _vk_stub("bilagrid_ppisp_sample_forward"); }

// from BilagridBindings.h
void bilagrid_ppisp_uniform_sample_backward_v1(
    BilagridReader bilagrid,
    const float* rgb,
    const float* v_output,
    float* v_bilagrid,
    float* v_rgb,
    int N, int L, int H, int W,
    int h, int w,
    const int target_tile_size,
    backend::Stream stream,
    const int* grid_indices ) { _vk_stub("bilagrid_ppisp_uniform_sample_backward_v1"); }

// from BilagridBindings.h
void bilagrid_ppisp_uniform_sample_forward(
    BilagridReader bilagrid,
    const float* rgb,
    float* output,
    int N, int L, int H, int W,
    int h, int w,
    backend::Stream stream,
    const int* grid_indices ) { _vk_stub("bilagrid_ppisp_uniform_sample_forward"); }

// from BilagridBindings.h
void bilagrid_sample_backward(
    BilagridReader bilagrid,
    const float* coords,
    const float* rgb,
    const float* v_output,
    float* v_bilagrid,
    float* v_coords,
    float* v_rgb,
    int N, int L, int H, int W,
    int m, int h, int w,
    backend::Stream stream
) { _vk_stub("bilagrid_sample_backward"); }

// from BilagridBindings.h
void bilagrid_sample_forward(
    BilagridReader bilagrid,
    const float* coords,
    const float* rgb,
    float* output,
    int N, int L, int H, int W,
    int m, int h, int w,
    backend::Stream stream
) { _vk_stub("bilagrid_sample_forward"); }

// from EngineInternal.h
void bilagrid_scatter_floats(
    const float* src, const int* indices, int n,
    float* dst, backend::Stream stream) { _vk_stub("bilagrid_scatter_floats"); }

// from BilagridBindings.h
void bilagrid_uniform_sample_backward_v1(
    BilagridReader bilagrid,
    const float* rgb,
    const float* v_output,
    float* v_bilagrid,
    float* v_rgb,
    int N, int L, int H, int W,
    int h, int w,
    const int target_tile_size,
    backend::Stream stream,
    const int* grid_indices ) { _vk_stub("bilagrid_uniform_sample_backward_v1"); }

// from BilagridBindings.h
void bilagrid_uniform_sample_backward_v2(
    BilagridReader bilagrid,
    const float* rgb,
    const float* v_output,
    float* v_bilagrid,
    float* v_rgb,
    int N, int L, int H, int W,
    int h, int w,
    backend::Stream stream
) { _vk_stub("bilagrid_uniform_sample_backward_v2"); }

// from BilagridBindings.h
void bilagrid_uniform_sample_forward(
    BilagridReader bilagrid,
    const float* rgb,
    float* output,
    int N, int L, int H, int W,
    int h, int w,
    backend::Stream stream,
    const int* grid_indices ) { _vk_stub("bilagrid_uniform_sample_forward"); }

// from BilagridBindings.h
void channel_mean_backward(
    BilagridReader bilagrid,
    const float* v_channel_mean,
    float* v_bilagrid,
    int N, int C, int L, int H, int W, bool inplace,
    backend::Stream stream
) { _vk_stub("channel_mean_backward"); }

// from BilagridBindings.h
void channel_mean_forward(
    BilagridReader bilagrid,
    float* channel_mean,
    int N, int C, int L, int H, int W,
    backend::Stream stream
) { _vk_stub("channel_mean_forward"); }

// from PerPixelLoss.cuh
LossValues compute_multi_scale_per_pixel_losses(
    int num_loss_scales,
    TorchTensorView render_rgb,
    TorchTensorView ref_rgb,
    TorchTensorView render_depth,
    TorchTensorView ref_depth,
    TorchTensorView render_normal,
    TorchTensorView depth_normal,
    TorchTensorView ref_normal,
    TorchTensorView render_Ts,
    TorchTensorView rgb_dist,
    TorchTensorView depth_dist,
    TorchTensorView normal_dist,
    TorchTensorView median_depth,
    TorchTensorView median_normal,
    TorchTensorView ref_alpha,
    bool has_mask,
    const std::array<float, (int)LossWeightIndex::length> loss_weights_0,
    const float w_ssim,
    TorchTensorView v_losses,
    std::vector<bool> needs_input_grad,
    long num_train_images,
    TorchTensorView camera_indices,
    TorchTensorView loss_map_out,
    int loss_map_mode,
    float robust_edge_aware_quantile,
    PerPixelGrads& grads_out
) { _vk_stub("compute_multi_scale_per_pixel_losses"); }

// from PixelWise.cuh
void compute_ppsip_regularization_backward(
    TorchTensorView ppisp_params,        
    const std::array<float, (int)PPISPRegLossIndex::length> loss_weights_0,
    TorchTensorView raw_losses,          
    TorchTensorView v_losses,            
    std::string param_type,
    TorchTensorView v_ppisp_params       
) { _vk_stub("compute_ppsip_regularization_backward"); }

// from PixelWise.cuh
void compute_ppsip_regularization_forward(
    TorchTensorView ppisp_params,        
    const std::array<float, (int)PPISPRegLossIndex::length> loss_weights_0,
    std::string param_type,
    TorchTensorView losses,              
    TorchTensorView raw_losses           
) { _vk_stub("compute_ppsip_regularization_forward"); }

// from EngineInternal.h
void fused_bilagrid_tv_adagrad(
    float*    grids,                     
    uint16_t* grids_q16,                 
    float2*   value_bounds,              
    float*    accum_f,                   
    uint8_t*  packed,                    
    float2*   quant_bounds,              
    const float* image_grad,
    const int*   cam_indices,
    int N_grids, int C_batch, int C,
    int L, int H, int W,
    float lr,
    float tv_weight,
    bool quantize,
    int  quant_bits,
    bool value_quantize,
    backend::Stream stream
) { _vk_stub("fused_bilagrid_tv_adagrad"); }

// from EngineInternal.h
void fused_bilagrid_tv_adam(
    float*    grids,                     
    uint16_t* grids_q16,                 
    float2*   value_bounds,              
    float*    g1_f,    float*  g2_f,
    uint8_t*  packed,                    
    float4*   quant_bounds,
    const float* image_grad,
    const int*   cam_indices,
    int N_grids, int C_batch, int C,
    int L, int H, int W,
    float lr,
    float tv_weight,
    int32_t adam_step,
    bool quantize,
    int  quant_bits,
    bool value_quantize,
    backend::Stream stream
) { _vk_stub("fused_bilagrid_tv_adam"); }

// from PixelWise.cuh
void launch_warp_byte_to_float_equi(
    const void* d_byte, bool input_is_u16,
    int B, int Hin, int Win, int C,
    float* d_float_out, int K, int Hout, int Wout,
    const float* d_axes) { _vk_stub("launch_warp_byte_to_float_equi"); }

// from PixelWise.cuh
void launch_warp_byte_to_float_wide(
    std::string camera_model,
    const float* d_intrins,                 
    const float* d_dist_coeffs,             
    const void* d_byte, bool input_is_u16,
    int B, int Hin, int Win, int C,
    float* d_float_out, int K, int Hout, int Wout,
    const float* d_axes) { _vk_stub("launch_warp_byte_to_float_wide"); }

// from PixelWise.cuh
void launch_warp_depth_equi(
    const void* d_depth, uint32_t elem_size,
    int B, int Hin, int Win,
    float* d_float_out, int K, int Hout, int Wout,
    const float* d_axes, bool input_is_ray_depth) { _vk_stub("launch_warp_depth_equi"); }

// from PixelWise.cuh
void launch_warp_depth_wide(
    std::string camera_model,
    const float* d_intrins,
    const float* d_dist_coeffs,
    const void* d_depth, uint32_t elem_size,
    int B, int Hin, int Win,
    int in_H, int in_W,
    float* d_float_out, int K, int Hout, int Wout,
    const float* d_axes, bool input_is_ray_depth) { _vk_stub("launch_warp_depth_wide"); }

// from PixelWise.cuh
void launch_warp_mask_equi(
    const uint8_t* d_byte_mask,
    int B, int Hin, int Win,
    uint8_t* d_byte_out, int K, int Hout, int Wout,
    const float* d_axes) { _vk_stub("launch_warp_mask_equi"); }

// from PixelWise.cuh
void launch_warp_mask_wide(
    std::string camera_model,
    const float* d_intrins,                 
    const float* d_dist_coeffs,             
    const uint8_t* d_byte_mask,
    int B, int Hin, int Win,
    uint8_t* d_byte_out, int K, int Hout, int Wout,
    const float* d_axes) { _vk_stub("launch_warp_mask_wide"); }

// from PixelWise.cuh
void launch_warp_normal_equi(
    const void* d_normal, uint32_t elem_size,
    int B, int Hin, int Win,
    float* d_float_out, int K, int Hout, int Wout,
    const float* d_axes) { _vk_stub("launch_warp_normal_equi"); }

// from PixelWise.cuh
void launch_warp_normal_wide(
    std::string camera_model,
    const float* d_intrins,
    const float* d_dist_coeffs,
    const void* d_normal, uint32_t elem_size,
    int B, int Hin, int Win,
    int in_H, int in_W,
    float* d_float_out, int K, int Hout, int Wout,
    const float* d_axes) { _vk_stub("launch_warp_normal_wide"); }

// from EngineInternal.h
void ppisp_add_into_grad(
    const float* src, float* dst, size_t n, backend::Stream stream) { _vk_stub("ppisp_add_into_grad"); }

// from PixelWise.cuh
void ppisp_backward(
    DeviceTensor3D<float3> in_image,     
    TorchTensorView ppisp_params,        
    TorchTensorView intrins,             
    const float actual_image_width,
    const float actual_image_height,
    DeviceTensor3D<float3> v_out_image,  
    std::string param_type,
    TorchTensorView cam_indices,         
    DeviceTensor3D<float3> v_in_image,   
    TorchTensorView v_ppisp_params       
) { _vk_stub("ppisp_backward"); }

// from PixelWise.cuh
void ppisp_forward(
    DeviceTensor3D<float3> in_image,     
    TorchTensorView ppisp_params,        
    TorchTensorView intrins,             
    const float actual_image_width,
    const float actual_image_height,
    std::string param_type,
    TorchTensorView cam_indices,         
    DeviceTensor3D<float3> out_image     
) { _vk_stub("ppisp_forward"); }

// from EngineInternal.h
void ppisp_original_default_init(
    float* params, int N, backend::Stream stream) { _vk_stub("ppisp_original_default_init"); }

// from BilagridBindings.h
void tv_loss_backward(
    BilagridReader bilagrid,
    const float v_tv_loss,
    float* v_bilagrid,
    int N, int C, int L, int H, int W, bool inplace,
    backend::Stream stream
) { _vk_stub("tv_loss_backward"); }

// from BilagridBindings.h
void tv_loss_forward(
    BilagridReader bilagrid,
    float* tv_loss,
    int N, int C, int L, int H, int W,
    backend::Stream stream
) { _vk_stub("tv_loss_forward"); }

// from EngineInternal.h
void uint16_depth_to_float_raw(const uint16_t* d_in, float* d_out,
                               int B, int H, int W, int C) { _vk_stub("uint16_depth_to_float_raw"); }

// from EngineInternal.h
void uint16_image_to_float_raw(const uint16_t* d_in, float* d_out,
                               int B, int H, int W, int C) { _vk_stub("uint16_image_to_float_raw"); }

// from EngineInternal.h
void uint8_image_to_float_raw (const uint8_t*  d_in, float* d_out,
                               int B, int H, int W, int C) { _vk_stub("uint8_image_to_float_raw"); }

// from EngineInternal.h
void uint8_normal_to_float_raw(const uint8_t*  d_in, float* d_out,
                               int B, int H, int W, int C) { _vk_stub("uint8_normal_to_float_raw"); }
